import type { BrowserWindow } from 'electron';
import type { WindowStateStore } from '../../../apps/desktop/src/main/window-state';
import { rmSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
export async function runHtmlPreviewFlow(flow: { frame(): any; outputs(): Promise<any>; window: BrowserWindow; evaluate(script: string): Promise<any>; wait(expression: string, label: string): Promise<void>; click(selector: string, text?: string): Promise<void>; key(key: string): Promise<void>; capture(name: string): Promise<void>; store: WindowStateStore; calls: unknown[]; setConnected(value: boolean): void; fixture: string; http(path: string): Promise<any> }) {
  const { window, evaluate, wait, click, capture, fixture } = flow;
  const reopen = async () => { if (await evaluate(`document.querySelector('[aria-label="Toggle side panel"]')?.getAttribute("aria-checked") === "false"`)) await click('[aria-label="Toggle side panel"]'); };
  await wait('document.querySelectorAll(".dock-suggested-list>li").length === 1 && panelState().body.includes("index.html")', 'actual successful EditTool single HTML suggestion');
  await capture('html-01-native-edit-output');
  await click('[aria-label="View source of index.html"]');
  await wait('[...document.querySelectorAll("diffs-container")].some(node=>node.shadowRoot?.textContent.includes("Actual native edited HTML")) && document.querySelector(".browser-viewport") === null', 'source action opens text independently');
  if ((flow.calls as any[]).some(call => call.method === 'openHtmlPreview')) throw new Error('Source inspection acquired a preview.');
  await capture('html-02-source');
  await click('[aria-label="Close index.html tab"]'); await reopen();
  await click('.dock-suggested-list>li>button:first-child', 'index.html');
  await wait('panelState().saved.state.dock.tabs.some(tab=>tab.browserTarget) && document.querySelector(".browser-viewport img")?.naturalWidth>0', 'original native HTML preview');
  await wait('document.querySelector(".browser-viewport-live img")?.clientHeight > 500', 'native viewport resize settled before input');
  await capture('html-03-native-page-assets');
  const state = flow.store.bootstrap().state!;
  const url = state.sessionBrowserObservations?.find(row => row.url.includes('/site/index.html'))?.url;
  if (!url) throw new Error('Original worker preview URL was not retained in native browser history.');
  if ((await fetch(new URL('private.json', url))).status !== 410) throw new Error('Preview served unrelated project bytes.');
  // Real outer Electron pointer input flows through BrowserPanel's original captured viewport.
  const context = flow.frame().context;
  const point = await evaluate(`(()=>{const img=document.querySelector(".browser-viewport-live img"), r=img.getBoundingClientRect();return{x:r.x+30/${context.width}*r.width,y:r.y+135/${context.height}*r.height}})()`);
  if (!window.webContents.debugger.isAttached()) window.webContents.debugger.attach('1.3');
  await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseMoved', ...point });
  await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 });
  await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 });
  await wait(`document.querySelector('[aria-label="Page address"]')?.value.endsWith("/site/about.html") && document.querySelector(".browser-viewport-live img") !== null`, 'relative link uses captured saved output');
  await capture('html-04-relative-navigation');
  await click('[aria-label="Back"]');
  await wait(`document.querySelector('[aria-label="Page address"]')?.value.endsWith("/site/index.html") && document.querySelector(".browser-viewport-live img") !== null`, 'native original-page Back history');
  await capture('html-05-native-back');
  rmSync(join(fixture, 'project', 'site', 'index.html'));
  if ((await flow.outputs()).outputs.some((row: any) => row.kind === 'html-preview')) throw new Error('Missing HTML remained a current Suggested output.');
  if ((await fetch(url)).status !== 410) throw new Error('Missing original HTML did not retire the lease.');
  await click('[aria-label="Reload page"]');
  await wait('document.querySelector(".browser-viewport-live img") !== null', 'original browser reload after source loss');
  await capture('html-06-missing-original');
  window.webContents.reload();
  await wait('typeof panelState === "function" && panelState().saved.state.dock.tabs.some(tab=>tab.browserTarget)', 'actual document reload retains original browser target');
  await capture('html-07-reloaded-history');
  for (let i = 0; i < 40 && (await fetch(url)).status !== 410; i++) await new Promise(resolve => setTimeout(resolve, 50));
  if ((await fetch(url)).status !== 410) throw new Error('Retired document kept its preview server lease.');
  if ((flow.calls as any[]).filter(call => call.method === 'openHtmlPreview').length !== 1) throw new Error('Reload reacquired a historical HTML preview.');
  flow.setConnected(false);
  await wait('panelState().body.toLowerCase().includes("offline") || panelState().body.includes("Reconnect")', 'offline original preview');
  await capture('html-08-offline');
  flow.setConnected(true);
  const selections = readFileSync(join(fixture, 'html-provider.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line));
  if (selections.filter(row => row.name === 'edit').length !== 1 || selections.filter(row => row.name === 'write').length !== 5) throw new Error('Historical output tool selection replayed.');
}
