import type { BrowserWindow } from 'electron';
import type { WindowStateStore } from '../../../apps/desktop/src/main/window-state';
import { join } from 'node:path';
export async function runMcpOwnerFlow(flow: { window: BrowserWindow; evaluate(script: string): Promise<any>; wait(expression: string, label: string): Promise<void>; click(selector: string, text?: string): Promise<void>; key(key: string): Promise<void>; capture(name: string): Promise<void>; store: WindowStateStore; calls: unknown[]; fixture: string; http(path: string, body?: unknown): Promise<any>; setConnected(value: boolean): void }) {
  const { window, evaluate, wait, click, capture, store } = flow;
  const acquisitions = () => flow.calls.filter((value: any) => value.method === 'mcpOwner' && value.args[1].type === 'acquire');
  if (acquisitions().length) throw new Error('Projectless route automatically acquired a native owner.');
  if ((await flow.http('/v1/state')).sessions.length) throw new Error('Fixture created a conversation.');
  const approveStartup = async () => { await wait('document.querySelector(".interaction-card")?.textContent.includes("Connect directory apps?")', 'original native startup permission'); await click('.interaction-actions button', 'Yes'); };
  await capture('owner-01-explicit-connect'); await click('.dock-empty-panel-label', 'Connect apps');
  await approveStartup();
  await wait('panelState().actions.includes("Counter app")', 'actual directory-native discovery');
  await capture('owner-02-native-catalogue');
  await click('.dock-empty-panel-label', 'Counter app');
  await wait('document.querySelector("iframe[title=\\"Counter app\\"]") !== null', 'original directory app iframe');
  const frame = () => window.webContents.mainFrame.frames.find(value => value.url === 'about:srcdoc');
  const inspect = (script: string) => { const value = frame(); if (!value) throw new Error('Missing original iframe'); return value.executeJavaScript(script, true); };
  const waitFrame = async (expression: string, label: string) => { for (let i = 0; i < 400; i++) { if (frame() && await inspect(expression)) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Timed out: ' + label); };
  const clickFrame = async (id: string) => {
    const outer = await evaluate('(()=>{const r=document.querySelector(".mcp-app-frame").getBoundingClientRect();return{x:r.x,y:r.y};})()');
    const inner: any = await inspect(`(()=>{const r=document.getElementById(${JSON.stringify(id)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    const point = { x: outer.x + inner.x, y: outer.y + inner.y }; window.webContents.focus();
    const hit = await evaluate(`document.elementFromPoint(${point.x},${point.y})?.tagName`);
    flow.calls.push({ method: "iframe-pointer", id, point, hit });
    if (hit !== "IFRAME") throw new Error("The actual app button is outside its visible iframe.");
    if (!window.webContents.debugger.isAttached()) window.webContents.debugger.attach('1.3');
    for (const [type, extra] of [['mouseMoved', {}], ['mousePressed', { button: 'left', clickCount: 1 }], ['mouseReleased', { button: 'left', clickCount: 1 }]] as const) await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type, ...point, ...extra });
  };
  const approve = async (choice: 'Approve' | 'Deny') => { await wait('document.querySelector(".interaction-card") !== null', 'native owner permission'); await click('.interaction-option', choice); await click('.interaction-actions button', 'Choose'); await wait('document.querySelector(".interaction-card") === null', 'native permission settlement'); };
  await approve('Approve'); await waitFrame('document.querySelector("#count")?.textContent === "Count 0"', 'actual no-conversation app result');
  if (!(await evaluate('document.querySelector(".mcp-directory-status")?.textContent')).includes(join(flow.fixture, 'project'))) throw new Error('Admitted default directory is not shown.');
  if (await inspect('(()=>{try{return !!parent.document}catch{return false}})()')) throw new Error('Opaque app can access parent DOM.');
  await capture('owner-03-ready-permission');
  await clickFrame('watch'); await waitFrame('document.querySelector("#resource-count")?.textContent === "Watching"', 'native resource subscription');
  await clickFrame('increment'); await approve('Approve'); await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'native approved mutation'); await waitFrame('document.querySelector("#resource-count")?.textContent === "Resource count 1"', 'native subscription notification and resync read'); await capture('owner-04-mutation');
  await clickFrame('increment'); await approve('Deny'); await waitFrame('document.querySelector("#result")?.textContent.includes("denied by user")', 'native denial');
  if (await inspect('document.querySelector("#count")?.textContent') !== 'Count 1') throw new Error('Denied operation changed native count.'); await capture('owner-05-denial');
  await clickFrame('unwatch'); await waitFrame('document.querySelector("#resource-count")?.textContent === "Stopped"', 'native subscription release');
  const original = store.bootstrap().state!.dock!.tabs.find(value => value.kind === 'mcp-app')!;
  if (original.target !== 'host' || original.mcpApp?.directory?.projectId !== null) throw new Error('Projectless app borrowed a conversation/project.');
  await click('[aria-label="Toggle side panel"]'); await click('[aria-label="Toggle side panel"]'); await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'same owner retained across hide'); await capture('owner-06-hide-return');
  flow.setConnected(false); await wait('document.querySelector(".mcp-app-frame") === null', 'offline app retirement'); await capture('owner-07-offline');
  const beforeReturn = acquisitions().length; flow.setConnected(true); await wait('document.querySelector(".mcp-app-empty button")?.disabled === false', 'explicit reconnect button');
  if (acquisitions().length !== beforeReturn) throw new Error('Reconnect acquired a replacement automatically.');
  await click('.mcp-app-empty button', 'Open app'); await approveStartup(); await approve('Approve'); await waitFrame('document.querySelector("#count")?.textContent === "Count 0"', 'fresh deliberately acquired native owner'); await capture('owner-08-fresh-owner');
  const beforeReload = acquisitions().length, documentId = await evaluate('panelState().documentId'); window.webContents.reload();
  await wait('typeof window.panelState === "function" && panelState().documentId !== ' + JSON.stringify(documentId), 'actual replacement renderer');
  await wait('document.querySelector(".mcp-app-empty button")?.disabled === false', 'saved descriptor requires explicit Open');
  if (acquisitions().length !== beforeReload || frame()) throw new Error('Restoration replayed native acquisition.');
  if (store.bootstrap().state!.dock!.tabs.find(value => value.kind === 'mcp-app')?.id !== original.id) throw new Error('Restoration changed saved identity.'); await capture('owner-09-restored');
  await click('.mcp-app-empty button', 'Open app'); await approveStartup(); await approve('Approve'); await waitFrame('document.querySelector("#count")?.textContent === "Count 0"', 'fresh document owner'); await capture('owner-10-restored-open');
  await clickFrame('increment'); await wait('document.querySelector(".interaction-card") !== null', 'pending owner permission');
  await click('[aria-label="Close Counter app tab"]'); await wait('!panelState().tabs.some(tab=>tab.label.includes("Counter app")) && document.querySelector(".interaction-card") === null', 'exact close cancels permission'); await capture('owner-11-cancelled-close');
  if ((await flow.http('/v1/state')).sessions.length || flow.calls.some((value: any) => value.method === 'sessionMcpApp' || value.method === 'getSessionMcp')) throw new Error('Directory app flow borrowed a conversation.');
}
