import type { BrowserWindow } from 'electron';
import type { WindowStateStore } from '../../../apps/desktop/src/main/window-state';
export async function runMcpFlow(flow: { window: BrowserWindow; evaluate(script: string): Promise<any>; wait(expression: string, label: string): Promise<void>; click(selector: string, text?: string): Promise<void>; key(key: string): Promise<void>; capture(name: string): Promise<void>; store: WindowStateStore; calls: unknown[]; connection: { hostId: string }; http(path: string, body?: unknown): Promise<any>; setConnected(connected: boolean): void }) {
  const { window, evaluate, wait, click, key, capture, store } = flow;
  await wait('panelState().actions.includes("Counter app")', 'actual native MCP thread entrypoint');
  const actions = await evaluate('panelState().actions');
  if (JSON.stringify(actions) !== JSON.stringify(['Files', 'Side chat', 'Browser', 'Counter app'])) throw new Error('Wrong provider action order: ' + JSON.stringify(actions));
  await capture('mcp-01-provider-action');
  await click('.dock-empty-panel-label', 'Counter app');
  await wait('document.querySelector("iframe[title=\\"Counter app\\"]") !== null', 'sandboxed app frame');
  const frame = () => window.webContents.mainFrame.frames.find(value => value.url === 'about:srcdoc');
  const inspect = async (script: string) => { const value = frame(); if (!value) throw new Error('Missing original SDK iframe'); return value.executeJavaScript(script, true); };
  const waitFrame = async (expression: string, label: string) => { for (let i = 0; i < 400; i++) { if (frame() && await inspect(expression)) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Timed out: ' + label); };
  const clickFrame = async (id: string) => {
    const outer = await evaluate('(()=>{const r=document.querySelector(".mcp-app-frame").getBoundingClientRect();return {x:r.x,y:r.y};})()');
    const inner = await inspect(`(()=>{const r=document.getElementById(${JSON.stringify(id)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    if (!inner || typeof inner !== "object" || !("x" in inner) || typeof inner.x !== "number" || !("y" in inner) || typeof inner.y !== "number") throw new Error("Invalid iframe target geometry.");
    const point = { x: outer.x + inner.x, y: outer.y + inner.y };
    window.webContents.focus();
    await new Promise(resolve => setTimeout(resolve, 150));
    flow.calls.push({ method: 'iframe-pointer', id, point, outer, inner, focused: window.isFocused(), hit: await evaluate(`document.elementFromPoint(${point.x},${point.y})?.tagName`) });
    if (!window.webContents.debugger.isAttached()) window.webContents.debugger.attach('1.3');
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseMoved', ...point });
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 });
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 });
    await new Promise(resolve => setTimeout(resolve, 150));
    flow.calls.push({ method: 'iframe-after-pointer', body: await inspect('document.body.innerText'), focus: await inspect('document.activeElement?.id'), events: await inspect('window.mcpEvents') });
  };
  const approve = async (choice: "Approve" | "Deny") => {
    await wait('document.querySelector(".interaction-card") !== null', 'actual session permission');
    await click('.interaction-option', choice); await click('.interaction-actions button', 'Choose');
    await wait('document.querySelector(".interaction-card") === null', 'permission response settles');
  };
  await approve("Approve");
  await waitFrame('document.querySelector("#count")?.textContent === "Count 0"' , 'SDK initialize and original-server tool read');
  if (await inspect('(()=>{try{return !!parent.document}catch{return false}})()')) throw new Error('Untrusted app can read host DOM.');
  await capture('mcp-02-ready-sandbox');
  const original = store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')!;
  await clickFrame('increment'); await approve('Approve'); await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'actual native MCP tool mutation'); await capture('mcp-03-native-result');
  await clickFrame('increment'); await approve('Deny'); await waitFrame('document.querySelector("#result")?.textContent.includes("could not be confirmed")', 'native denied call reaches app');
  if (await inspect('document.querySelector("#count")?.textContent') !== 'Count 1') throw new Error('Denied native operation changed visible state.');
  await capture('mcp-03b-native-denial');
  await clickFrame('notes'); await waitFrame('document.querySelector("#result")?.textContent.includes("original MCP provider")', 'actual native resource read'); await capture('mcp-04-resource');
  await clickFrame('link'); await wait('document.querySelector("dialog[aria-label=\\"Open external link\\"]") !== null', 'explicit external-link decision');
  await capture('mcp-05-link-decision'); await click('.mcp-app-link button', 'Cancel'); await waitFrame('document.querySelector("#result")?.textContent === "Link cancelled"', 'link cancellation reaches app');
  await click('[aria-label="Toggle side panel"]'); await click('[aria-label="Toggle side panel"]');
  await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'hide/reopen preserves app and original tool state');
  if (store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')?.id !== original.id) throw new Error('Hide/reopen changed original app descriptor.');
  await capture('mcp-06-retained');
  await click('[aria-label="Open side panel tab"]'); await key('ESCAPE'); await wait('panelState().menu.length === 0', 'app menu keyboard dismissal');
  await click('[aria-label="Close Counter app tab"]'); await wait('!panelState().tabs.some(tab => tab.label.includes("Counter app"))', 'app close drains and removes original tab');
  if (!flow.calls.some((value: any) => value.method === 'sessionMcpApp' && value.args[1].type === 'close')) throw new Error('Close did not reach original host channel.');
  await capture('mcp-07-closed');
  await click('[aria-label="Toggle side panel"]');
  await wait('panelState().actions.includes("Counter app")', 'real app action returns after close'); await click('.dock-empty-panel-label', 'Counter app');
  await approve('Approve');
  await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'new deliberate app keeps server state');
  if (store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')?.id === original.id) throw new Error('Explicit reopen recycled a retired presentation.');
  await capture('mcp-08-deliberate-reopen');
  const currentId = store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')!.id;
  flow.setConnected(false);
  await wait('document.querySelector(".mcp-app-frame") === null && document.querySelector(".mcp-app-empty button")?.disabled === true', 'observed host loss retires app and disables admission');
  await capture('mcp-09-offline');
  const openings = () => flow.calls.filter((value: any) => value.method === 'sessionMcpApp' && value.args[1].type === 'open').length;
  const beforeReturn = openings(); flow.setConnected(true);
  await wait('document.querySelector(".mcp-app-empty button")?.disabled === false', 'original host reconnect enables deliberate recovery');
  if (openings() !== beforeReturn) throw new Error('Reconnect automatically reopened the app.');
  await click('.mcp-app-empty button', 'Open app'); await approve('Approve');
  await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'reconnect explicit opening keeps native provider state');
  if (store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')?.id !== currentId) throw new Error('Reconnect changed saved presentation identity.');
  await capture('mcp-10-recovered');
  const beforeReload = openings(), originalDocument = await evaluate('panelState().documentId');
  window.webContents.reload();
  await wait('typeof window.panelState === "function" && panelState().documentId !== ' + JSON.stringify(originalDocument), 'new renderer document');
  await wait('document.querySelector(".mcp-app-empty button")?.disabled === false', 'persisted original descriptor requires deliberate Open');
  if (openings() !== beforeReload || frame()) throw new Error('Restoration automatically replayed the old app.');
  if (store.bootstrap().state!.dock!.tabs.find(tab => tab.kind === 'mcp-app')?.id !== currentId) throw new Error('Reload changed the original saved app.');
  await capture('mcp-11-restored');
  await click('.mcp-app-empty button', 'Open app'); await approve('Approve');
  await waitFrame('document.querySelector("#count")?.textContent === "Count 1"', 'restored descriptor opens against current native owner');
  await capture('mcp-12-restored-open');
  await clickFrame('increment'); await wait('document.querySelector(".interaction-card") !== null', 'pending native permission before explicit app close');
  await click('[aria-label="Close Counter app tab"]');
  await wait('!panelState().tabs.some(tab => tab.label.includes("Counter app")) && document.querySelector(".interaction-card") === null', 'close cancels original native permission and drains');
  await capture('mcp-13-cancelled-close');
}
