import type { BrowserWindow } from 'electron';
import type { WindowStateStore } from '../../../apps/desktop/src/main/window-state';
import { readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
export async function runSuggestedFlow(flow: { window: BrowserWindow; evaluate(script: string): Promise<any>; wait(expression: string, label: string): Promise<void>; click(selector: string, text?: string): Promise<void>; key(key: string): Promise<void>; capture(name: string): Promise<void>; store: WindowStateStore; calls: unknown[]; inputs: unknown[]; setConnected(value: boolean): void; fixture: string; http(path: string): Promise<any>; prompt(text: string): Promise<unknown> }) {
  const { window, evaluate, wait, click, key, capture, fixture } = flow;
  const reopen = async () => { if (await evaluate(`document.querySelector('[aria-label="Toggle side panel"]')?.getAttribute("aria-checked") === "false"`)) await click('[aria-label="Toggle side panel"]'); };
  const rows = '[...document.querySelectorAll(".dock-suggested-list button")].map(node=>node.textContent.trim())';
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 3', 'three actual saved outputs');
  const original = await evaluate(rows); if (!original.includes('summary.md') || original.some((row: string) => /input|failed/.test(row))) throw new Error('Read or failed input was suggested.');
  await capture('suggested-01-native-outputs');
  await click('.dock-suggested-list button', 'summary.md');
  await wait('panelState().tabs.some(tab=>tab.label.includes("summary.md")) && panelState().body.includes("Original saved output")', 'original native output file opened');
  await capture('suggested-02-original-file');
  await click('[aria-label="Close summary.md tab"]'); await reopen();
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 3', 'outputs after file close');
  const image = original.find((row: string) => row.endsWith('.png')); if (!image) throw new Error('Generated output missing.');
  await click('.dock-suggested-list button', image);
  await wait('document.querySelector(".image-preview-dialog[open] img")?.naturalWidth === 1', 'actual recorded generated PNG bytes');
  await capture('suggested-03-recorded-image'); await key('ESCAPE');
  await wait('document.querySelector(".image-preview-dialog[open]") === null', 'image keyboard close');
  await click('.dock-suggested-list button', 'report result');
  await wait('document.querySelector(".mcp-app-frame") !== null', 'retained MCP output panel');
  const frame = () => window.webContents.mainFrame.frames.find(frame => frame.url === 'about:srcdoc');
  for (let i = 0; i < 200; i++) { if (frame() && await frame()!.executeJavaScript('document.querySelector("#retained")?.textContent.includes("3,5,8")', true)) break; if (i === 199) throw new Error('Saved native MCP result not delivered.'); await new Promise(resolve => setTimeout(resolve, 50)); }
  await capture('suggested-04-retained-app');
  await click('[aria-label="Close report result tab"]'); await reopen();
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 3', 'outputs restored after app close');
  flow.setConnected(false);
  await wait('[...document.querySelectorAll(".dock-suggested-list button")].every(button=>button.disabled)', 'offline saved rows disabled');
  await capture('suggested-05-offline-history');
  flow.setConnected(true); await wait('[...document.querySelectorAll(".dock-suggested-list button")].every(button=>!button.disabled)', 'original owner reconnect');
  rmSync(join(fixture, 'project', 'summary.md'));
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 2', 'missing saved output removed');
  await capture('suggested-06-missing-output');
  const oldDocument = await evaluate('panelState().documentId'); window.webContents.reload();
  await wait(`typeof panelState === 'function' && panelState().documentId !== ${JSON.stringify(oldDocument)} && document.querySelectorAll('.dock-suggested-list button').length === 2`, 'actual App reload restores saved outputs');
  await capture('suggested-07-reloaded');
  await flow.prompt('many-outputs');
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 26', 'twenty-four actual native saved files');
  window.setContentSize(1000, 600);
  await wait('innerHeight === 600', 'explicit short viewport');
  await evaluate('document.querySelector(".dock-suggested-list button").focus()');
  await key('TAB');
  await wait('document.activeElement.textContent.includes("output-01.md")', 'natural next output keyboard focus');
  flow.inputs.push({ type: 'chromium-key-sequence', key: 'ENTER', events: ['keyDown', 'char-CR', 'keyUp'] });
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'ENTER' });
  window.webContents.sendInputEvent({ type: 'char', keyCode: '\r' });
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'ENTER' });
  await wait('panelState().tabs.some(tab=>tab.label.includes("output-01.md")) && panelState().body.includes("Saved output 1")', 'keyboard opens original output');
  await capture('suggested-08-keyboard-file');
  await click('[aria-label="Close output-01.md tab"]'); await reopen();
  await wait('document.querySelectorAll(".dock-suggested-list button").length === 26', 'long Suggested list retained');
  const point = await evaluate('(()=>{const r=document.querySelector(".dock-empty-panel-actions").getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()');
  flow.inputs.push({ type: 'chromium-wheel', ...point, deltaY: -600 });
  window.webContents.sendInputEvent({ type: 'mouseWheel', x: Math.round(point.x), y: Math.round(point.y), deltaX: 0, deltaY: -600 });
  await wait('document.querySelector(".dock-empty-panel-header.has-scroll-shadow") !== null', 'measured sticky header and wheel scroll shadow');
  await capture('suggested-09-sticky-short');
  window.setContentSize(1250, 950);
  await flow.prompt('website-only');
  const website = JSON.parse(readFileSync(join(fixture, 'website.json'), 'utf8')).url;
  await wait(`${rows}.includes(${JSON.stringify(website)})`, 'saved declared local website');
  const top = await evaluate('(()=>{const r=document.querySelector(".dock-empty-panel-actions").getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()');
  flow.inputs.push({ type: 'chromium-wheel', ...top, deltaY: 3000 });
  window.webContents.sendInputEvent({ type: 'mouseWheel', x: Math.round(top.x), y: Math.round(top.y), deltaX: 0, deltaY: 3000 });
  await wait('document.querySelector(".dock-empty-panel-actions").scrollTop === 0', 'return to newest saved output above sticky header');
  await click('.dock-suggested-list button', website);
  await wait('panelState().saved.state.dock.tabs.some(tab=>tab.browserTarget) && document.querySelector(".browser-viewport img")?.naturalWidth > 0', 'native original website frame');
  await capture('suggested-10-native-website');
  const browserCalls = flow.calls as { method: string; args: any[] }[];
  if (browserCalls.filter(call => call.method === 'createBrowserTab').length !== 1) throw new Error('Suggested website dispatched more than one browser creation.');

  const calls = readFileSync(join(fixture, 'mcp-requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line));
  if (calls.filter(value => value.method === 'tools/call' && value.params.name === 'report').length !== 1) throw new Error('Historical MCP output was replayed.');
  if (readFileSync(join(fixture, 'image-provider.jsonl'), 'utf8').trim().split('\n').length !== 1) throw new Error('Image provider was replayed.');
}
