import { afterEach, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { LocalEnvironmentStore, parseLocalEnvironment, scriptForPlatform, serializeLocalEnvironment, type LocalEnvironmentConfig } from "./index";

const roots: string[] = [];
function root() { const path = mkdtempSync(join(tmpdir(), "agent-desktop-environments-")); roots.push(path); return path; }
afterEach(() => { for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true }); });

const environment: LocalEnvironmentConfig = {
  version: 2, name: "Full stack",
  setup: { script: "npm install", darwin: { script: "brew bundle\nnpm install" }, linux: { script: "" } },
  cleanup: { script: "docker compose down", win32: { script: "docker compose down --remove-orphans" } },
  actions: [
    { name: "Dev", icon: "run", command: "npm run dev", platform: "darwin" },
    { name: "Test", icon: null, command: "npm test" },
  ],
};

test("native format roundtrips and platform scripts use non-empty override then base", () => {
  const raw = serializeLocalEnvironment(environment), parsed = parseLocalEnvironment(raw);
  expect(raw).toContain("# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY\nversion = 2\nname = \"Full stack\"");
  expect(raw).toContain("[setup.darwin]\nscript = '''\nbrew bundle\nnpm install'''");
  expect(raw).not.toContain("[setup.linux]");
  expect(parsed).toEqual({ ...environment, setup: { script: "npm install", darwin: { script: "brew bundle\nnpm install" } } });
  expect(scriptForPlatform(parsed.setup, "darwin")).toBe("brew bundle\nnpm install");
  expect(scriptForPlatform(parsed.setup, "linux")).toBe("npm install");
  expect(scriptForPlatform(parsed.cleanup, "win32")).toBe("docker compose down --remove-orphans");
  expect(scriptForPlatform(undefined, "darwin")).toBeNull();

  const syntacticNewline = parseLocalEnvironment("name = \"\\nLiteral leading newline\"\n[setup]\nscript = '''\n\nIntentional leading newline'''\n");
  expect(syntacticNewline.name).toBe("\nLiteral leading newline");
  expect(syntacticNewline.setup.script).toBe("\nIntentional leading newline");
  const delimiterText = "nested = '''\nkeep a \\\\ path and a \"\"\" token";
  expect(parseLocalEnvironment(serializeLocalEnvironment({ version: 1, name: "Delimiter", setup: { script: delimiterText } })).setup.script).toBe(delimiterText);
  const controlsAndDelimiters = "both ''' and \"\"\"\ncontrol: \u0001\ttail\"\"";
  expect(parseLocalEnvironment(serializeLocalEnvironment({ version: 1, name: "Fallback", setup: { script: controlsAndDelimiters } })).setup.script).toBe(controlsAndDelimiters);
  expect(parseLocalEnvironment('name="Quotes"\n[setup]\nscript="""one""""\n[cleanup]\nscript="""two"""""\n')).toMatchObject({
    setup: { script: 'one"' }, cleanup: { script: 'two""' },
  });
});

test("parser follows native defaults and icon fallback while rejecting invalid platforms", () => {
  const parsed = parseLocalEnvironment('name="Local"\n[setup]\nscript=""\n[[actions]]\nname="Open"\nicon="unknown"\ncommand="code ."\n');
  expect(parsed).toEqual({ version: 1, name: "Local", setup: { script: "" }, actions: [{ name: "Open", icon: null, command: "code ." }] });
  expect(() => parseLocalEnvironment('version=0\nname="x"\n[setup]\nscript="x"')).toThrow("at least 1");
  expect(() => parseLocalEnvironment('name="x"\n[setup]\nscript="x"\n[[actions]]\nname="x"\ncommand="x"\nplatform="freebsd"')).toThrow("platform is invalid");
});

test("catalog keeps valid entries beside individual parse and symlink errors", async () => {
  const project = root(), directory = join(project, ".agent-desktop", "environments"); mkdirSync(directory, { recursive: true });
  writeFileSync(join(directory, "good.toml"), serializeLocalEnvironment(environment));
  writeFileSync(join(directory, "broken.toml"), "name = [");
  const outside = join(root(), "outside.toml"); writeFileSync(outside, serializeLocalEnvironment(environment)); symlinkSync(outside, join(directory, "escape.toml"));
  const items = await new LocalEnvironmentStore(project).catalog();
  expect(items.map(item => [item.type, item.configPath.split("/").at(-1)])).toEqual([["error", "broken.toml"], ["error", "escape.toml"], ["environment", "good.toml"]]);
  expect(items.find(item => item.configPath.endsWith("good.toml"))).toMatchObject({ type: "environment", revision: expect.stringMatching(/^[a-f0-9]{64}$/), environment: { name: "Full stack" } });
  expect(items.find(item => item.configPath.endsWith("escape.toml"))).toMatchObject({ type: "error", error: expect.stringContaining("symlink") });
});

test("revisioned writes preserve the attempted and current versions on stale save", async () => {
  const project = root(), store = new LocalEnvironmentStore(project), sentinel = join(project, "must-not-run"), raw = serializeLocalEnvironment({
    ...environment,
    setup: { ...environment.setup, script: `touch ${sentinel}` },
    actions: [{ name: "Also inert", icon: "run", command: `touch ${sentinel}` }],
  });
  const created = await store.save({ expectedRevision: null, raw });
  if (created.type !== "saved") throw new Error("expected create");
  expect(created.configPath).toBe(join(project, ".agent-desktop", "environments", "full-stack.toml"));
  chmodSync(created.configPath, 0o640);
  const editedRaw = serializeLocalEnvironment({ ...environment, name: "Edited" });
  const edited = await store.save({ configPath: created.configPath, expectedRevision: created.revision, raw: editedRaw });
  if (edited.type !== "saved") throw new Error("expected edit");
  const staleRaw = serializeLocalEnvironment({ ...environment, name: "Stale draft" });
  const stale = await store.save({ configPath: created.configPath, expectedRevision: created.revision, raw: staleRaw });
  expect(stale).toMatchObject({ type: "conflict", expectedRevision: created.revision, current: { type: "environment", revision: edited.revision, environment: { name: "Edited" } }, attempted: { raw: staleRaw, environment: { name: "Stale draft" } } });
  expect(readFileSync(created.configPath, "utf8")).toBe(editedRaw);
  expect(statSync(created.configPath).mode & 0o777).toBe(0o640);
  expect(existsSync(sentinel)).toBeFalse();
  const reopened = new LocalEnvironmentStore(project);
  expect(await reopened.catalog()).toMatchObject([{ type: "environment", revision: edited.revision, environment: { name: "Edited" } }]);
});

test("separate store instances serialize compare-and-save for one project", async () => {
  const project = root(), initial = await new LocalEnvironmentStore(project).save({ expectedRevision: null, raw: serializeLocalEnvironment(environment) });
  if (initial.type !== "saved") throw new Error("expected create");
  const alias = join(root(), "project-alias"); symlinkSync(project, alias, "dir");
  const [first, second] = await Promise.all([
    new LocalEnvironmentStore(project).save({ configPath: initial.configPath, expectedRevision: initial.revision, raw: serializeLocalEnvironment({ ...environment, name: "First" }) }),
    new LocalEnvironmentStore(alias).save({ configPath: join(alias, ".agent-desktop", "environments", "full-stack.toml"), expectedRevision: initial.revision, raw: serializeLocalEnvironment({ ...environment, name: "Second" }) }),
  ]);
  expect([first.type, second.type].sort()).toEqual(["conflict", "saved"]);
  const conflict = first.type === "conflict" ? first : second;
  const saved = first.type === "saved" ? first : second;
  if (conflict.type !== "conflict" || saved.type !== "saved") throw new Error("expected one saved result and one conflict");
  expect(conflict).toMatchObject({ current: { type: "environment", revision: saved.revision }, attempted: { environment: { name: expect.stringMatching(/First|Second/) } } });
});

test("matching parse-error revision can be repaired without overwriting an intervening external edit", async () => {
  const project = root(), directory = join(project, ".agent-desktop", "environments"), path = join(directory, "repair.toml");
  mkdirSync(directory, { recursive: true }); writeFileSync(path, "name = [");
  const store = new LocalEnvironmentStore(project), [broken] = await store.catalog();
  if (broken?.type !== "error" || !broken.revision) throw new Error("expected revisioned parse error");
  const repairedRaw = serializeLocalEnvironment({ ...environment, name: "Repaired" });
  const repaired = await store.save({ configPath: path, expectedRevision: broken.revision, raw: repairedRaw });
  expect(repaired).toMatchObject({ type: "saved", environment: { name: "Repaired" } });

  if (repaired.type !== "saved") throw new Error("expected repair");
  const externalRaw = serializeLocalEnvironment({ ...environment, name: "External" });
  const originalRead = Reflect.get(store, "readEntry").bind(store); let reads = 0;
  Reflect.set(store, "readEntry", async (configPath: string) => {
    if (++reads === 2) writeFileSync(path, externalRaw);
    return originalRead(configPath);
  });
  const save = store.save({ configPath: path, expectedRevision: repaired.revision, raw: serializeLocalEnvironment({ ...environment, name: "Editor" }) });
  const conflicted = await save;
  expect(conflicted).toMatchObject({ type: "conflict", current: { type: "environment", environment: { name: "External" } }, attempted: { environment: { name: "Editor" } } });
  expect(readFileSync(path, "utf8")).toBe(externalRaw);

  if (conflicted.type !== "conflict" || conflicted.current?.type !== "environment") throw new Error("expected external conflict");
  reads = 0;
  Reflect.set(store, "readEntry", async (configPath: string) => {
    if (++reads === 2) throw new Error("interrupted before replace");
    return originalRead(configPath);
  });
  await expect(store.save({ configPath: path, expectedRevision: conflicted.current.revision, raw: repairedRaw })).rejects.toThrow("interrupted");
  expect(readdirSync(directory).filter(name => name.endsWith(".tmp"))).toEqual([]);
  expect(readFileSync(path, "utf8")).toBe(externalRaw);
});

test("owned config paths reject traversal, file symlinks and storage-directory symlinks", async () => {
  const project = root(), store = new LocalEnvironmentStore(project), raw = serializeLocalEnvironment(environment), outsideRoot = root();
  await expect(store.save({ configPath: join(outsideRoot, "outside.toml"), expectedRevision: null, raw })).rejects.toThrow("outside");
  const created = await store.save({ expectedRevision: null, raw }); if (created.type !== "saved") throw new Error("expected create");
  const outside = join(outsideRoot, "target.toml"); writeFileSync(outside, "untouched");
  const link = join(project, ".agent-desktop", "environments", "linked.toml"); symlinkSync(outside, link);
  const linked = await store.save({ configPath: link, expectedRevision: null, raw });
  expect(linked).toMatchObject({ type: "conflict", current: { type: "error", error: expect.stringContaining("symlink") } });
  expect(readFileSync(outside, "utf8")).toBe("untouched");

  const symlinkedProject = root(), external = root(); mkdirSync(join(symlinkedProject, ".agent-desktop"));
  symlinkSync(external, join(symlinkedProject, ".agent-desktop", "environments"));
  await expect(new LocalEnvironmentStore(symlinkedProject).catalog()).rejects.toThrow("owned directory");
});

test("catalog rejects a named pipe without blocking", async () => {
  if (process.platform === "win32") return;
  const project = root(), directory = join(project, ".agent-desktop", "environments"), fifo = join(directory, "blocked.toml");
  mkdirSync(directory, { recursive: true });
  const made = spawnSync("mkfifo", [fifo]); if (made.status !== 0) throw new Error(made.stderr.toString());
  const started = performance.now(), items = await new LocalEnvironmentStore(project).catalog();
  expect(performance.now() - started).toBeLessThan(1_000);
  expect(items).toMatchObject([{ type: "error", configPath: fifo, error: expect.stringContaining("regular file") }]);
});

test("catalog bounds oversized config reads", async () => {
  const project = root(), directory = join(project, ".agent-desktop", "environments"), path = join(directory, "oversized.toml");
  mkdirSync(directory, { recursive: true }); writeFileSync(path, Buffer.alloc(1024 * 1024 + 1, 65));
  expect(await new LocalEnvironmentStore(project).catalog()).toMatchObject([
    { type: "error", configPath: path, error: expect.stringContaining("exceeds 1 MiB") },
  ]);
});

test("existing native configs are discovered, edited in place and revision conflicts retain both versions", async () => {
  const project = root(), nativeDirectory = join(project, ".codex", "environments");
  mkdirSync(nativeDirectory, { recursive: true });
  const nativePath = join(nativeDirectory, "environment.toml"), raw = serializeLocalEnvironment(environment);
  writeFileSync(nativePath, raw); chmodSync(nativePath, 0o640);
  const store = new LocalEnvironmentStore(project);
  const authored = await store.save({ expectedRevision: null, raw });
  if (authored.type !== "saved") throw new Error("expected saved app config");
  const entries = await store.catalog();
  expect(entries.map(item => item.configPath)).toEqual([nativePath, authored.configPath]);
  const native = await store.read(nativePath);
  const alias = join(root(), "alias"); symlinkSync(project, alias);
  const aliasStore = new LocalEnvironmentStore(alias);
  expect((await aliasStore.read(nativePath)).raw).toBe(raw);
  expect((await store.read(join(alias, ".codex", "environments", "environment.toml"))).raw).toBe(raw);
  const editedRaw = serializeLocalEnvironment({ ...environment, name: "Native edited" });
  const edited = await store.save({ configPath: join(alias, ".codex", "environments", "environment.toml"), expectedRevision: native.revision, raw: editedRaw });
  expect(edited).toMatchObject({ type: "saved", configPath: nativePath });
  expect(readFileSync(nativePath, "utf8")).toBe(editedRaw);
  expect(statSync(nativePath).mode & 0o777).toBe(0o640);
  expect(readFileSync(authored.configPath, "utf8")).toBe(raw);
  const conflict = await new LocalEnvironmentStore(project).save({ configPath: nativePath, expectedRevision: native.revision, raw });
  expect(conflict).toMatchObject({ type: "conflict", current: { environment: { name: "Native edited" } }, attempted: { raw } });
  expect(readdirSync(nativeDirectory)).toEqual(["environment.toml"]);
});

test("native config ownership rejects nested paths and symlink directories without widening project scope", async () => {
  const project = root(), outside = root(), directory = join(project, ".codex", "environments");
  mkdirSync(directory, { recursive: true });
  const raw = serializeLocalEnvironment(environment), outsidePath = join(outside, "external.toml");
  writeFileSync(outsidePath, raw);
  const store = new LocalEnvironmentStore(project);
  symlinkSync(outsidePath, join(directory, "linked.toml"));
  await expect(store.read(join(directory, "linked.toml"))).rejects.toThrow("symlink");
  await expect(store.save({ configPath: join(directory, "nested", "file.toml"), expectedRevision: null, raw })).rejects.toThrow("outside");
  await expect(store.read(outsidePath)).rejects.toThrow("outside");
  rmSync(directory, { recursive: true }); symlinkSync(outside, directory);
  await expect(store.catalog()).rejects.toThrow("owned directory");
  await expect(store.save({ configPath: join(directory, "external.toml"), expectedRevision: null, raw })).rejects.toThrow("owned directory");
  expect(readFileSync(outsidePath, "utf8")).toBe(raw);
});
