import { afterEach, expect, test } from "bun:test";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readGitActionContext } from "./git-action-context";
import { defaultGitPushRunner, pushPreparedDestination, type GitPushRunner } from "./git-push";
import { WorkspaceService } from "./service";
const roots:string[]=[]; afterEach(async()=>{await Promise.all(roots.splice(0).map(path=>rm(path,{recursive:true,force:true})))});
function git(cwd:string,...args:string[]){const r=Bun.spawnSync(["git","-C",cwd,...args],{stdout:"pipe",stderr:"pipe"});if(!r.success)throw new Error(new TextDecoder().decode(r.stderr));return new TextDecoder().decode(r.stdout).trim()}
function refs(cwd:string){return new TextDecoder().decode(Bun.spawnSync(["git","-C",cwd,"show-ref"],{stdout:"pipe",stderr:"pipe"}).stdout).trim()}
async function fixture(timeout=30_000){const root=await mkdtemp(join(tmpdir(),"push-test-"));roots.push(root);const cwd=join(root,"repo"),remote=join(root,"remote.git");await mkdir(cwd);git(cwd,"init","-q","--initial-branch=main");git(cwd,"config","user.name","Push Test");git(cwd,"config","user.email","push@example.invalid");await writeFile(join(cwd,"a"),"a\n");git(cwd,"add","a");git(cwd,"commit","-qm","one");git(root,"init","-q","--bare",remote);git(cwd,"remote","add","origin",remote);return{root,cwd,remote,service:new WorkspaceService(cwd,{gitTimeoutMs:timeout})}}
async function input(f:Awaited<ReturnType<typeof fixture>>){const context=await readGitActionContext(f.service);if(context.push.state!=="available")throw new Error("unavailable");return{contextRevision:context.revision,sourceCommit:context.status.head!,branch:context.status.branch!,destination:context.push.destination}}
test("first exact-SHA push configures upstream and next push preserves it",async()=>{const f=await fixture();let result=await f.service.pushPreparedDestination(await input(f));expect(result).toMatchObject({outcome:"succeeded",applied:{remote:"confirmed",upstream:"configured"}});expect(git(f.remote,"rev-parse","refs/heads/main")).toBe(result.sourceCommit);expect(git(f.cwd,"config","branch.main.remote")).toBe("origin");await writeFile(join(f.cwd,"b"),"b\n");git(f.cwd,"add","b");git(f.cwd,"commit","-qm","two");result=await f.service.pushPreparedDestination(await input(f));expect(result).toMatchObject({outcome:"succeeded",applied:{remote:"confirmed",upstream:"not-requested"}})});
test("stale HEAD or destination rejects before dispatch",async()=>{const f=await fixture(),reviewed=await input(f);await writeFile(join(f.cwd,"b"),"b");git(f.cwd,"add","b");git(f.cwd,"commit","-qm","later");await expect(f.service.pushPreparedDestination(reviewed)).rejects.toMatchObject({code:"GIT_CHANGED"});expect(refs(f.remote)).toBe("")});
test("remote rejection is a definite failed result",async()=>{const f=await fixture();await writeFile(join(f.remote,"hooks","pre-receive"),"#!/bin/sh\nexit 1\n");await chmod(join(f.remote,"hooks","pre-receive"),0o755);const result=await f.service.pushPreparedDestination(await input(f));expect(result).toMatchObject({outcome:"failed",applied:{remote:"rejected",upstream:"not-requested"},errorCode:"PUSH_REJECTED"});expect(refs(f.remote)).toBe("")});
test("upstream config failure preserves the confirmed remote partial",async()=>{const f=await fixture();await writeFile(join(f.cwd,".git","config.lock"),"foreign");const result=await f.service.pushPreparedDestination(await input(f));expect(result).toMatchObject({outcome:"failed",applied:{remote:"confirmed",upstream:"failed"}});expect(git(f.remote,"rev-parse","refs/heads/main")).toBe(result.sourceCommit);expect(await readFile(join(f.cwd,".git","config.lock"),"utf8")).toBe("foreign")});
test("configured followTags and recurseSubmodules cannot expand the one-SHA push",async()=>{const f=await fixture();git(f.cwd,"tag","-a","extra","-m","extra");git(f.cwd,"config","push.followTags","true");git(f.cwd,"config","push.recurseSubmodules","on-demand");let pushArgs:string[]=[];const runner:GitPushRunner=async(cwd,args,timeout)=>{if(args[0]==="push")pushArgs=args;return defaultGitPushRunner(cwd,args,timeout)};const result=await pushPreparedDestination(f.service,await input(f),30_000,runner);expect(result.outcome).toBe("succeeded");expect(pushArgs).toContain("--no-follow-tags");expect(pushArgs).toContain("--recurse-submodules=no");expect(refs(f.remote)).not.toContain("refs/tags/extra")});
test("a timed-out applied push is unknown and is not retried",async()=>{const f=await fixture(250);await writeFile(join(f.remote,"hooks","post-receive"),"#!/bin/sh\nsleep 2\n");await chmod(join(f.remote,"hooks","post-receive"),0o755);const reviewed=await input(f);const result=await f.service.pushPreparedDestination(reviewed);expect(result).toMatchObject({outcome:"unknown",applied:{remote:"unknown"},errorCode:"GIT_TIMEOUT"});expect(git(f.remote,"rev-parse","refs/heads/main")).toBe(reviewed.sourceCommit);expect(refs(f.remote).match(/refs\/heads\/main/g)?.length).toBe(1)},10_000);
test("mirror configuration is rejected before the single-ref push",async()=>{const f=await fixture();git(f.cwd,"config","remote.origin.mirror","true");const context=await readGitActionContext(f.service);expect(context.push.state).toBe("unavailable");if(context.push.state!=="unavailable")throw new Error("expected unavailable");await expect(f.service.pushPreparedDestination({contextRevision:context.revision,sourceCommit:context.status.head!,branch:context.status.branch!,destination:context.push.alternatives[0]!})).rejects.toMatchObject({code:"PUSH_CONFIG_UNSUPPORTED"});expect(refs(f.remote)).toBe("")});
test("operational mirror-config failure closes before push dispatch",async()=>{const f=await fixture(),reviewed=await input(f);let pushes=0;const runner:GitPushRunner=async(cwd,args,timeout)=>{if(args[0]==="config"&&args[1]==="--get")return{ok:false,stdout:Buffer.alloc(0),stderr:Buffer.from("failure"),timeout:false,overflow:false,exitCode:128};if(args[0]==="push")pushes++;return defaultGitPushRunner(cwd,args,timeout)};await expect(pushPreparedDestination(f.service,reviewed,30_000,runner)).rejects.toMatchObject({code:"GIT_FAILED"});expect(pushes).toBe(0);expect(refs(f.remote)).toBe("")});
test("timeout outranks rejection text and post-push inspection failure retains the remote receipt",async()=>{const timed=await fixture(),timedInput=await input(timed);const timeoutRunner:GitPushRunner=async(cwd,args,timeout)=>args[0]==="push"?{ok:false,stdout:Buffer.from("!\tHEAD:refs/heads/main\t[rejected]\n"),stderr:Buffer.alloc(0),timeout:true,overflow:false,exitCode:null}:defaultGitPushRunner(cwd,args,timeout);expect(await pushPreparedDestination(timed.service,timedInput,30_000,timeoutRunner)).toMatchObject({outcome:"unknown",applied:{remote:"unknown"},errorCode:"GIT_TIMEOUT"});
const inspected=await fixture(),inspectedInput=await input(inspected);let pushed=false;const inspectRunner:GitPushRunner=async(cwd,args,timeout)=>{if(args[0]==="rev-parse"&&pushed)return{ok:false,stdout:Buffer.alloc(0),stderr:Buffer.from("failure"),timeout:false,overflow:false,exitCode:128};const result=await defaultGitPushRunner(cwd,args,timeout);if(args[0]==="push"&&result.ok)pushed=true;return result};expect(await pushPreparedDestination(inspected.service,inspectedInput,30_000,inspectRunner)).toMatchObject({outcome:"unknown",applied:{remote:"confirmed",upstream:"unknown"},errorCode:"UPSTREAM_UNCONFIRMED"});expect(git(inspected.remote,"rev-parse","refs/heads/main")).toBe(inspectedInput.sourceCommit)});
