import{app,BrowserWindow,Menu,ipcMain}from'electron';import{readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';
import{requestVersionedCommand}from'../../../apps/desktop/src/main/command-endpoints';
import{requestHost}from'../../../apps/desktop/src/main/host-transport';import{defaultWindowView}from'../../../apps/desktop/src/window-state';
const[output,fixture]=process.argv.slice(2)as[string,string],connection=JSON.parse(readFileSync(join(fixture,'connection.json'),'utf8'));
app.setPath('userData',join(fixture,'electron'));const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function run(){
await app.whenReady();Menu.setApplicationMenu(null);const window=new BrowserWindow({show:false,width:1280,height:900,webPreferences:{preload:join(output,'preload.cjs'),sandbox:true,contextIsolation:true,backgroundThrottling:false}});
const calls:unknown[]=[],inputs:unknown[]=[],captures:unknown[]=[],errors:unknown[]=[];let saved={state:{...defaultWindowView(),route:{hostId:connection.hostId,sessionId:null},settingsOpen:true,settingsPage:'omp'}};
window.webContents.on('console-message',(_event,level,message)=>{if(level>=3)errors.push(message);});
const http=(path:string,body?:unknown)=>requestHost(connection,path,body);
ipcMain.on('lsp-app-save',(event,value)=>{saved={state:value};event.returnValue={};});
ipcMain.handle('lsp-app-call',async(_event,method:string,args:any[]=[])=>{calls.push({method,args});switch(method){
case'bootstrap':return saved;case'getState':return http('/v1/state');case'getHosts':return http('/v1/peers');case'getPreferences':return http('/v1/preferences');case'getTheme':return http('/v1/theme');
case'getSettingsCatalog':return http('/v1/settings/catalog');case'getSettings':return http('/v1/settings/read',{target:args[0]});
case'getComposerCatalog':return http('/v1/models/composer',{target:args[0],refresh:args[1]});case'getComposerActions':return http('/v1/composer/actions',{target:args[0],refresh:args[1]});
case'getLspConfiguration':return http('/v1/integrations/lsp/read',{target:args[0]});case'mutateLspConfiguration':return http('/v1/integrations/lsp/mutate',{target:args[0],mutation:args[1]});
case'workspaceQuery':return http('/v1/workspace/query',{target:args[0],query:args[1]});case'command':return requestVersionedCommand(http,args[0]);default:throw Error('Unsupported fixture bridge method '+method);}});
const socket=new WebSocket(connection.origin.replace('http:','ws:')+'/v1/events?after=0',['agent-desktop',connection.token]);socket.addEventListener('message',event=>{if(!window.isDestroyed())window.webContents.send('lsp-app-event',{...JSON.parse(String(event.data)),hostId:connection.hostId});});
const js=(source:string)=>window.webContents.executeJavaScript(source,true);const wait=async(source:string)=>{for(let i=0;i<400;i++){if(await js(source))return;await delay(50);}throw Error('Timed out '+source);};
const click=async(selector:string,text?:string,field?:string)=>{const p=await js(`(()=>{const root=${field?`[...document.querySelectorAll('.lsp-field')].find(e=>e.querySelector('label')?.textContent===${JSON.stringify(field)})`:'document'};const e=[...root.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.getClientRects().length&&!e.disabled&&${text===undefined?'true':`e.textContent.trim()===${JSON.stringify(text)}`});if(!e)throw Error('Missing click target');e.scrollIntoView({block:'center'});const b=e.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};})()`);for(const type of ['mouseMove','mouseDown','mouseUp']as const)window.webContents.sendInputEvent({type,...p,...(type==='mouseMove'?{}:{button:'left' as const,clickCount:1})});inputs.push({kind:'synthetic-electron-pointer',selector,text});await delay(100);};
const change=async(selector:string,value:string)=>{await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(e.tagName==='SELECT'?HTMLSelectElement.prototype:e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}));})()`);inputs.push({kind:'synthetic-dom-input',selector,value});await delay(100);};
const capture=async(name:string)=>{await delay(200);const geometry=await js(`({viewport:[innerWidth,innerHeight],overflow:document.documentElement.scrollWidth>innerWidth,dialog:(()=>{const d=document.querySelector('.lsp-dialog');if(!d)return null;const b=d.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,scrollWidth:d.scrollWidth,clientWidth:d.clientWidth};})(),text:document.querySelector('.lsp-settings')?.innerText})`);writeFileSync(join(output,name+'.png'),(await window.webContents.capturePage()).toPNG());captures.push({name,geometry});if(geometry.overflow||geometry.dialog&&geometry.dialog.scrollWidth>geometry.dialog.clientWidth)throw Error('Horizontal overflow');};
let failure:string|undefined;
try{
await window.loadFile(join(output,'web/index.html'));await wait("!!document.querySelector('[aria-label=\"Native settings category\"]')");await change('[aria-label="Native settings category"]','lsp-servers');await wait("document.querySelector('.lsp-list')?.textContent.includes('fixture')");await capture('wide-list');
await click('.lsp-server summary span strong','fixture');await click('.lsp-server[open] .secondary-button','Edit override');await wait("!!document.querySelector('.lsp-dialog[open]')");
await click('.lsp-dialog label','Override disabled');await click('.lsp-dialog .native-checkbox input');await capture('wide-edit');await click('.lsp-dialog .primary-button','Save for new sessions');await wait("!document.querySelector('.lsp-dialog[open]')");await wait("document.querySelector('.lsp-server[open]')?.textContent.includes('Disabled')");
await click('.lsp-server[open] .secondary-button','Edit override');await wait("!!document.querySelector('.lsp-dialog[open]')");window.setContentSize(720,720);await capture('narrow-edit');await click('.lsp-dialog .native-checkbox input');await click('.lsp-dialog .primary-button','Save for new sessions');await wait("!document.querySelector('.lsp-dialog[open]')");
await click('.lsp-server[open] .secondary-button','Edit override');await wait("!!document.querySelector('.lsp-dialog[open]')");await click('.lsp-dialog .danger-link','Remove override…');await click('.lsp-dialog .primary-button','Remove override');await wait("!document.querySelector('.lsp-list')?.textContent.includes('fixture')");
await click('.lsp-actions .secondary-button','Add server');await wait("!!document.querySelector('.lsp-dialog[open]')");await change('.lsp-name input','added-fixture');
await click('.lsp-dialog label','Override command');await change('[aria-label="Command"]','/usr/bin/false');
await click('.lsp-dialog label','Override file types');await click('button','Add item','Override file types');await change('[aria-label="File types item 1"]','.fixture');
await click('.lsp-dialog label','Override project root markers');await click('button','Add item','Override project root markers');await change('[aria-label="Project root markers item 1"]','.');
await click('.lsp-dialog .primary-button','Save for new sessions');await wait("!document.querySelector('.lsp-dialog[open]')&&document.querySelector('.lsp-list')?.textContent.includes('added-fixture')");
await click('.lsp-sources>summary');await click('.lsp-sources .secondary-button','Edit idle timeout');await wait("!!document.querySelector('.lsp-dialog[open]')");await click('.lsp-dialog .lsp-override','Override idle timeout');await change('[aria-label="Idle timeout (ms)"]','1250');await click('.lsp-dialog .primary-button','Save for new sessions');await wait("!document.querySelector('.lsp-dialog[open]')&&document.querySelector('.lsp-actions')?.textContent.includes('1250 ms')");
await capture('narrow-saved');
if(errors.length)throw Error('Renderer errors: '+JSON.stringify(errors));
}catch(error){failure=String(error);writeFileSync(join(output,'failure.png'),(await window.webContents.capturePage()).toPNG());writeFileSync(join(output,'failure-dom.txt'),await js('document.body.innerText'));}
finally{writeFileSync(join(output,'result.json'),JSON.stringify({passed:!failure,failure,calls,inputs,captures,errors,classification:'Production App plus authenticated actual discovery worker; disposable configuration; synthetic input; no provider or physical acceptance'},null,2));socket.close();window.destroy();app.exit(failure?1:0);}

}
void run().catch(error=>{writeFileSync(join(output,"startup-error.txt"),String(error));app.exit(1);});
