import{createHash}from'node:crypto';import{mkdir,mkdtemp,readFile,readdir,realpath,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve,relative}from'node:path';import{build}from'vite';
const root=resolve(import.meta.dir,'../../..'),output=resolve(process.argv[2]??'.data/lsp-settings/app-001');await mkdir(output,{recursive:true});if((await readdir(output)).length)throw Error('Evidence directory must be empty');
const sources=['patches/@oh-my-pi%2Fpi-coding-agent@18.1.10.patch','node_modules/@oh-my-pi/pi-coding-agent/src/lsp/config.ts','node_modules/@oh-my-pi/pi-coding-agent/src/discovery/helpers.ts','apps/desktop/src/renderer/App.tsx','apps/desktop/src/renderer/NativeSettings.tsx','apps/desktop/src/renderer/LspSettings.tsx','apps/desktop/src/renderer/lsp-settings.css','apps/host/src/integrations/lsp.ts','apps/host/src/integrations-http.ts','apps/host/src/omp-workers/entry.ts','apps/host/src/omp-workers/runtime.ts','apps/host/src/omp-workers/protocol.ts','packages/shared/src/native-lsp.ts','packages/shared/src/protocol.ts',...(await readdir(import.meta.dir)).map(name=>'scripts/acceptance/lsp-settings-app/'+name)];
const hashes=async()=>Object.fromEntries(await Promise.all(sources.map(async name=>[name,createHash('sha256').update(await readFile(join(root,name))).digest('hex')])));const before=await hashes();await writeFile(join(output,'source-before.json'),JSON.stringify(before,null,2));
const fixture=await realpath(await mkdtemp(join(tmpdir(),'agent-lsp-app-'))),host=Bun.spawn([process.execPath,join(import.meta.dir,'host.ts'),fixture],{cwd:root,env:{HOME:fixture,PI_CODING_AGENT_DIR:join(fixture,'agent'),PATH:'/usr/bin:/bin',TMPDIR:tmpdir(),PI_DISABLE_DOTENV:'1',TERM:'dumb',AGENT_DESKTOP_NATIVE_TERMINALS:'0'},stdin:'pipe',stdout:Bun.file(join(output,'host.stdout')),stderr:Bun.file(join(output,'host.stderr'))});let electron:Bun.Subprocess|undefined;
try{
for(let i=0;!(await Bun.file(join(fixture,'connection.json')).exists());i++){if(i>400||host.exitCode!==null)throw Error('Host start failed');await Bun.sleep(100);}
const connection=JSON.parse(await readFile(join(fixture,'connection.json'),'utf8'));const command=async(command:unknown)=>{const r=await fetch(connection.origin+'/v1/commands',{method:'POST',headers:{Authorization:`Bearer ${connection.token}`,'content-type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),command})});const body=await r.json()as any;if(!r.ok||!body.ok)throw Error(JSON.stringify(body));return body.value;};
const project=await command({type:'project.add',path:join(fixture,'project'),name:'LSP fixture'});await command({type:'draft.put',draft:{id:'new-conversation',text:'',projectId:project.id,model:null},expectedRevision:0});
await writeFile(join(output,'index.html'),`<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="${relative(output,join(import.meta.dir,'browser.tsx'))}"></script>`);await build({configFile:join(root,'apps/desktop/vite.config.ts'),root:output,logLevel:'warn',build:{outDir:join(output,'web'),emptyOutDir:true}});
const compiled=await Bun.build({entrypoints:[join(import.meta.dir,'main.ts')],outdir:output,naming:'main.mjs',target:'node',format:'esm',external:['electron']});if(!compiled.success)throw Error(compiled.logs.join('\n'));
await writeFile(join(output,'preload.cjs'),`const{contextBridge,ipcRenderer}=require('electron');contextBridge.exposeInMainWorld('lspSettingsAppFixture',{save:value=>ipcRenderer.sendSync('lsp-app-save',value),call:(method,args)=>ipcRenderer.invoke('lsp-app-call',method,args),subscribe:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('lsp-app-event',handler);return()=>ipcRenderer.removeListener('lsp-app-event',handler);}});`);
electron=Bun.spawn([join(root,'node_modules/electron/dist',(await readFile(join(root,'node_modules/electron/path.txt'),'utf8')).trim()),join(output,'main.mjs'),output,fixture],{cwd:root,stdout:Bun.file(join(output,'electron.stdout')),stderr:Bun.file(join(output,'electron.stderr'))});const timer=setTimeout(()=>electron!.kill('SIGTERM'),90000);const code=await electron.exited;clearTimeout(timer);if(code)throw Error(`App fixture failed (${code})`);
}finally{if(electron?.exitCode===null){electron.kill('SIGTERM');await electron.exited;}if(host.exitCode===null){host.stdin.write('stop\n');host.stdin.end();}const timer=setTimeout(()=>host.kill('SIGKILL'),15000),code=await host.exited;clearTimeout(timer);const after=await hashes();await writeFile(join(output,'source-after.json'),JSON.stringify(after,null,2));await writeFile(join(output,'cleanup.json'),JSON.stringify({hostExit:code,electronExit:electron?.exitCode,fixture},null,2));if(JSON.stringify(before)!==JSON.stringify(after))throw Error('Source changed during acceptance');if(code===0&&electron?.exitCode===0)await rm(fixture,{recursive:true,force:true});}
