import {app,BrowserWindow,ipcMain,Menu,Notification} from "electron";
import {readFileSync,writeFileSync} from "node:fs";import{join}from"node:path";
import {requestHost} from "../../../apps/desktop/src/main/host-transport";
import {requestVersionedCommand} from "../../../apps/desktop/src/main/command-endpoints";
import {WindowStateStore} from "../../../apps/desktop/src/main/window-state";import{defaultWindowView}from"../../../apps/desktop/src/window-state";
import {NotificationDelivery} from "../../../apps/desktop/src/main/notification-delivery";import{NotificationNavigation}from"../../../apps/desktop/src/main/notification-navigation";
const [output,fixture]=process.argv.slice(2) as [string,string],connection=JSON.parse(readFileSync(join(fixture,"connection.json"),"utf8")),context=JSON.parse(readFileSync(join(fixture,"context.json"),"utf8")),control=JSON.parse(readFileSync(join(fixture,"control.json"),"utf8"));
app.setPath("userData",join(fixture,"electron"));const store=new WindowStateStore(join(fixture,"window"),"notification-flow");const initialSave=store.saveView({...defaultWindowView(),route:{hostId:connection.hostId,sessionId:context.initial},expandedProjects:[`${connection.hostId}:${context.projectId}`],collapsedSidebarSections:[]});if(initialSave.error)throw Error(initialSave.error);
const navigation=new NotificationNavigation();let shown:Notification|undefined;const checkpoints:string[]=[],errors:string[]=[],diagnostics:string[]=[],calls:any[]=[];
const progress=(value:string)=>writeFileSync(join(output,"progress.log"),`${Date.now()} ${value}\n`,{flag:"a"});
const delivery=new NotificationDelivery(join(fixture,"notification-ledger.json"),{preferences:()=>({turnComplete:true,completionPolicy:"always",approvalRequired:true,questionRequired:true,sound:false}),focused:()=>false,supported:()=>Notification.isSupported(),show:(notice,options)=>{const value=new Notification({title:notice.title,body:notice.body,silent:options.silent});value.on("click",options.onClick);value.on("close",options.onClosed);value.on("failed",(_event,error)=>{diagnostics.push(String(error));options.onFailed()});value.show();shown=value;return{close:()=>value.close()};},navigate:target=>navigation.open(target),statusChanged:()=>{}});
const http=(path:string,body?:unknown)=>requestHost(connection,path,body);const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function run(){await app.whenReady();Menu.setApplicationMenu(null);const window=new BrowserWindow({show:true,width:1250,height:900,minWidth:720,minHeight:480,webPreferences:{preload:join(output,"preload.cjs"),sandbox:true,contextIsolation:true,backgroundThrottling:false}});window.webContents.on("console-message",(_event,level,message)=>{if(level>=2)diagnostics.push(message)});window.webContents.on("did-fail-load",(_event,code,description)=>errors.push(`load ${code}: ${description}`));
const emit=(channel:string,value:any)=>{if(!window.isDestroyed())window.webContents.send(channel,value)};
ipcMain.on("notification-window-bootstrap",event=>{event.returnValue=store.bootstrap()});ipcMain.on("notification-window-save",(event,value)=>{event.returnValue=store.saveView(value)});
ipcMain.handle("notification-fixture",async(event,method:string,args:any[]=[])=>{calls.push({method,args});switch(method){case"bootstrap":return store.bootstrap();case"save":return store.saveView(args[0]);case"ack":return navigation.acknowledge(event.sender.id,args[0]);case"ready":navigation.ready({id:event.sender.id,send:value=>emit("notification-navigate",value)});return{};case"unready":navigation.unready(event.sender.id);return{};case"getState":return http("/v1/state");case"getHosts":return http("/v1/peers");case"getPreferences":return http("/v1/preferences");case"getTheme":return http("/v1/theme");case"getMessages":return http(`/v1/sessions/${encodeURIComponent(args[0])}/messages`);case"getInteractions":return http(`/v1/sessions/${encodeURIComponent(args[0])}/interactions`);case"getComposerCatalog":return http("/v1/models/composer",{target:args[0],refresh:args[1]});case"getSessionControls":return http(`/v1/sessions/${encodeURIComponent(args[0])}/controls`);case"workspaceQuery":return http("/v1/workspace/query",{target:args[0],query:args[1]});case"command":return requestVersionedCommand(http,args[0]);default:throw Error("Unsupported "+method)}});
const evaluate=(script:string)=>window.webContents.executeJavaScript(script,true),wait=async(script:string,label:string)=>{for(let i=0;i<300;i++){if(await evaluate(script))return;await delay(40)}throw Error("Timed out: "+label)};
let passed=false;try{progress("load-start");await window.loadFile(join(output,"web/index.html"));progress("load-done");window.focus();window.webContents.focus();await wait("document.body.innerText.includes('Initial conversation')","App host load");progress("app-ready");navigation.ready({id:window.webContents.id,send:value=>emit("notification-navigate",value)});delivery.begin(connection.hostId);delivery.snapshot(connection.hostId,0,[],true);
const completed=await fetch(control.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({method:"complete"})}).then(response=>response.json()) as any;for(const event of completed.events){emit("host-event",{...event,hostId:connection.hostId});if(event.type==="notification")delivery.event(connection.hostId,event.sequence,event.notification)}
await wait(`document.querySelector('[data-session-id="${context.target}"]')?.closest('.organized-session')?.classList.contains('unread')===true`,"native activity unread");progress("unread");if(!shown)throw Error("Electron did not create the completion notification");shown.emit("click");await wait(`Boolean(document.querySelector('[data-session-id="${context.target}"]')?.closest('.selected'))`,"exact conversation selected");progress("selected");for(let i=0;i<300&&store.bootstrap().state?.route.sessionId!==context.target;i++)await delay(40);if(store.bootstrap().state?.route.sessionId!==context.target)throw Error("Exact route was not durably saved");if(navigation.current())throw Error("Saved route did not acknowledge notification");checkpoints.push("Synthetic native completion produced unread attention and Electron click selected and saved the exact owner conversation");
progress("reload-start");await Promise.race([window.reload(),delay(15000).then(()=>{throw Error("Reload did not finish")})]);progress("reload-done");await wait(`Boolean(document.querySelector('[data-session-id="${context.target}"]')?.closest('.selected'))`,"saved route reopened");checkpoints.push("Window reload restored the saved notification conversation");
const foreign={hostId:"offline-owner",sessionId:"offline-session"};navigation.open(foreign,window.webContents.id);for(let i=0;i<300&&(store.bootstrap().state?.route.hostId!==foreign.hostId||navigation.current());i++)await delay(40);if(store.bootstrap().state?.route.hostId!==foreign.hostId||store.bootstrap().state?.route.sessionId!==foreign.sessionId)throw Error("Offline exact owner was not durably saved");if(navigation.current())throw Error("Offline exact route was not acknowledged");checkpoints.push("Unavailable owner remained exact and never fell back to the local conversation");passed=true;}catch(cause){errors.push(String(cause));progress("error "+String(cause));}finally{progress("finish");const renderer=await evaluate("notificationFixtureState()").catch(()=>null);writeFileSync(join(output,"result.json"),JSON.stringify({passed,checkpoints,errors,diagnostics,calls,renderer,notificationSupported:Notification.isSupported(),scope:"Actual production App, WindowStateStore, notification delivery/navigation owners, disposable authenticated host state and Electron Notification. The completion and click are synthetic fixture inputs; this is not proof of a physical Notification Center click or provider execution."},null,2));writeFileSync(join(output,"final.png"),(await window.webContents.capturePage()).toPNG());delivery.dispose();window.destroy();app.exit(passed?0:1)}}
void run().catch(error=>{console.error(error);app.exit(1)});
