import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.argv[2]!, nativePackage = process.env.BROWSER_CONTROL_NATIVE_PACKAGE; assert(nativePackage);
await Promise.all(["agent", "project", "sessions"].map(name => mkdir(path.join(root, name), { recursive: true, mode: 0o700 })));
const agentDir = path.join(root, "agent"), cwd = path.join(root, "project"); await writeFile(path.join(agentDir, "config.yml"), "browser:\n  enabled: true\n  headless: true\n  cmux: false\n  relay: false\nretry:\n  enabled: false\n");
const mod = await import(pathToFileURL(path.join(nativePackage, "src/index.ts")).href), supervisor = await import(pathToFileURL(path.join(nativePackage, "src/tools/browser/tab-supervisor.ts")).href);
const { AgentRegistry, createAgentSession, discoverAuthStorage, ModelRegistry, SessionManager, Settings } = mod as typeof import("@oh-my-pi/pi-coding-agent");
type Context = { documentId: string; width: number; height: number; scrollX: number; scrollY: number; navigation: { entryId: number; canGoBack: boolean; canGoForward: boolean } };
type Action = { type: string; [key: string]: unknown };
const { captureTabViewportForOwner, getTab, listTabsForOwner, performTabHumanActionForOwner, releaseAllTabs } = supervisor as typeof import("@oh-my-pi/pi-coding-agent/tools/browser/tab-supervisor") & {
  captureTabViewportForOwner(owner: string, target: { name: string; targetId: string }): Promise<{ data: Uint8Array; context: Context }>;
  performTabHumanActionForOwner(owner: string, target: { name: string; targetId: string }, context: Context, action: Action): Promise<{ context: Context; url: string; title: string }>;
};
let session: Awaited<ReturnType<typeof createAgentSession>>["session"] | undefined, server: ReturnType<typeof Bun.serve> | undefined, failure: unknown; const checks: string[] = [];
const rejected = async (promise: Promise<unknown>, pattern?: RegExp) => { try { await promise; assert.fail("Expected BrowserActionRejected"); } catch (error) { assert.equal((error as Error).name, "BrowserActionRejected"); if (pattern) assert.match((error as Error).message, pattern); } };
try {
  const nativeFetch = globalThis.fetch; globalThis.fetch = Object.assign((input: Parameters<typeof fetch>[0], init?: RequestInit) => { const url = new URL(input instanceof Request ? input.url : String(input)); assert(["127.0.0.1", "localhost", "[::1]"].includes(url.hostname)); return nativeFetch(input, init); }, { preconnect: () => {} }) as typeof fetch;
  let firstRequests = 0, secondRequests = 0, linkedRequests = 0, slowEntered = false; const slowGate = Promise.withResolvers<void>(); server = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) { const pathname = new URL(request.url).pathname; if (pathname === "/slow") { slowEntered = true; await slowGate.promise; } if (pathname === "/first") firstRequests++; if (pathname === "/second") secondRequests++; if (pathname === "/linked") linkedRequests++; const title = pathname === "/second" ? "Second" : pathname === "/linked" ? "Linked" : "First"; return new Response(`<!doctype html><meta charset=utf-8><title>${title}</title><style>html,body{margin:0;width:100%;height:1800px}button{position:absolute;left:20px;top:20px;width:120px;height:50px}input{position:absolute;left:20px;top:100px;width:300px;height:40px}a{position:absolute;left:20px;top:170px;width:180px;height:50px}</style><button>click</button><input>${pathname === "/first" ? '<a href="/linked">open linked page</a>' : ""}<script>globalThis.controlState={clicks:0,enters:0};document.addEventListener('pointerdown',()=>sessionStorage.setItem('pointerDowns',String(Number(sessionStorage.getItem('pointerDowns')||0)+1)),true);document.addEventListener('click',()=>sessionStorage.setItem('pageClicks',String(Number(sessionStorage.getItem('pageClicks')||0)+1)),true);document.querySelector('button').onclick=()=>controlState.clicks++;document.querySelector('input').onkeydown=e=>{if(e.key==='Enter')controlState.enters++}</script>`, { headers: { "Content-Type": "text/html" } }); } });
  const firstUrl = `http://127.0.0.1:${server.port}/first`, secondUrl = `http://127.0.0.1:${server.port}/second`, linkedUrl = `http://127.0.0.1:${server.port}/linked`, auth = await discoverAuthStorage(agentDir), settings = await Settings.loadReadOnly({ cwd, agentDir }), manager = SessionManager.create(cwd, path.join(root, "sessions")); await manager.ensureOnDisk();
  const created = await createAgentSession({ cwd, agentDir, settings, authStorage: auth, modelRegistry: new ModelRegistry(auth, path.join(agentDir, "models.yml"), { settings }), sessionManager: manager, agentRegistry: new AgentRegistry(), toolNames: ["eval"], disableExtensionDiscovery: true, enableMCP: false, hasUI: false }); session = created.session;
  const evalTool = session.getToolByName("eval"); assert(evalTool); const name = "control-proof"; const opened = await evalTool.execute(crypto.randomUUID(), { language: "js", title: "Open control proof", code: `await browser.open({name:${JSON.stringify(name)},url:${JSON.stringify(firstUrl)},viewport:{width:640,height:480,scale:1},timeout:30});`, timeout: 30 }); assert(!opened.isError);
  const owner = manager.getSessionId(), metadata = listTabsForOwner(owner), tab = metadata[0]!; assert.equal(metadata.length, 1); const target = { name, targetId: tab.targetId }, nativeTab = getTab(name); assert(nativeTab?.backend === "worker"); const browserTarget = nativeTab.browser.browser.targets().find(candidate => (candidate as unknown as { _targetId?: string })._targetId === tab.targetId), page = await browserTarget?.page(); assert(page);
  let frame = await captureTabViewportForOwner(owner, target); assert.equal(frame.context.width, 640); assert.equal(frame.context.height, 480); assert(frame.context.documentId); assert.equal(frame.context.navigation.canGoForward, false); const initialDocument = frame.context.documentId, initialEntry = frame.context.navigation.entryId, initialCanGoBack = frame.context.navigation.canGoBack;
  await page.evaluate(() => history.pushState({ proof: true }, "", "#same-document")); const sameDocument = await captureTabViewportForOwner(owner, target); assert.equal(sameDocument.context.documentId, initialDocument); assert.notEqual(sameDocument.context.navigation.entryId, initialEntry); assert.equal(sameDocument.context.navigation.canGoBack, true); await rejected(performTabHumanActionForOwner(owner, target, frame.context, { type: "click", x: 50, y: 50 }), /changed/); let result = await performTabHumanActionForOwner(owner, target, sameDocument.context, { type: "back" }); assert.equal(result.context.navigation.entryId, initialEntry); assert.equal(result.context.navigation.canGoForward, true);
  await rejected(performTabHumanActionForOwner("wrong-owner", target, frame.context, { type: "click", x: 50, y: 50 }), /owner-bound/); await rejected(performTabHumanActionForOwner(owner, target, { ...frame.context, navigation: { ...frame.context.navigation, entryId: -1 } }, { type: "resize", width: 800, height: 600 }), /exact owner/); await rejected(performTabHumanActionForOwner(owner, target, frame.context, { type: "navigate", url: "file:///tmp/no" }), /protocol/);
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "click", x: 50, y: 50 }); assert.equal((await page.evaluate(() => (globalThis as any).controlState.clicks)), 1);
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "click", x: 100, y: 120 }); result = await performTabHumanActionForOwner(owner, target, result.context, { type: "text", text: "typed text" }); assert.equal(await page.$eval("input", element => (element as HTMLInputElement).value), "typed text");
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "key", key: "Enter" }); assert.equal(await page.evaluate(() => (globalThis as any).controlState.enters), 1);
  const beforeResize = result.context, viewportBefore = page.viewport(); assert(viewportBefore); result = await performTabHumanActionForOwner(owner, target, result.context, { type: "resize", width: 800, height: 600 }); assert.equal(result.context.width, 800); assert.equal(result.context.height, 600); assert.equal(result.context.documentId, beforeResize.documentId); assert.equal(result.context.navigation.entryId, beforeResize.navigation.entryId); assert.equal(await page.$eval("input", element => (element as HTMLInputElement).value), "typed text"); assert.deepEqual({ ...page.viewport(), width: viewportBefore.width, height: viewportBefore.height }, viewportBefore); await rejected(performTabHumanActionForOwner(owner, target, beforeResize, { type: "resize", width: 900, height: 700 }), /changed/); assert.equal(page.viewport()?.width, 800); frame = await captureTabViewportForOwner(owner, target); const decodedResize = await new Bun.Image(frame.data).metadata(); assert.equal(decodedResize.width, 800); assert.equal(decodedResize.height, 600); result = await performTabHumanActionForOwner(owner, target, frame.context, { type: "resize", width: 640, height: 480 });
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "click", x: 50, y: 50, clickCount: 2 }); assert.equal(await page.evaluate(() => (globalThis as any).controlState.clicks), 3);
  const beforeLinkDocument = result.context.documentId; result = await performTabHumanActionForOwner(owner, target, result.context, { type: "click", x: 80, y: 190 }); assert.equal(result.url, linkedUrl); assert.equal(result.title, "Linked"); assert.notEqual(result.context.documentId, beforeLinkDocument); assert.equal(linkedRequests, 1); assert.equal(listTabsForOwner(owner)[0]?.targetId, target.targetId); result = await performTabHumanActionForOwner(owner, target, result.context, { type: "back" }); assert.equal(result.url, firstUrl); assert.equal(result.context.navigation.canGoForward, true);
  // Repeated real loader handoffs expose a before/after context-read race that
  // one successful navigation does not rule out. Count browser events, not calls.
  const counters = () => page.evaluate(() => ({ down: Number(sessionStorage.getItem("pointerDowns") || 0), click: Number(sessionStorage.getItem("pageClicks") || 0) }));
  const initialCounters = await counters(), initialLinkedRequests = linkedRequests;
  for (let navigationIndex = 0; navigationIndex < 20; navigationIndex++) {
    frame = await captureTabViewportForOwner(owner, target);
    result = await performTabHumanActionForOwner(owner, target, frame.context, { type: "click", x: 80, y: 190 });
    assert.equal(result.url, linkedUrl); assert.equal(result.title, "Linked");
    assert.notEqual(result.context.documentId, frame.context.documentId);
    assert.deepEqual(await counters(), { down: initialCounters.down + navigationIndex + 1, click: initialCounters.click + navigationIndex + 1 });
    assert.equal(linkedRequests, initialLinkedRequests + navigationIndex + 1);
    assert.equal(listTabsForOwner(owner)[0]?.targetId, target.targetId);
    result = await performTabHumanActionForOwner(owner, target, result.context, { type: "back" });
    assert.equal(result.url, firstUrl);
  }
  checks.push("20 navigation loader transitions return a stable receipt with exactly one pointer-down, click, and destination load per action");
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "wheel", x: 300, y: 300, deltaX: 0, deltaY: 400 }); assert(result.context.scrollY > 0);
  checks.push("click navigation survives the transient CDP loader handoff without repeating input, and exact target ownership remains stable"); checks.push("click, double-click, focused text, key, explicit viewport resize, and coordinate-bound wheel actions mutate the actual page once");

  const beforeNavigate = result.context; await page.evaluate(() => scrollTo(0, 700)); result = await performTabHumanActionForOwner(owner, target, beforeNavigate, { type: "navigate", url: secondUrl }); assert.equal(result.url, secondUrl); assert.notEqual(result.context.documentId, initialDocument);
  const requestsBeforeStale = secondRequests; await rejected(performTabHumanActionForOwner(owner, target, { ...result.context, documentId: initialDocument }, { type: "reload" }), /changed/); assert.equal(secondRequests, requestsBeforeStale);
  const secondDocument = result.context.documentId; result = await performTabHumanActionForOwner(owner, target, result.context, { type: "reload" }); assert.notEqual(result.context.documentId, secondDocument);
  result = await performTabHumanActionForOwner(owner, target, result.context, { type: "back" }); assert.equal(result.url, firstUrl); assert.equal(result.context.navigation.canGoBack, initialCanGoBack); assert.equal(result.context.navigation.canGoForward, true); result = await performTabHumanActionForOwner(owner, target, result.context, { type: "forward" }); assert.equal(result.url, secondUrl); assert(result.context.documentId); assert.equal(result.context.navigation.canGoBack, true); assert.equal(result.context.navigation.canGoForward, false);
  checks.push("CDP history tracks normal and same-document entries; stale history and reload have no effect and back/forward return actual new context");

  frame = await captureTabViewportForOwner(owner, target); const originalScreenshot = page.screenshot.bind(page); (page as any).screenshot = async (options: unknown) => { const bytes = await originalScreenshot(options as any); await page.evaluate(() => scrollTo(0, 200)); return bytes; }; await assert.rejects(captureTabViewportForOwner(owner, target), /changed during capture/); (page as any).screenshot = originalScreenshot; await page.evaluate(() => scrollTo(0, 0)); frame = await captureTabViewportForOwner(owner, target); assert.equal(frame.context.scrollY, 0);
  checks.push("viewport capture returns CDP loader and CSS context and rejects a document viewport change during capture");

  const previewGate = Promise.withResolvers<void>(); let previewEntered = false; (page as any).screenshot = async (options: unknown) => { previewEntered = true; await previewGate.promise; return originalScreenshot(options as any); }; const preview = captureTabViewportForOwner(owner, target); for (let i = 0; i < 100 && !previewEntered; i++) await Bun.sleep(10); assert(previewEntered); const queuedClick = performTabHumanActionForOwner(owner, target, frame.context, { type: "click", x: 50, y: 50 }); await assert.rejects(captureTabViewportForOwner(owner, target), /human action/); previewGate.resolve(); await preview; await queuedClick; (page as any).screenshot = originalScreenshot; assert.equal(await page.evaluate(() => (globalThis as any).controlState.clicks), 1);
  checks.push("a human action reserves the tab, waits for an existing viewer capture, then revalidates and dispatches once");

  const slowUrl = `http://127.0.0.1:${server.port}/slow`, nativeRun = evalTool.execute(crypto.randomUUID(), { language: "js", title: "Native busy proof", code: `await browser.tab(${JSON.stringify(name)}).run(${JSON.stringify(`await page.goto(${JSON.stringify(slowUrl)});`)},{timeout:5});`, timeout: 5 }); for (let i = 0; i < 100 && !slowEntered; i++) await Bun.sleep(10); assert(slowEntered && nativeTab.pending.size > 0); await rejected(performTabHumanActionForOwner(owner, target, frame.context, { type: "resize", width: 700, height: 500 }), /native browser work/); slowGate.resolve(); assert(!(await nativeRun).isError); frame = await captureTabViewportForOwner(owner, target);
  const originalSetViewport = page.setViewport.bind(page), originalViewport = page.viewport.bind(page), gate = Promise.withResolvers<void>(); let delayedResizes = 0; (page as any).setViewport = async (...args: unknown[]) => { await gate.promise; delayedResizes++; return (originalSetViewport as any)(...args); };
  const uncertain = performTabHumanActionForOwner(owner, target, frame.context, { type: "resize", width: 700, height: 500 }); for (let i = 0; i < 100; i++) { const busy = await evalTool.execute(crypto.randomUUID(), { language: "js", title: "Human busy proof", code: `await browser.tab(${JSON.stringify(name)}).run('return 1',{timeout:5});`, timeout: 5 }); if (busy.isError) { assert.match(JSON.stringify(busy), /human browser action/); break; } await Bun.sleep(10); }
  await assert.rejects(uncertain, error => (error as Error).name !== "BrowserActionRejected" && /Timed out/.test((error as Error).message)); await rejected(performTabHumanActionForOwner(owner, target, frame.context, { type: "resize", width: 710, height: 510 }), /busy/); gate.resolve(); for (let i = 0; i < 100 && delayedResizes === 0; i++) await Bun.sleep(20); assert.equal(delayedResizes, 1); (page as any).setViewport = originalSetViewport; await Bun.sleep(50); assert.equal(page.viewport()?.width, 700);
  frame = await captureTabViewportForOwner(owner, target); (page as any).viewport = () => null; await rejected(performTabHumanActionForOwner(owner, target, frame.context, { type: "resize", width: 720, height: 520 }), /unavailable/); (page as any).viewport = originalViewport; assert.equal((await page.evaluate(() => ({ width: innerWidth, height: innerHeight }))).width, 700);
  checks.push("native run and human resize reject each other; timed-out resize retains busy identity, dispatches once, and null-viewport tabs reject before mutation");

  frame = await captureTabViewportForOwner(owner, target); const keyboard = page.keyboard as any, originalPress = keyboard.press.bind(keyboard), originalUp = keyboard.up.bind(keyboard); const released: string[] = []; keyboard.press = async () => { throw new Error("controlled post-dispatch key failure"); }; keyboard.up = async (key: string) => { released.push(key); return originalUp(key); };
  await assert.rejects(performTabHumanActionForOwner(owner, target, frame.context, { type: "key", key: "a", modifiers: ["Control"] }), error => (error as Error).name !== "BrowserActionRejected"); keyboard.press = originalPress; keyboard.up = originalUp; assert.deepEqual(released, ["Control"]);
  checks.push("modifier keys release after partial dispatch failure and the outcome remains uncertain rather than preflight-rejected");
  assert(firstRequests >= 1 && secondRequests >= 2); assert.equal(listTabsForOwner(owner).length, 1); assert.equal(getTab(name), nativeTab);
} catch (error) { failure = error; } finally { await session?.dispose().catch(error => { failure ??= error; }); await releaseAllTabs({ kill: true }).catch(error => { failure ??= error; }); server?.stop(true); await writeFile(path.join(root, "result.json"), JSON.stringify({ passed: failure === undefined, checks, scope: "Copied pinned OMP candidate, disposable native browser, and loopback pages only; no provider or existing profile." }, null, 2)); }
if (failure) throw failure;
