import { expect, test } from 'bun:test';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { inspectSessionOutputs, projectSessionOutputs, recordedGeneratedImage } from './session-outputs';
const user = (id = 'turn') => ({ id, type: 'message', message: { role: 'user', content: [{ type: 'text', text: 'Create the requested outputs.' }] } });
const result = (id: string, toolName: string, details: unknown, isError = false) => ({ id, type: 'message', message: { role: 'toolResult', toolName, toolCallId: id, isError, details, content: [{ type: 'text', text: 'Done.' }] } });
const final = (text = '', id = 'final') => ({ id, type: 'message', message: { role: 'assistant', stopReason: 'stop', content: [{ type: 'text', text }] } });
test('completed outputs use saved successful write paths, not read/failed/unrelated input mentions', () => {
  const entries = [user(), result('read', 'read', { resolvedPath: '/task/input.pdf' }), result('fail', 'write', { resolvedPath: '/task/failed.pdf' }, true),
    result('output', 'write', { resolvedPath: '/task/report.pdf' }), result('scratch', 'write', { resolvedPath: '/task/work/intermediate.pdf' }),
    final('[input](input.pdf) and [report](report.pdf) and `plain.txt`\n```md\n[not output](code.pdf)\n```')];
  expect(projectSessionOutputs(entries, '/task').outputs.map(row => [row.kind, row.entryId, 'path' in row ? row.path : ''])).toEqual([['file', 'output', '/task/report.pdf']]);
  expect(projectSessionOutputs(entries.slice(0, -1), '/task').outputs).toEqual([]);
});
test('newest turn deduplicates saved files and preserves actual original entry', () => {
  const entries = [user('old'), result('old-result', 'write', { resolvedPath: '/task/report.pdf' }), final('', 'old-final'), user('new'), result('new-result', 'write', { resolvedPath: '/task/report.pdf' }), final()];
  expect(projectSessionOutputs(entries, '/task').outputs.map(row => row.entryId)).toEqual(['new-result']);
});
test('retained generated bytes have their own index and do not require a final assistant response', () => {
  const entry = result('image', 'generate_image', { imagePaths: ['/task/output.png'], images: [{ mimeType: 'image/png', data: Buffer.from('saved pixels').toString('base64') }] });
  const outputs = projectSessionOutputs([user(), entry], '/task').outputs;
  expect(outputs).toHaveLength(1); expect(outputs[0]?.kind).toBe('generated-image');
  expect(Buffer.from(recordedGeneratedImage(entry, 0).data).toString()).toBe('saved pixels');
  expect(() => recordedGeneratedImage(result('input', 'read', entry.message.details), 0)).toThrow('unavailable');
  expect(() => recordedGeneratedImage(entry, 1)).toThrow('unavailable');
});
test('retained native MCP execution metadata is projected without replay or current catalogue synthesis', () => {
  const details = { serverName: 'charts', mcpToolName: 'report', mcpToolMeta: { ui: { resourceUri: 'ui://charts/report' } }, rawContent: [{ type: 'text', text: 'Original report' }] };
  const outputs = projectSessionOutputs([user(), result('native', 'xd', { xdev: { mode: 'execute', tool: 'mcp__charts__report', inner: details } }),
    result('help', 'xd', { xdev: { mode: 'read', tool: 'mcp__charts__report', inner: details } }), final()], '/task').outputs;
  expect(outputs.map(row => [row.kind, row.entryId])).toEqual([['mcp', 'native']]);
});
test('original file existence and metadata revisions are checked without directory enumeration', async () => {
  const cwd = await mkdtemp(join(tmpdir(), 'suggested-outputs-'));
  try {
    const path = join(cwd, 'report.pdf'); await writeFile(path, 'first');
    const entries = [user(), result('write', 'write', { resolvedPath: path }), final()];
    const first = await inspectSessionOutputs(entries, cwd, 'epoch'); expect(first.outputs).toHaveLength(1);
    await writeFile(path, 'different bytes and size'); const next = await inspectSessionOutputs(entries, cwd, 'epoch');
    expect(next.outputs[0]?.revision).not.toBe(first.outputs[0]?.revision);
    await rm(path); expect((await inspectSessionOutputs(entries, cwd, 'epoch')).outputs).toEqual([]);
  } finally { await rm(cwd, { recursive: true, force: true }); }
});
test('explicit document outputs exclude code/images/inputs and accept balanced/angle link targets', () => {
  const entries = [user(), result('input', 'read', { resolvedPath: '/task/input.pdf' }), final([
    '`[inline](inline.pdf)` ![image](image.pdf)', '[nested [label]](report(1).pdf)', '[spaced](<report two.pdf> "Report")',
    '[input](input.pdf) [remote](file://foreign/task/foreign.pdf)', '~~~md', '[unclosed](fenced.pdf)',
  ].join('\n'))];
  expect(projectSessionOutputs(entries, '/task').outputs.map(row => 'path' in row && row.path)).toEqual(['/task/report(1).pdf', '/task/report two.pdf']);
});
test('only one canonical declared port URL is a fallback; HTML edits are not a website substitute', () => {
  const urls = (text: string) => projectSessionOutputs([user(), final(text)], '/task').outputs;
  expect(urls('Preview http://localhost:8080 and http://localhost:8080/.')).toMatchObject([{ kind: 'website', url: 'http://localhost:8080/' }]);
  expect(urls('http://localhost:8080/a[b]')).toEqual([]);
  expect(urls('https://example.com and http://localhost:8080/')).toHaveLength(1);
  expect(urls('http://localhost:8080/ http://localhost:8081/')).toEqual([]);
  expect(projectSessionOutputs([user(), result('html', 'write', { resolvedPath: '/task/index.html' }), final()], '/task').outputs).toEqual([]);
});
test('generated items reverse within a turn, upgrade same path, and only selected images are decoded', () => {
  const image = (id: string, path: string, data = Buffer.from('pixels').toString('base64')) => result(id, 'generate_image', { imagePaths: [path], images: [{ data, mimeType: 'image/png' }] });
  const rows = projectSessionOutputs([user(), result('file', 'write', { resolvedPath: '/task/a.png' }), image('a', '/task/a.png'), image('b', '/task/b.png'), final()], '/task');
  expect(rows.outputs.map(row => [row.kind, row.entryId])).toEqual([['generated-image', 'b'], ['generated-image', 'a']]);
  const entries = [user('old'), image('invalid-old', '/task/invalid.png', '!invalid!'), final('', 'old-final'), user('new'),
    ...Array.from({ length: 100 }, (_, i) => result(`write-${i}`, 'write', { resolvedPath: `/task/${i}.pdf` })), final()];
  const bounded = projectSessionOutputs(entries, '/task'); expect(bounded.outputs).toHaveLength(100); expect(bounded.truncated).toBe(true); expect(bounded.warnings).toEqual([]);
});
