import { dapAdapterFields, type DesktopBridge, type NativeDapCatalog, type SettingJson, type WorkspaceTarget } from '@agent-desktop/shared';
import { useEffect, useMemo, useReducer, useRef } from 'react';
import { NativeValueField, nativeSettingSeed } from './NativeSettings';
import { dapObject, dapSettingsOwner, type DapSettingsState } from './dap-settings-state';
import { Icon } from './Icons';
import './dap-settings.css';
export function DapSettings({bridge,hostId,hostName,target,connected,localHostId}:{bridge:DesktopBridge;hostId:string;hostName:string;target?:WorkspaceTarget;connected:boolean;localHostId?:string}) {
  const targetKey=JSON.stringify(target??null),data=useMemo(()=>dapSettingsOwner(bridge,hostId,target),[bridge,hostId,targetKey]);const [,redraw]=useReducer(x=>x+1,0);
  useEffect(()=>data.subscribe(redraw),[data]);
  useEffect(()=>{if(connected){data.connected=true;void data.refresh();}else data.disconnect();return()=>data.disconnect();},[data,connected]);
  useEffect(()=>bridge.subscribe(event=>{if(connected&&(event.hostId??localHostId)===hostId&&event.type==='settings')void data.refresh();}),[bridge,data,connected,hostId,localHostId]);
  const catalog=data.catalog,sourceName=(id:string)=>catalog?.sources.find(source=>source.id===id)?.path??'Native built-in default';
  const override=(name:string,scope:'user'|'project',adding=false)=>{const source=catalog?.sources.find(s=>s.id===catalog.overrideTargets[scope]);if(source)data.edit(source,name,adding);};
  return <section className="dap-settings" aria-label="Debugger adapters">
    <header className="dap-heading"><div><h2>Debugger adapters</h2><p>Native DAP configuration on {hostName}. Saves apply to future launch and attach attempts, including in existing sessions. Running debuggers keep their current configuration.</p></div><button className="icon-button" aria-label="Reload debugger adapters" disabled={!connected||data.saving||data.loading} onClick={()=>void data.refresh()}><Icon name="refresh"/></button></header>
    {data.error&&!data.draft&&<p className="inline-error" role="alert">{data.error}</p>}
    {!catalog?<p role="status">{data.loading?'Loading native adapters…':'Reload to inspect debugger adapters.'}</p>:<>
      <div className="dap-actions"><button className="secondary-button" disabled={!connected||data.saving} onClick={()=>override('','user',true)}>Add debugger adapter</button><span className="native-note">Viewing or saving does not launch an adapter or a debuggee.</span></div>
      {catalog.warnings.length>0&&<details className="dap-warnings"><summary>Configuration warnings · {catalog.warnings.length}</summary>{catalog.warnings.map((warning,i)=><p key={i} className="inline-error">{warning}</p>)}</details>}
      <div className="native-settings-card dap-list">{catalog.adapters.map(adapter=><details className="dap-adapter" key={adapter.name}><summary><span>{adapter.name}<small>{adapter.builtin?'Native built-in':'Configured adapter'}{adapter.configured?' · Local or plugin overrides':''}</small></span><span className="dap-status">{adapter.applicability==='ready'?'Command available':adapter.applicability==='invalid'?'Invalid native definition':'Command unavailable'}</span></summary>
        <dl className="dap-derived"><div><dt>Configured command</dt><dd><code>{String(adapter.effective.command??'Unset')}</code></dd></div><div><dt>Resolved command</dt><dd><code>{String(adapter.resolved?.resolvedCommand??'Not found by native resolver')}</code></dd></div><div><dt>Connection mode</dt><dd>{String(adapter.resolved?.connectMode??adapter.effective.connectMode??'stdio')}</dd></div></dl>
        <details className="dap-effective"><summary>Effective native fields and provenance</summary><dl>{Object.entries(adapter.effective).map(([field,value])=><div key={field}><dt>{field}</dt><dd><code>{JSON.stringify(value)}</code><small>{sourceName(adapter.fieldSources[field]??'builtin')}</small>{(field==='launchDefaults'||field==='attachDefaults')&&Object.entries(adapter.defaultSources[field]).map(([key,id])=><small key={key}>{key}: {sourceName(id)}</small>)}</dd></div>)}</dl>{adapter.resolved&&<p>Native resolved arguments: <code>{JSON.stringify(adapter.resolved.args)}</code></p>}</details>
        {adapter.sources.map(id=>{const source=catalog.sources.find(s=>s.id===id)!;return <div className="dap-source-row" key={id}><span>{source.path}{!source.writable?' · Read only':''}{source.ignoredAdapters.includes(adapter.name)?' · Invalid override ignored by native loader':''}</span><button className="secondary-button" disabled={!connected||!source.writable||!dapObject(source.adapters[adapter.name])||data.saving} onClick={()=>data.edit(source,adapter.name)}>Edit override</button></div>;})}
        <div className="dap-actions"><span>Override in</span><button className="secondary-button" disabled={!connected||data.saving} onClick={()=>override(adapter.name,'user')}>User configuration</button><button className="secondary-button" disabled={!connected||!target||data.saving} onClick={()=>override(adapter.name,'project')}>This project</button></div>
      </details>)}</div>
      <details className="dap-sources"><summary>Configuration sources</summary><p>Highest priority first. Launch and attach defaults merge one key deep. Removing an override reveals lower sources; native DAP has no disabled flag.</p>{catalog.sources.filter(s=>s.exists||Object.values(catalog.overrideTargets).includes(s.id)).map(source=><p className="dap-source-row" key={source.id}>{source.path} · {source.scope}{source.exists?'':' · Not created'}{!source.writable?' · Read only':''}</p>)}</details>
    </>}
    {data.draft&&catalog&&<DapEditor data={data} catalog={catalog} hasProject={!!target}/>}
  </section>;
}
function DapEditor({data,catalog,hasProject}:{data:DapSettingsState;catalog:NativeDapCatalog;hasProject:boolean}){
  const dialog=useRef<HTMLDialogElement>(null),draft=data.draft!,source=catalog.sources.find(s=>s.id===draft.sourceId),adapter=catalog.adapters.find(a=>a.name===draft.name);
  useEffect(()=>{const element=dialog.current!,opener=document.activeElement as HTMLElement|null;element.showModal();return()=>{const focused=document.activeElement;const restore=focused===document.body||focused===element||!!focused&&element.contains(focused);element.close();if(restore&&opener?.isConnected)opener.focus();};},[]);
  const enabled=data.connected&&!data.saving&&!data.stale&&source?.writable;
  const updateField=(key:string,value:SettingJson|undefined)=>{const values={...draft.values};if(value===undefined)delete values[key];else values[key]=value;data.change({...draft,values});};
  const fields=(advanced:boolean)=>Object.entries(dapAdapterFields).filter(([,field])=>!!field.advanced===advanced).map(([key,field])=>{const overridden=Object.hasOwn(draft.values,key),effective=adapter?.effective[key];return <div className="dap-field" key={key}><label className="dap-override"><input type="checkbox" checked={overridden} disabled={data.saving} onChange={event=>updateField(key,event.target.checked?structuredClone(effective??nativeSettingSeed(field.schema)):undefined)}/><span>Override {field.label.toLowerCase()}</span></label>{overridden?<NativeValueField label={field.label} value={draft.values[key]!} schema={field.schema} onChange={value=>updateField(key,value)} disabled={data.saving}/>:<p className="native-note">Current native effective value: {effective===undefined?'Native default / unset':JSON.stringify(effective)}</p>}</div>;});
  return <dialog ref={dialog} className="dap-dialog" aria-labelledby="dap-title" onCancel={event=>{event.preventDefault();data.close();}}><div className="dap-heading"><h2 id="dap-title">{draft.remove?'Remove override?':draft.originalName?`Configure ${draft.name}`:'Add debugger adapter'}</h2><button className="icon-button" aria-label="Close debugger adapter editor" disabled={data.saving} onClick={()=>data.close()}><Icon name="close"/></button></div>
    <p className="dap-path">{source?.path??'Original source no longer available'}</p>{data.error&&<p className="inline-error" role="alert">{data.error}</p>}{!data.connected&&<p role="status">Disconnected. Your draft is preserved.</p>}
    <button className="secondary-button" disabled={!data.connected||data.loading||data.saving} onClick={()=>void data.refresh()}>Reload saved sources</button>
    {data.stale&&<div className="dap-conflict" role="alert"><p>Saved configuration changed. Your edits are preserved. Review the current source before adopting its revision.</p><pre>{JSON.stringify(source?.adapters[draft.name]??{},null,2)}</pre><button className="secondary-button" disabled={data.saving||!source||!data.connected} onClick={()=>data.reviewLatest()}>Keep edits and use reviewed revision</button></div>}
    <form onSubmit={event=>{event.preventDefault();void data.save();}}><fieldset disabled={data.saving}>
      {draft.remove?<p>Remove {draft.name} from this source. A lower configuration or built-in adapter can become effective. This does not disable an adapter or stop a running debugger.</p>:<>
        {!draft.originalName&&<><label className="dap-name">Adapter name<input className="text-field" autoFocus required value={draft.name} onChange={event=>data.change({...draft,name:event.target.value})}/></label><label className="dap-name">Scope<select value={source?.scope} onChange={event=>{const next=catalog.sources.find(s=>s.id===catalog.overrideTargets[event.target.value as 'project'|'user']);if(next){const saved=next.adapters[draft.name];data.change({...draft,sourceId:next.id,original:dapObject(saved)?structuredClone(saved):{}});}}}><option value="user">User configuration</option><option value="project" disabled={!hasProject}>This project</option></select></label></>}
        {fields(false)}<p className="native-note">TCP adapters substitute {'${port}'} in arguments. Socket mode uses the native adapter-specific launch behavior. File types and root markers influence automatic native adapter selection.</p><details className="native-advanced"><summary>Advanced native configuration</summary>{fields(true)}<p className="native-note">Unknown saved fields are preserved. Launch and attach defaults accept native JSON objects and merge one key deep. Resolved commands and arguments are read only.</p></details>
      </>}
      <div className="dap-actions dap-footer"><button className="secondary-button" type="button" onClick={()=>data.close()}>Cancel</button>{!draft.remove&&Object.hasOwn(source?.adapters??{},draft.name)&&<button className="danger-link" type="button" onClick={()=>data.change({...draft,remove:true})}>Remove override…</button>}<button className="primary-button" type="submit" disabled={!enabled||!draft.name.trim()}>{data.saving?'Saving…':draft.remove?'Remove override':'Save adapter'}</button></div>
    </fieldset></form>
  </dialog>;
}
