import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { Icon } from "./Icons";
import { activateDockTab, closeDockTab, hideDock, moveDockTab, otherDock, reorderDockTab, resizeDock, type DockDestination, type DockState, type DockTab, type DockViewport } from "./dock-state";
import "./dock-panel.css";

export interface DockAddAction { id: string; label: string; onSelect(destination: DockDestination): void }
export interface DockPanelProps { destination: DockDestination; state: DockState; tabs: readonly DockTab[]; viewport: DockViewport; renderTab(tab: DockTab, active: boolean): ReactNode; onChange(state: DockState): void; onTabDrop?(tabId: string, from: DockDestination, to: DockDestination, index: number): void; onHide?(): void; onMaximize?(): void; addActions?: readonly DockAddAction[] }
export function DockPanel({ destination, state, tabs, viewport, renderTab, onChange, onTabDrop, onHide, onMaximize, addActions = [] }: DockPanelProps) {
  const region = state[destination], panelId = useId(), strip = useRef<HTMLDivElement>(null), drag = useRef<{ id: string; pointer: number; start: DockState } | undefined>(undefined), resize = useRef<{ pointer: number; start: DockState } | undefined>(undefined); const [, setDragging] = useState<string | undefined>(undefined);
  const ordered = region.tabIds.flatMap(id => { const tab = tabs.find(item => item.id === id); return tab ? [tab] : []; });
  const publish = (next: DockState) => { if (next !== state) onChange(next); };
  const focus = (id: string | undefined) => requestAnimationFrame(() => strip.current?.querySelector<HTMLButtonElement>(`[data-dock-tab-id="${CSS.escape(id ?? "")}"]`)?.focus());
  const select = (id: string) => publish(activateDockTab(state, destination, id));
  const close = (id: string) => { const next = closeDockTab(state, destination, id); publish(next); focus(next[destination].activeTabId); };
  const dropIndex = (root: HTMLElement, id: string, clientX: number) => { const pills = [...root.querySelectorAll<HTMLElement>("[data-dock-tab-id]")].filter(item => item.dataset.dockTabId !== id); const index = pills.findIndex(item => clientX < item.getBoundingClientRect().left + item.getBoundingClientRect().width / 2); return index < 0 ? pills.length : index; };
  const keydown = (event: React.KeyboardEvent<HTMLButtonElement>, index: number, id: string) => { const last = ordered.length - 1; let next: number | undefined; if (event.key === "ArrowRight") next = index === last ? 0 : index + 1; else if (event.key === "ArrowLeft") next = index === 0 ? last : index - 1; else if (event.key === "Home") next = 0; else if (event.key === "End") next = last; else if (event.key === "Delete") { event.preventDefault(); close(id); return; } else if ((event.altKey || event.ctrlKey) && event.key === "ArrowDown") { event.preventDefault(); publish(moveDockTab(state, id, otherDock(destination))); return; } else return; event.preventDefault(); const tab = ordered[next!]; if (tab) { select(tab.id); focus(tab.id); } };
  const startResize = (event: React.PointerEvent<HTMLDivElement>) => { resize.current = { pointer: event.pointerId, start: state }; try { event.currentTarget.setPointerCapture(event.pointerId); } catch { /* Synthetic and canceled pointers still restore through the state model. */ } };
  const moveResize = (event: React.PointerEvent<HTMLDivElement>) => { if (resize.current?.pointer !== event.pointerId) return; const size = destination === "right" ? (viewport.left ?? 0) + viewport.width - event.clientX : (viewport.top ?? 0) + viewport.height - event.clientY; publish(resizeDock(state, destination, size, viewport)); };
  const endResize = (event: React.PointerEvent<HTMLDivElement>) => { if (resize.current?.pointer === event.pointerId) resize.current = undefined; };
  const resizeKey = (event: React.KeyboardEvent<HTMLDivElement>) => { const step = 16, current = destination === "right" ? state.rightWidthRatio * viewport.width : state.bottomHeight; if (event.key === "Escape" && resize.current) { publish(resize.current.start); resize.current = undefined; return; } if (event.key === "Home") publish(resizeDock(state, destination, 0, viewport)); else if (event.key === "End") publish(resizeDock(state, destination, Number.MAX_SAFE_INTEGER, viewport)); else if (["ArrowLeft", "ArrowDown", "ArrowRight", "ArrowUp"].includes(event.key)) { const delta = event.key === "ArrowLeft" || event.key === "ArrowUp" ? -step : step; publish(resizeDock(state, destination, current + delta, viewport)); } else return; event.preventDefault(); };
  useEffect(() => { const cancel = (event: KeyboardEvent) => { if (event.key !== "Escape") return; if (resize.current) { publish(resize.current.start); resize.current = undefined; } if (drag.current) { publish(drag.current.start); drag.current = undefined; setDragging(undefined); } }; addEventListener("keydown", cancel); return () => removeEventListener("keydown", cancel); });
  return <section className={`dock-panel dock-panel-${destination}`} aria-label={`${destination === "right" ? "Side" : "Bottom"} dock`} data-dock-destination={destination} data-open={region.open}>
    <div className="dock-resize" role="separator" aria-orientation={destination === "right" ? "vertical" : "horizontal"} aria-valuemin={160} aria-valuemax={destination === "right" ? viewport.width : viewport.height / 2} aria-valuenow={destination === "right" ? Math.round(state.rightWidthRatio * viewport.width) : Math.round(state.bottomHeight)} tabIndex={0} onPointerDown={startResize} onPointerMove={moveResize} onPointerUp={endResize} onPointerCancel={event => { if (resize.current?.pointer === event.pointerId) { publish(resize.current.start); resize.current = undefined; } }} onKeyDown={resizeKey}/>
    <header className="dock-strip" ref={strip} data-app-shell-tab-strip-controller={destination} role="tablist" aria-label={`${destination} dock tabs`}>
      <div className="dock-tabs">{ordered.map((tab, index) => <div className={`dock-pill ${region.activeTabId === tab.id ? "active" : ""}`} key={tab.id} draggable={false} onPointerDown={event => { drag.current = { id: tab.id, pointer: event.pointerId, start: state }; try { event.currentTarget.setPointerCapture(event.pointerId); } catch {} }} onPointerMove={event => { if (drag.current?.pointer === event.pointerId) setDragging(tab.id); }} onPointerUp={event => { if (drag.current?.pointer === event.pointerId) { const target = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-dock-destination]"); const to = target?.dataset.dockDestination as DockDestination | undefined; if (target && (to === "right" || to === "bottom")) { const at = dropIndex(target, tab.id, event.clientX); if (onTabDrop) onTabDrop(tab.id, destination, to, at); else if (to === destination) publish(reorderDockTab(state, destination, tab.id, at)); } drag.current = undefined; setDragging(undefined); } }} onPointerCancel={event => { if (drag.current?.pointer === event.pointerId) { drag.current = undefined; setDragging(undefined); } }}>
        <button id={`${panelId}-${tab.id}`} data-dock-tab-id={tab.id} role="tab" aria-selected={region.activeTabId === tab.id} aria-controls={`${panelId}-panel-${tab.id}`} tabIndex={region.activeTabId === tab.id ? 0 : -1} onClick={() => select(tab.id)} onKeyDown={event => keydown(event, index, tab.id)} onAuxClick={event => { if (event.button === 1) { event.preventDefault(); close(tab.id); } }}><Icon name={tab.kind === "browser" ? "globe" : tab.kind === "terminal" ? "terminal" : tab.kind === "review" ? "compose" : "folder"}/><span>{tab.title}</span></button><button className="dock-tab-close" data-app-shell-tab-close-button aria-label={`Close ${tab.title} tab`} onPointerDown={event => event.stopPropagation()} onClick={() => close(tab.id)}><Icon name="close"/></button>
      </div>)}</div>
      {addActions.length > 0 && <details className="dock-add" name="workbench-panel-menu"><summary aria-label="Add panel tab" title="Add panel tab"><Icon name="plus"/></summary><div>{addActions.map(action => <button key={action.id} onClick={event => { event.currentTarget.closest("details")?.removeAttribute("open"); action.onSelect(destination); }}>{action.label}</button>)}</div></details>}
      <details className="dock-menu" name="workbench-panel-menu"><summary aria-label="Dock options" title="Dock options"><Icon name="more"/></summary><div>{region.activeTabId && <button onClick={event => { event.currentTarget.closest("details")?.removeAttribute("open"); publish(moveDockTab(state, region.activeTabId!, otherDock(destination))); }}>Move to {otherDock(destination)} dock</button>}{onMaximize && <button onClick={event => { event.currentTarget.closest("details")?.removeAttribute("open"); onMaximize(); }}>Maximize dock</button>}<button onClick={event => { event.currentTarget.closest("details")?.removeAttribute("open"); publish(hideDock(state, destination)); onHide?.(); }}>Hide panel</button></div></details>
    </header>
    <div className="dock-content">{ordered.map(tab => <div key={tab.id} id={`${panelId}-panel-${tab.id}`} role="tabpanel" aria-labelledby={`${panelId}-${tab.id}`} hidden={region.activeTabId !== tab.id} inert={region.activeTabId !== tab.id || undefined}>{renderTab(tab, region.activeTabId === tab.id)}</div>)}</div>
  </section>;
}
