import { useEffect, useMemo, useRef, useSyncExternalStore } from "react";
import { SessionUsageState, usageResetMessage } from "./session-usage-state";
import type { UsageCredit } from "../../../../packages/shared/src/session-usage";
import "./session-usage.css";

const date = (value?: number | string) => value === undefined ? "Unknown" : Number.isNaN(new Date(value).getTime()) ? String(value) : new Date(value).toLocaleString();
function Credit({ credit }: { credit: UsageCredit }) {
  return <><strong>{credit.title ?? "Saved rate-limit reset"}</strong>{credit.description && <p>{credit.description}</p>}<p>{credit.status ?? "Status unknown"}{credit.resetType && ` · ${credit.resetType}`} · Expires {date(credit.expiresAt)}{credit.grantedAt && ` · Granted ${date(credit.grantedAt)}`}</p></>;
}
export function SessionUsagePanel({ hostId, hostName, sessionId, connected, controller: suppliedController, onClose, onSettings }: {
  hostId: string; hostName: string; sessionId: string; connected: boolean; controller?: SessionUsageState; onClose(): void; onSettings(): void;
}) {
  const controller = useMemo(() => suppliedController ?? new SessionUsageState(hostId, sessionId, window.agentDesktop, localStorage), [hostId, sessionId, suppliedController]);
  const view = useSyncExternalStore(controller.subscribe, () => controller.view);
  const dialog = useRef<HTMLDialogElement>(null), close = useRef<HTMLButtonElement>(null);
  useEffect(() => { controller.open(); const previous = document.activeElement as HTMLElement | null; dialog.current?.showModal(); close.current?.focus(); return () => { dialog.current?.close(); controller.close(); previous?.focus(); }; }, [controller]);
  const snapshot = view.value?.snapshot, reset = view.value?.reset;
  // The command chooser follows the native helper order and labels; the menu
  // keeps its ordinary inspection order. Selection still uses the opaque row.
  const commandAccounts = suppliedController ? snapshot?.resetCommandAccounts : undefined;
  const commandOrder = new Map(commandAccounts?.map((account, index) => [account.accountRef, index]));
  const credits = commandAccounts ? [...(snapshot?.credits ?? [])].sort((a, b) =>
    (commandOrder.get(a.accountRef) ?? Infinity) - (commandOrder.get(b.accountRef) ?? Infinity)) : snapshot?.credits ?? [];
  const blocked = !connected || view.busy || !!view.pending || reset?.state === "prepared" || reset?.state === "unknown" || reset?.state === "dispatching";
  return <dialog ref={dialog} className="app-dialog session-usage-dialog" aria-labelledby="session-usage-title" onCancel={event => { event.preventDefault(); onClose(); }} onClick={event => { if (event.target === event.currentTarget) onClose(); }}>
    <header><div><h2 id="session-usage-title">Provider usage</h2><p>{hostName} · Original conversation {sessionId}</p></div><button ref={close} className="secondary-button" onClick={onClose}>Close</button></header>
    <p>Provider limits and saved resets are separate from conversation statistics and context usage. Report refresh can refresh native credentials, caches and account blocks. This panel does not run the native automatic reset policy.</p>
    <div className="usage-actions"><button className="secondary-button" disabled={!connected || view.busy} onClick={() => void controller.refresh("reports")}>Refresh provider reports</button><button className="secondary-button" disabled={!connected || view.busy} onClick={() => void controller.refresh("credits")}>Inspect saved credits</button><button className="secondary-button" disabled={!connected || view.busy} onClick={() => void controller.refresh()}>Inspect original receipt</button></div>
    <p role="status">{!connected ? "Offline — viewing cached information." : view.busy ? "Waiting for the owning native session…" : view.cached ? "Cached information. Use an explicit refresh for newer provider evidence." : "Provider inspection complete. Native timestamps below identify the evidence."}</p>
    {view.error && <p className="inline-error" role="alert">{view.error}</p>}
    {view.pending && <section aria-label="Unconfirmed request"><p>Original request {view.pending.envelope.id}: {view.value?.command?.state ?? view.pending.state}. Reconnecting and opening this panel never resends it.</p>{view.pending.state === "absent" && <button className="secondary-button" disabled={!connected || view.busy} onClick={() => void controller.retryAbsent()}>Retry this exact absent request</button>}</section>}
    {snapshot && <section>{snapshot.model && <p>Selection at inspection: {snapshot.model.provider}/{snapshot.model.id}</p>}<h3>Native automatic reset setting: {snapshot.policy.autoRedeem}</h3><p>Minimum blocked time {snapshot.policy.minBlockedMinutes} minutes · Keep {snapshot.policy.keepCredits} credits · Salvage horizon {snapshot.policy.salvageHorizonHours} hours. Existing native policy can act independently on other stored Codex accounts. Manual confirmation here does not change this setting.</p><button className="secondary-button" disabled={!connected} onClick={onSettings}>Open native settings on {hostName}</button></section>}
    {reset && <section className="usage-reset-receipt" aria-label="Saved-reset confirmation"><h3>One existing saved reset · {hostName}</h3><p>{reset.confirmation.account.email ?? reset.confirmation.account.accountId ?? "Native account"}{reset.confirmation.account.accountId && ` · Account ${reset.confirmation.account.accountId}`}{reset.confirmation.account.orgId && ` · Organization ${reset.confirmation.account.orgId}`}{reset.confirmation.account.projectId && ` · Project ${reset.confirmation.account.projectId}`}</p><Credit credit={reset.confirmation.credit}/>{reset.confirmation.creditReference && <p>Credit reference: {reset.confirmation.creditReference}</p>}<p role="status">{usageResetMessage(reset)}</p><small>Original operation {reset.operationId}</small>{reset.state === "prepared" && <><p>Confirmation expires {date(reset.confirmation.expiresAt)}. Confirm spends this one identified credit for this account. It does not purchase credits or enable future automatic resets.</p><div className="usage-actions"><button className="secondary-button" disabled={!connected || view.busy || !!view.pending} onClick={() => void controller.answer(false)}>Cancel</button><button className="primary-button" disabled={!connected || view.busy || !!view.pending || reset.confirmation.expiresAt <= Date.now()} onClick={() => void controller.answer(true)}>Confirm: spend one saved reset</button></div></>}</section>}
    <section><h3>Provider reports</h3><p>Native reporting may omit unavailable providers and reuse cached reports. Missing limits are unknown.</p>{!snapshot || snapshot.reportStatus === "not-loaded" ? <p>Refresh provider reports to inspect native limits.</p> : snapshot.reportStatus === "unsupported" ? <p>Native usage reporting is unavailable for the configured providers.</p> : !snapshot.reports.length ? <p>The native call returned no reports. This can mean no applicable accounts or unsuccessful provider reads; it does not establish zero usage.</p> : snapshot.reports.map((report, index) => <article key={index}><h4>{report.provider}{report.active && " · Active account at inspection"}</h4><p>{Object.entries(report.identity).map(([key, value]) => `${key}: ${value}`).join(" · ")}</p><p>Fetched {date(report.fetchedAt)}{Date.now() - report.fetchedAt > 300_000 && " · May be stale"}{reset && report.fetchedAt < (reset.dispatchedAt ?? reset.createdAt) && " · Predates this reset operation"}</p>{report.notes.map((note, i) => <p key={i}>{note}</p>)}{report.resetCredits && <div><p>Report snapshot: {report.resetCredits.availableCount} saved resets. Inspect saved credits for live availability.</p>{report.resetCredits.credits.map((credit, i) => <div key={i} className="usage-limit"><Credit credit={credit}/></div>)}</div>}{!report.limits.length && <p>No limit windows were provided.</p>}{report.limits.map((limit, i) => <div key={i} className="usage-limit"><strong>{limit.label}{limit.active && " · Active at inspection"}</strong><p>{Object.entries(limit.scope).map(([key, value]) => `${key}: ${value}`).join(" · ")}</p><p>Used {limit.amount.used ?? "Unknown"} · Limit {limit.amount.limit ?? "Unknown"} · Remaining {limit.amount.remaining ?? "Unknown"} {limit.amount.unit}{limit.amount.usedFraction !== undefined && ` · ${(limit.amount.usedFraction * 100).toFixed(1)}% used`}{limit.amount.remainingFraction !== undefined && ` · ${(limit.amount.remainingFraction * 100).toFixed(1)}% remaining`}{limit.status && ` · ${limit.status}`}</p>{limit.window && <p>{limit.window.label} · {limit.window.resetLabel ?? "Resets"} {date(limit.window.resetsAt)}{limit.window.durationMs !== undefined && ` · Window ${limit.window.durationMs / 60_000} minutes`}</p>}{limit.notes.map((note, j) => <p key={j}>{note}</p>)}</div>)}</article>)}{!!snapshot?.modelSelectors.length && <details><summary>Applicable native models</summary><p>{snapshot.modelSelectors.join(", ")}</p></details>}</section>
    <section><h3>Saved resets · OpenAI Codex</h3><p>Only existing Codex OAuth credits support manual resets. Other providers retain their reports above.</p>{!snapshot?.creditsCheckedAt ? <p>Inspect saved credits to load live account rows.</p> : <><p>Inspected {date(snapshot.creditsCheckedAt)}{reset && snapshot.creditsCheckedAt < (reset.dispatchedAt ?? reset.createdAt) && " · Predates this reset operation"}</p>{!snapshot.credits.length && <p>No stored Codex OAuth accounts are available through this session’s native configuration.</p>}{credits.map(account => <article key={account.accountRef}><h4>{commandAccounts?.find(row => row.accountRef === account.accountRef)?.label ?? account.email ?? account.accountId ?? "Native Codex account"}{account.active && " · Active at inspection"}</h4><p>{account.accountId}{account.orgId && ` · Organization ${account.orgId}`}{account.projectId && ` · Project ${account.projectId}`}</p>{account.unavailable ? <p role="status">{account.unavailable} Available count is unknown.</p> : <p>{account.availableCount ?? "Unknown"} available saved resets</p>}{account.credits.map((credit, index) => <div key={index} className="usage-limit"><Credit credit={credit}/></div>)}<button className="secondary-button" disabled={blocked || !account.canPrepare} onClick={() => void controller.prepare(account.accountRef)}>Spend one saved reset…</button></article>)}</>}</section>
  </dialog>;
}
