import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { TranscriptCodeIcon } from "./TranscriptCodeIcons";
import { TranscriptDiagramPreview } from "./TranscriptDiagramPreview";
import { TranscriptTableIcon } from "./TranscriptTableIcons";
import { useCodeCopy } from "./use-code-copy";
import { useCodeTheme } from "./use-code-theme";
import type { RenderedDiagram } from "./transcript-diagram";

const SVG_LABEL = "Image generated by the assistant", MERMAID_LABEL = "Mermaid diagram";
const LOADING_HEIGHT = 240, GATE_MARGIN = "600px 0px", OVERFLOW_SLACK = 1;
const FALLBACK_FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
/** Model markup is only ever handed to an image context; it is never adopted into this document. */
const imageSource = (svg: string) => `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;

/** Model SVG source, normalized through an inert template and displayed as an image.
 * The ordinary code toolbar wraps this element; the image owns no chrome of its own. */
export function TranscriptSvg({ code }: { code: string }) {
  const src = useMemo(() => {
    if (!code) return undefined;
    if (typeof document === "undefined") return imageSource(code);
    const template = document.createElement("template");
    template.innerHTML = code;
    return template.innerHTML ? imageSource(template.innerHTML) : undefined;
  }, [code]);
  if (!src) return null;
  return <img className="transcript-svg-preview" src={src} alt={SVG_LABEL}/>;
}

function innerWidth(node: HTMLElement): number {
  const style = node.ownerDocument.defaultView?.getComputedStyle(node);
  if (!style) return 0;
  const width = parseFloat(style.width) || 0;
  if (style.boxSizing !== "border-box") return width;
  const inset = ["paddingLeft", "paddingRight", "borderLeftWidth", "borderRightWidth"] as const;
  return width - inset.reduce((total, key) => total + (parseFloat(style[key]) || 0), 0);
}

/** A Mermaid fence rendered off the main document: the sandbox returns a self-contained SVG that
 * this surface shows as an image. An unfinished fence never renders, a failed one falls back to
 * the ordinary code block, and every async completion is fenced against its own source and theme. */
export function TranscriptMermaid({ code, open, allowWideBlocks, fallback }: { code: string; open: boolean; allowWideBlocks: boolean; fallback: ReactNode }) {
  const root = useRef<HTMLDivElement>(null), surface = useRef<HTMLDivElement>(null), expand = useRef<HTMLButtonElement>(null);
  const dark = useCodeTheme().themeType === "dark", renderKey = `${dark ? "dark" : "light"}::${code}`;
  const [visible, setVisible] = useState(false), [expanded, setExpanded] = useState(false), [overflow, setOverflow] = useState(false);
  const [preview, setPreview] = useState<{ key: string; diagram: RenderedDiagram }>(), [failure, setFailure] = useState<string>();
  const fenced = useMemo(() => `\`\`\`mermaid\n${code}\n\`\`\``, [code]);
  const copy = useCodeCopy(fenced);
  const current = preview !== undefined && preview.key === renderKey, failed = !open && failure === renderKey;
  const pending = !current && !failed, diagram = preview?.diagram;
  const src = useMemo(() => diagram && imageSource(diagram.svg), [diagram]);
  // Offscreen diagrams cost nothing until the reader is within a screen of them.
  useEffect(() => {
    if (visible) return;
    const node = root.current;
    if (!node) return;
    if (typeof IntersectionObserver === "undefined") { const timer = setTimeout(() => setVisible(true), 0); return () => clearTimeout(timer); }
    const observer = new IntersectionObserver(entries => { if (entries.some(entry => entry.isIntersecting)) { setVisible(true); observer.disconnect(); } }, { rootMargin: GATE_MARGIN });
    observer.observe(node);
    return () => observer.disconnect();
  }, [visible]);
  // A render belongs to the source and theme that started it; a later one aborts and discards it.
  // The mermaid bundle is imported on demand: a transcript without diagrams must never pay for it.
  useEffect(() => {
    if (!visible || open || typeof window === "undefined") return;
    const node = surface.current ?? root.current, controller = new AbortController();
    const family = node?.ownerDocument.defaultView?.getComputedStyle(node).fontFamily.trim();
    const font = family ? family : FALLBACK_FONT;
    let live = true;
    void (async () => {
      try {
        const { renderMermaidDiagram } = await import("./mermaid-sandbox");
        const rendered = await renderMermaidDiagram(code, dark, font, controller.signal);
        if (!live || controller.signal.aborted) return;
        setPreview({ key: renderKey, diagram: rendered });
        setFailure(previous => previous === renderKey ? undefined : previous);
      } catch {
        if (!live || controller.signal.aborted) return;
        setFailure(renderKey);
      }
    })();
    return () => { live = false; controller.abort(); };
  }, [visible, open, code, dark, renderKey]);
  // An expanded preview never survives the source or theme it was opened from.
  useEffect(() => { setExpanded(false); }, [renderKey]);
  useEffect(() => {
    const node = surface.current, block = root.current;
    if (!node || !block || !current || !diagram) { setOverflow(false); return; }
    const measure = () => {
      const style = getComputedStyle(node);
      const natural = diagram.width + (parseFloat(style.paddingLeft) || 0) + (parseFloat(style.paddingRight) || 0)
        + (parseFloat(style.borderLeftWidth) || 0) + (parseFloat(style.borderRightWidth) || 0);
      const parentWidth = block.parentElement?.getBoundingClientRect().width ?? 0;
      block.style.setProperty("--transcript-diagram-width", allowWideBlocks && parentWidth > 0 && natural > parentWidth ? "var(--transcript-diagram-max)" : `${natural}px`);
      setOverflow(diagram.width > innerWidth(node) + OVERFLOW_SLACK);
    };
    measure();
    if (typeof ResizeObserver === "undefined") return;
    const observer = new ResizeObserver(measure);
    observer.observe(node);
    if (block.parentElement) observer.observe(block.parentElement);
    return () => observer.disconnect();
  }, [current, diagram, allowWideBlocks]);
  if (failed) return <>{fallback}</>;
  const close = () => {
    setExpanded(false);
    requestAnimationFrame(() => {
      const trigger = expand.current;
      if (trigger?.isConnected && trigger.ownerDocument.defaultView?.getComputedStyle(trigger).display !== "none") { trigger.focus({ preventScroll: true }); return; }
      surface.current?.focus({ preventScroll: true });
    });
  };
  const copyLabel = copy.state === "copied" ? "Copied" : copy.state === "failed" ? "Copy failed · retry" : "Copy mermaid";
  return <div ref={root} className={`transcript-markdown-diagram${allowWideBlocks ? " transcript-wide-diagram" : ""}`}
    data-wide-markdown-block={allowWideBlocks ? "true" : undefined} data-wide-markdown-block-kind={allowWideBlocks ? "mermaid" : undefined}
    data-markdown-copy={current ? "code-block" : "exclude"} data-markdown-copy-text={current ? fenced : undefined}>
    {!visible
      ? <pre className="transcript-diagram-placeholder" aria-hidden="true"><code>{code}</code></pre>
      : <div ref={surface} className="transcript-diagram-surface" data-preview={diagram ? "true" : undefined} tabIndex={-1} style={diagram ? undefined : { height: LOADING_HEIGHT }}>
        {pending && <div className="transcript-diagram-loading" role="status" aria-label="Loading Mermaid diagram" aria-hidden={diagram ? true : undefined}/>}
        {src && diagram && <img className="transcript-diagram-image" src={src} alt={MERMAID_LABEL} width={diagram.width} height={diagram.height} style={{ maxWidth: "100%", height: "auto" }} draggable={false}/>}
        <span className="sr-only">Mermaid source code</span><pre className="sr-only">{code}</pre>
      </div>}
        {current && <div className="transcript-diagram-actions" data-markdown-copy="exclude">
          {overflow && <button ref={expand} type="button" aria-label="Expand Mermaid diagram" title="Expand Mermaid diagram" aria-haspopup="dialog" aria-expanded={expanded} onClick={() => setExpanded(true)}><TranscriptTableIcon name="expand"/></button>}
          <button type="button" className="transcript-diagram-copy" aria-label={copyLabel} title={copyLabel} aria-busy={copy.state === "pending"} disabled={copy.state === "pending"} onClick={() => void copy.copy()}><TranscriptCodeIcon name={copy.state === "copied" ? "copied" : "copy"}/></button>
        </div>}
        {current && copy.error && <p className="transcript-diagram-copy-error" role="alert" data-markdown-copy="exclude">{copy.error} <button type="button" onClick={() => void copy.copy()}>Retry</button></p>}
    {expanded && current && diagram && <TranscriptDiagramPreview key={diagram.svg} diagram={diagram} onClose={close}/>}
  </div>;
}
