/** Pinned language display labels; unlisted language names remain literal. */
const labels: Record<string,string> = {
  "arduino": "Arduino",
  "bash": "Bash",
  "c": "C",
  "cpp": "C++",
  "csharp": "C#",
  "css": "CSS",
  "diff": "Diff",
  "go": "Go",
  "graphql": "GraphQL",
  "ini": "INI",
  "java": "Java",
  "javascript": "JavaScript",
  "json": "JSON",
  "kotlin": "Kotlin",
  "less": "Less",
  "lua": "Lua",
  "makefile": "Makefile",
  "markdown": "Markdown",
  "objectivec": "Objective-C",
  "perl": "Perl",
  "php": "PHP",
  "php-template": "PHP template",
  "plaintext": "Plaintext",
  "python": "Python",
  "python-repl": "Python REPL",
  "r": "R",
  "ruby": "Ruby",
  "rust": "Rust",
  "scss": "SCSS",
  "shell": "Shell",
  "sql": "SQL",
  "swift": "Swift",
  "typescript": "TypeScript",
  "vbnet": "Visual Basic .NET",
  "wasm": "WebAssembly",
  "xml": "XML",
  "yaml": "YAML"
};
const aliases: Record<string,string> = {
  "c#": "csharp",
  "c++": "cpp",
  "cs": "csharp",
  "gql": "graphql",
  "html": "xml",
  "js": "javascript",
  "jsx": "javascript",
  "md": "markdown",
  "objc": "objectivec",
  "patch": "diff",
  "py": "python",
  "rb": "ruby",
  "rs": "rust",
  "sh": "bash",
  "text": "plaintext",
  "ts": "typescript",
  "tsx": "typescript",
  "vb": "vbnet",
  "yml": "yaml",
  "zsh": "bash"
};
export function codeLanguageLabel(language:string) { return labels[aliases[language.toLowerCase()] ?? language.toLowerCase()] ?? language; }
