// Real native SessionManager/AgentSession/CommandController, isolated files and
// competing native processes. Only UI callbacks gate the actual cwd operation.
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
const packageRoot=process.env.OWNERSHIP_NATIVE_PACKAGE!,root=process.argv[2]!;
const {createAgentSession,discoverAuthStorage,ModelRegistry,SessionManager,Settings}=await import(path.join(packageRoot,'src/index.ts'));
const {FileSessionStorage}=await import(path.join(packageRoot,'src/session/session-storage.ts'));
const {CommandController}=await import(path.join(packageRoot,'src/modes/controllers/command-controller.ts'));
const {initThemeSync}=await import(path.join(packageRoot,'src/modes/theme/theme.ts'));initThemeSync();
const cwd=path.join(root,'project'),agentDir=path.join(root,'agent');await mkdir(cwd,{recursive:true});
const settings=await Settings.loadReadOnly({cwd,agentDir}),auth=await discoverAuthStorage(agentDir),models=new ModelRegistry(auth,path.join(agentDir,'models.yml'),{settings});
const checks:any[]=[];let sequence=0;
const bounded=<T>(p:Promise<T>)=>Promise.race([p,new Promise<never>((_,reject)=>{const timer=setTimeout(()=>reject(new Error('Move fixture event timeout')),10000);timer.unref();})]);
async function check(name:string,work:()=>Promise<void>){try{await work();checks.push({name,status:'passed'});}catch(error){checks.push({name,status:'failed',error:String(error),stack:error instanceof Error?error.stack:undefined});}await writeFile(path.join(root,'result.json'),JSON.stringify({checks,passed:checks.filter(c=>c.status==='passed').length,failed:checks.filter(c=>c.status==='failed').length,providerCalls:false,packageRoot},null,2));}
async function fresh(storage?:any){const manager=SessionManager.create(cwd,path.join(root,`sessions-${++sequence}`),storage);const {session}=await createAgentSession({cwd,agentDir,settings,authStorage:auth,modelRegistry:models,sessionManager:manager,enableMCP:false,enableIrc:false,enableLsp:false,toolNames:[],preloadedExtensionPaths:[],preloadedCustomToolPaths:[],hasUI:false});manager.appendMessage({role:'user',content:'isolated real native move fixture',timestamp:sequence});await manager.ensureOnDisk();await manager.flush();const target=path.join(root,`target-${sequence}`);await mkdir(target);return{manager,session,target};}
async function probe(file:string){const ready=Promise.withResolvers<any>();const child=Bun.spawn([process.execPath,path.resolve(import.meta.dir,'../actor.ts'),file],{env:process.env,stdout:'pipe',stderr:'pipe',ipc:event=>ready.resolve(event)});try{const event=await bounded(ready.promise);if(event.type==='ready')child.send({type:'close'});await bounded(child.exited);return event;}finally{if(child.exitCode===null){child.kill('SIGKILL');await child.exited;}}}
async function busy(file:string){const event=await probe(file);assert.equal(event.type,'rejected',`competing writer admitted at ${file}`);assert.match(event.message,/ownership is busy|namespace.*busy/i);}
function controller(session:any,manager:any,apply:(next:string)=>Promise<boolean>){const errors:string[]=[];let shutdown=0;const ctx={session,sessionManager:manager,settings,applyCwdChange:apply,showError:(s:string)=>errors.push(s),showWarning:(s:string)=>errors.push(s),shutdown:async()=>{shutdown++;},updateEditorBorderColor(){},reloadTodos:async()=>{},ui:{requestRender(){},requestComponentRender(){}},present(){}};return{controller:new CommandController(ctx as any),errors,get shutdown(){return shutdown;}};}
try{
 await check('actual CommandController move retires source only after successful cwd commit',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!,id=manager.getSessionId();const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();
  const ctx=controller(session,manager,async(next)=>{entered.resolve();await release.promise;process.chdir(next);return true;});const pending=ctx.controller.handleMoveCommand(target);
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!;await busy(source);await busy(destination);assert.notEqual(destination,source);release.resolve();await pending;assert.equal(ctx.errors.length,0);assert.deepEqual(manager.getOwnership().heldFiles,[destination]);assert.equal(manager.getSessionId(),id);assert.equal(process.cwd(),target);}finally{release.resolve();await pending.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('close racing actual controller cwd application retains both leases until rollback settles',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();
  const ctx=controller(session,manager,async(next)=>{if(next===target){entered.resolve();await release.promise;throw new Error('controlled cwd setup refusal');}process.chdir(next);return true;});const pending=ctx.controller.handleMoveCommand(target);let closing:Promise<void>|undefined;
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!;closing=manager.close();await busy(source);await busy(destination);release.resolve();await pending;await closing;assert.equal(manager.getSessionFile(),source);assert.equal(manager.getCwd(),cwd);assert.equal(process.cwd(),cwd);}finally{release.resolve();await pending.catch(()=>{});await closing?.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('nested child writer blocks parent move before any transcript/artifact relocation',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;const artifact=source.slice(0,-6);const child=SessionManager.create(cwd,path.join(artifact,'children'));await child.ensureOnDisk();child.appendCustomEntry('before-parent-move',{});await child.flush();const childFile=child.getSessionFile()!,before=await readFile(childFile),parentBefore=await readFile(source);const ctx=controller(session,manager,async(next)=>{process.chdir(next);return true;});
  try{await ctx.controller.handleMoveCommand(target);assert.equal(manager.getSessionFile(),source,'parent moved while a nested child owned the source namespace');assert(ctx.errors.some(e=>/busy/i.test(e)));assert.deepEqual(await readFile(source),parentBefore);assert.deepEqual(await readFile(childFile),before);child.appendCustomEntry('after-busy-parent-move',{});await child.flush();assert((await readFile(childFile,'utf8')).includes('after-busy-parent-move'));}finally{process.chdir(root);await child.close().catch(()=>{});await session.dispose().catch(()=>{});}
 });
 await check('actual controller rollback preserves concurrent completed appends, title, native draft and ordinary artifacts',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;
  const artifactId=await manager.saveArtifact('native artifact 雪 λ','read');await manager.saveDraft('native unsent draft 雪');
  const artifactName=path.basename((await manager.getArtifactPath(artifactId))!);
  const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),rollbackEntered=Promise.withResolvers<void>(),rollbackRelease=Promise.withResolvers<void>();
  const ctx=controller(session,manager,async(next)=>{if(next===target){entered.resolve();await release.promise;return false;}process.chdir(next);rollbackEntered.resolve();await rollbackRelease.promise;return true;});const pending=ctx.controller.handleMoveCommand(target);
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!;assert.equal(await readFile(path.join(destination.slice(0,-6),artifactName),'utf8'),'native artifact 雪 λ');manager.appendCustomEntry('during-forward-cwd',{});await manager.setSessionName('concurrent native title','user');await manager.flush();release.resolve();await bounded(rollbackEntered.promise);await busy(source);await busy(destination);manager.appendCustomEntry('during-rollback-cwd',{});await manager.flush();rollbackRelease.resolve();await pending;
   assert.equal(manager.getSessionFile(),source);assert.equal(manager.getSessionName(),'concurrent native title');assert.equal(await manager.consumeDraft(),'native unsent draft 雪');assert.equal(await readFile(path.join(source.slice(0,-6),artifactName),'utf8'),'native artifact 雪 λ');const entries=(await readFile(source,'utf8')).trim().split('\n').map(JSON.parse);for(const kind of ['during-forward-cwd','during-rollback-cwd'])assert.equal(entries.filter((e:any)=>e.customType===kind).length,1);assert.deepEqual(manager.getOwnership().heldFiles,[source]);assert.equal(process.cwd(),cwd);
  }finally{release.resolve();rollbackRelease.resolve();await pending.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('uncertain controller rollback seals persistence and retains both file and namespace owners',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;let destination:string|undefined;
  const ctx=controller(session,manager,async(next)=>{if(next===target){destination=manager.getSessionFile();throw new Error('controlled target cwd refusal');}throw new Error('controlled source cwd restoration refusal');});
  try{await ctx.controller.handleMoveCommand(target);assert.equal(ctx.shutdown,1);assert.equal(manager.getOwnership().sealed,true);assert(destination);await busy(source);await busy(destination);await busy(path.join(source.slice(0,-6),'late-child.jsonl'));const before=await readFile(source);manager.appendCustomEntry('late-after-uncertain-move',{});await assert.rejects(manager.close(),/indeterminate/i);assert.deepEqual(await readFile(source),before);await busy(source);await busy(destination);}finally{process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('native new/open child admission cannot recreate either artifact namespace during the outer move',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;await manager.saveArtifact('artifact before admission race','bash');
  const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();const ctx=controller(session,manager,async(next)=>{entered.resolve();await release.promise;process.chdir(next);return true;});const pending=ctx.controller.handleMoveCommand(target);
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!;for(const file of [source,destination]){const childDir=path.join(file.slice(0,-6),'late-children');assert.throws(()=>SessionManager.create(cwd,childDir),/namespace.*busy/i);await busy(path.join(childDir,'child.jsonl'));assert.equal(existsSync(childDir),false);}assert.equal(existsSync(source.slice(0,-6)),false);release.resolve();await pending;assert.equal(ctx.errors.length,0);}finally{release.resolve();await pending.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('parked nested session remains explicitly unsupported without moving its original ID or sidecars',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;const child=SessionManager.create(cwd,path.join(source.slice(0,-6),'children'));await child.ensureOnDisk();child.appendCustomEntry('parked-child',{});await child.flush();const file=child.getSessionFile()!,id=child.getSessionId();await child.close();const before=await readFile(file);const ctx=controller(session,manager,async(next)=>{process.chdir(next);return true;});
  try{await ctx.controller.handleMoveCommand(target);assert.equal(manager.getSessionFile(),source);assert(ctx.errors.some(e=>/native child relocation is not yet supported/i.test(e)));assert.deepEqual(await readFile(file),before);const reopened=await SessionManager.open(file,undefined,undefined,{expectedNativeId:id});assert.equal(reopened.getSessionId(),id);await reopened.close();}finally{process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('failed native destination rewrite restores actual file, artifact, draft and cwd before returning',async()=>{
  class FailedPublish extends FileSessionStorage { source?:string; armed=false; failed=false; override async writeTextAtomic(file:string,body:string,options?:any){if(this.armed&&!this.failed&&file!==this.source){this.failed=true;throw new Error('controlled native destination publish refusal');}return super.writeTextAtomic(file,body,options);} }
  const storage=new FailedPublish(),{manager,session,target}=await fresh(storage),source=manager.getSessionFile()!;const originalEntries=manager.getEntries().map((e:any)=>e.id);await manager.saveArtifact('artifact on failed publish','read');await manager.saveDraft('draft on failed publish');storage.source=source;storage.armed=true;
  const ctx=controller(session,manager,async(next)=>{process.chdir(next);return true;});
  try{await ctx.controller.handleMoveCommand(target);assert(storage.failed);assert(ctx.errors.some(e=>e.includes('controlled native destination publish refusal')));assert.equal(manager.getSessionFile(),source);assert.equal(manager.getCwd(),cwd);assert.equal(process.cwd(),cwd);assert.deepEqual(manager.getEntries().map((e:any)=>e.id),originalEntries);assert.equal(await manager.consumeDraft(),'draft on failed publish');assert.equal((await readFile(source,'utf8')).trim().split('\n').map(JSON.parse).find((entry:any)=>entry.type==='session').cwd,cwd);manager.appendCustomEntry('usable-after-publish-rollback',{});await manager.flush();assert((await readFile(source,'utf8')).includes('usable-after-publish-rollback'));assert.deepEqual(manager.getOwnership().heldFiles,[source]);}finally{process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('post-cwd native storage drain failure restores source through the same controller transaction',async()=>{
  class FailedDrain extends FileSessionStorage { armed=false; failed=false; override async drain(){if(this.armed&&!this.failed){this.failed=true;throw new Error('controlled native post-cwd drain refusal');}return super.drain();} }
  const storage=new FailedDrain(),{manager,session,target}=await fresh(storage),source=manager.getSessionFile()!;
  const ctx=controller(session,manager,async(next)=>{process.chdir(next);if(next===target){manager.appendCustomEntry('completed-before-drain-refusal',{});storage.armed=true;}return true;});
  try{await ctx.controller.handleMoveCommand(target);assert(storage.failed);assert(ctx.errors.some(e=>e.includes('controlled native post-cwd drain refusal')));assert.equal(manager.getSessionFile(),source);assert.equal(process.cwd(),cwd);assert.equal(manager.getOwnership().sealed,false);assert.equal(manager.getEntries().filter((e:any)=>e.customType==='completed-before-drain-refusal').length,1);assert((await readFile(source,'utf8')).includes('completed-before-drain-refusal'));assert.deepEqual(manager.getOwnership().heldFiles,[source]);}finally{process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('real completed persistent shell cd uses the same controller ownership and cwd rollback',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;
  const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();
  const ctx=controller(session,manager,async(next)=>{if(next===target){entered.resolve();await release.promise;return false;}process.chdir(next);return true;});
  const quoted="'"+target.replaceAll("'","'\\''")+"'";const pending=ctx.controller.handleBashCommand('cd '+quoted);void pending.catch(()=>{});
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!;await busy(source);await busy(destination);release.resolve();await pending;assert.equal(manager.getSessionFile(),source);assert.equal(process.cwd(),cwd);const bash=manager.getEntries().filter((e:any)=>e.type==='message'&&e.message.role==='bashExecution');assert.equal(bash.length,1);assert.equal(bash[0].message.exitCode,0);assert.deepEqual(manager.getOwnership().heldFiles,[source]);}finally{release.resolve();await pending.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
 await check('competing file transitions cannot replace the native identity during an outer move',async()=>{
  const {manager,session,target}=await fresh(),source=manager.getSessionFile()!;const entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();const ctx=controller(session,manager,async(next)=>{entered.resolve();await release.promise;process.chdir(next);return true;});const pending=ctx.controller.handleMoveCommand(target);
  try{await bounded(entered.promise);const destination=manager.getSessionFile()!,id=manager.getSessionId();await assert.rejects(manager.newSession(),/transition/i);await assert.rejects(manager.setSessionFile(source),/transition/i);await assert.rejects(manager.fork(),/transition/i);await assert.rejects(manager.dropSession(source),/transition/i);assert.throws(()=>manager.createBranchedSession(manager.getLeafId()),/transition/i);assert.equal(manager.getSessionFile(),destination);assert.equal(manager.getSessionId(),id);release.resolve();await pending;assert.equal(ctx.errors.length,0);}finally{release.resolve();await pending.catch(()=>{});process.chdir(root);await session.dispose().catch(()=>{});}
 });
}finally{auth.close();}
console.log(JSON.stringify({output:path.join(root,'result.json'),passed:checks.filter(c=>c.status==='passed').length,failed:checks.filter(c=>c.status==='failed').length}));process.exitCode=checks.some(c=>c.status==='failed')?1:0;
