import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.argv[2]!, nativePackage = process.env.BROWSER_FRAME_NATIVE_PACKAGE; assert(nativePackage);
await Promise.all(["agent", "project", "sessions"].map(name => mkdir(path.join(root, name), { recursive: true, mode: 0o700 })));
const agentDir = path.join(root, "agent"), cwd = path.join(root, "project"); await writeFile(path.join(agentDir, "config.yml"), "browser:\n  enabled: true\n  headless: true\n  cmux: false\n  relay: false\nretry:\n  enabled: false\n");
const mod = await import(pathToFileURL(path.join(nativePackage, "src/index.ts")).href), supervisor = await import(pathToFileURL(path.join(nativePackage, "src/tools/browser/tab-supervisor.ts")).href);
const { AgentRegistry, createAgentSession, discoverAuthStorage, ModelRegistry, SessionManager, Settings } = mod as typeof import("@oh-my-pi/pi-coding-agent");
const { captureTabViewportForOwner, getTab, listTabsForOwner, releaseAllTabs } = supervisor as typeof import("@oh-my-pi/pi-coding-agent/tools/browser/tab-supervisor") & { captureTabViewportForOwner(owner: string, target: { name: string; targetId: string }): Promise<{ data: Uint8Array; name: string; ownerSessionId: string; targetId: string; url: string; title: string }> };
let session: Awaited<ReturnType<typeof createAgentSession>>["session"] | undefined, server: ReturnType<typeof Bun.serve> | undefined, failure: unknown; const checks: string[] = [];
try {
  const nativeFetch = globalThis.fetch; globalThis.fetch = Object.assign((input: Parameters<typeof fetch>[0], init?: RequestInit) => { const url = new URL(input instanceof Request ? input.url : String(input)); assert(["127.0.0.1", "localhost", "[::1]"].includes(url.hostname)); return nativeFetch(input, init); }, { preconnect: () => {} }) as typeof fetch;
  let pageRequests = 0; server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch: request => { if (new URL(request.url).pathname === "/page") pageRequests++; return new Response("<!doctype html><meta charset=utf-8><title>Native viewport proof</title><style>html,body{margin:0;width:100%;height:100%;background:#2468ac}</style><script>globalThis.captureProof={token:'stable',count:9}</script>", { headers: { "Content-Type": "text/html" } }); } });
  const url = `http://127.0.0.1:${server.port}/page`, auth = await discoverAuthStorage(agentDir), settings = await Settings.loadReadOnly({ cwd, agentDir }), manager = SessionManager.create(cwd, path.join(root, "sessions")); await manager.ensureOnDisk();
  const created = await createAgentSession({ cwd, agentDir, settings, authStorage: auth, modelRegistry: new ModelRegistry(auth, path.join(agentDir, "models.yml"), { settings }), sessionManager: manager, agentRegistry: new AgentRegistry(), toolNames: ["eval"], disableExtensionDiscovery: true, enableMCP: false, hasUI: false }); session = created.session;
  const evalTool = session.getToolByName("eval"); assert(evalTool); const name = "viewport-proof"; const opened = await evalTool.execute(crypto.randomUUID(), { language: "js", title: "Open viewport proof", code: `await browser.open({name:${JSON.stringify(name)},url:${JSON.stringify(url)},viewport:{width:640,height:480,scale:1},timeout:30});`, timeout: 30 }); assert(!opened.isError);
  const owner = manager.getSessionId(), metadata = listTabsForOwner(owner), tab = metadata[0]!; assert.equal(metadata.length, 1); const nativeTab = getTab(name); assert(nativeTab?.backend === "worker"); const target = nativeTab.browser.browser.targets().find(candidate => (candidate as unknown as { _targetId?: string })._targetId === tab.targetId), page = await target?.page(); assert(page);
  const before = { url: page.url(), title: await page.title(), viewport: page.viewport(), state: await page.evaluate(() => (globalThis as any).captureProof), requests: pageRequests }; const capture = await captureTabViewportForOwner(owner, { name, targetId: tab.targetId });
  assert(capture.data instanceof Uint8Array && capture.data.byteLength > 100); assert.equal(capture.data[0], 255); assert.equal(capture.data[1], 216); assert.equal(capture.data.at(-2), 255); assert.equal(capture.data.at(-1), 217); assert.equal(capture.url, url); assert.equal(capture.title, "Native viewport proof"); assert.equal(capture.ownerSessionId, owner); assert.equal(capture.targetId, tab.targetId);
  await assert.rejects(captureTabViewportForOwner("other", { name, targetId: tab.targetId })); await assert.rejects(captureTabViewportForOwner(owner, { name, targetId: "stale" }));
  const originalScreenshot = page.screenshot.bind(page), gate = Promise.withResolvers<void>();
  (page as any).screenshot = async (options: unknown) => { await gate.promise; return originalScreenshot(options as any); };
  const timedOut = captureTabViewportForOwner(owner, { name, targetId: tab.targetId }); await assert.rejects(timedOut, /Timed out after 10000ms/); await assert.rejects(captureTabViewportForOwner(owner, { name, targetId: tab.targetId }), /already being captured/); gate.resolve(); await new Promise(resolve => setTimeout(resolve, 500)); (page as any).screenshot = originalScreenshot;
  const afterTimeout = await captureTabViewportForOwner(owner, { name, targetId: tab.targetId }); assert(afterTimeout.data.byteLength > 100);
  const after = { url: page.url(), title: await page.title(), viewport: page.viewport(), state: await page.evaluate(() => (globalThis as any).captureProof), requests: pageRequests }; assert.deepEqual(after, before); assert.equal(listTabsForOwner(owner).length, 1); assert.equal(getTab(name), nativeTab);
  checks.push("nonempty viewport JPEG comes from the exact owner-bound native target", "capture preserves URL, title, actual page viewport, document state, request count, and tab lifetime", "different-owner and stale-target capture are rejected", "timed-out capture retains its in-flight slot until the underlying screenshot settles");
} catch (error) { failure = error; } finally { await session?.dispose().catch(error => { failure ??= error; }); await releaseAllTabs({ kill: true }).catch(error => { failure ??= error; }); server?.stop(true); await writeFile(path.join(root, "result.json"), JSON.stringify({ passed: failure === undefined, checks, scope: "Copied pinned OMP candidate, disposable native browser, and loopback page only; no provider or existing profile." }, null, 2)); }
if (failure) throw failure;
