import { build } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { mkdir, readFile, writeFile, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve, join, relative } from "node:path";
import { HostStore } from "../../apps/host/src/store";
import { ThemeFile } from "../../apps/host/src/theme-file";
import { PreferencesSync } from "../../apps/host/src/preferences-sync";
import { readLocalFontFaces } from "../../apps/desktop/src/main/local-fonts";
const repo = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? ".data/appearance-flow/native001");
await mkdir(output, { recursive: true }); if ((await readdir(output)).length) throw new Error("Output must be empty");
const tracked = await new Response(Bun.spawn(["git", "ls-files", "--cached", "--others", "--exclude-standard", "apps", "packages", "scripts/acceptance/appearance.ts", "scripts/acceptance/appearance-browser.tsx"], { cwd: repo, stdout: "pipe" }).stdout).text();
const sources = [...new Set(tracked.trim().split("\n"))].sort();
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(repo, path))).digest("hex")])));
const before = await hashes(); await writeFile(join(output, "source-before.json"), JSON.stringify(before, null, 2));
const store = new HostStore(join(output, "host")), preferences = new PreferencesSync(store, () => {}), theme = new ThemeFile({ dataDirectory: join(output, "host"), store, preferences, changed() {} });
let failWrite = false; const writes: unknown[] = [];
const server = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
  const path = new URL(request.url).pathname, headers = { "access-control-allow-origin": "*", "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,OPTIONS" };
  if (request.method === "OPTIONS") return new Response(null, { headers });
  try {
    let value;
    if (path === "/fonts") value = await readLocalFontFaces();
    else if (path === "/fault") { failWrite = (await request.json()).failWrite; value = {}; }
    else if (path === "/remote") { preferences.put({ key: "theme.mode", value: "light" }); value = await theme.refresh(); }
    else if (request.method === "POST") { const body = await request.json(); if (failWrite) throw new Error("Controlled disk write unavailable"); value = await theme.set(body.document, body.expectedRevision); writes.push(body); }
    else value = await theme.refresh();
    return Response.json(value, { headers });
  } catch (error) { return Response.json({ error: String(error instanceof Error ? error.message : error) }, { status: 409, headers }); }
} });
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;height:100%}.appearance-fixture{display:grid;grid-template-columns:minmax(680px,3fr) minmax(280px,1fr);height:100vh;background:var(--app-surface);color:var(--text)}.appearance-fixture-settings{min-height:0}.appearance-fixture-settings .theme-settings{width:100%;height:100%}.appearance-fixture aside{padding:20px;min-width:0;min-height:0;display:flex;flex-direction:column;border-left:1px solid var(--border)}.appearance-fixture aside h2{font-size:14px}.appearance-fixture aside .pierre-source-editor-frame{flex:1;min-height:0}.appearance-fixture aside .pierre-source-editor{height:100%}.appearance-diff{height:260px;flex:none;min-height:0;display:flex;flex-direction:column;margin-top:16px}.appearance-diff .review-scroll{height:100%}</style><div id="root"></div><script>window.fixtureEndpoint=${JSON.stringify(server.url.origin)}</script><script type="module" src="${relative(output, join(import.meta.dir, "appearance-browser.tsx"))}"></script>`);
let code = 1;
try {
  await build({ configFile: false, logLevel: "warn", root: output, base: "./", plugins: [react(), tailwindcss()], build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });
  const main = String.raw`const {app,BrowserWindow,clipboard,nativeTheme}=require('electron'),fs=require('node:fs'),path=require('node:path');
app.setPath('userData',path.join(__dirname,'electron-profile'));app.commandLine.appendSwitch('disable-renderer-backgrounding');
app.whenReady().then(async()=>{const win=new BrowserWindow({width:1280,height:1000,useContentSize:true,show:false,webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false,backgroundThrottling:false}}),checks=[],captures=[];let step='load';
const js=source=>win.webContents.executeJavaScript(source),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const wait=async expression=>{for(let i=0;i<400;i++){if(await js(expression))return;await pause(25)}throw new Error('Timed out '+expression)};
const click=async selector=>{const point=await js('window.point('+JSON.stringify(selector)+')');for(const type of ['mouseMove','mouseDown','mouseUp'])win.webContents.sendInputEvent({type,...point,...(type==='mouseMove'?{}:{button:'left',clickCount:1})});await pause(80)};
const key=async(keyCode,modifiers=[])=>{for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode,modifiers});await pause(80)};
const choose=async(label,query)=>{await click('button[aria-label="'+label+'"]');if(label.toLowerCase().includes('font')){for(const character of query)await key(character)}else await win.webContents.insertText(query);await key('Enter');await wait('!window.theme.saving&&!window.theme.dirty')};
const capture=async name=>{await pause(150);fs.writeFileSync(path.join(__dirname,name+'.png'),(await win.webContents.capturePage()).toPNG());captures.push(name)};
try{await win.loadFile(path.join(__dirname,'web/index.html'));win.webContents.focus();await wait('window.theme?.current&&!window.theme.loading&&document.querySelector("diffs-container")?.shadowRoot?.querySelector("[contenteditable=true]")');
step='native-preset';await choose('Dark code theme','Dracula');await js('document.querySelector("#appearance-mode").value="dark";document.querySelector("#appearance-mode").dispatchEvent(new Event("change",{bubbles:true}))');await wait('window.snapshot().dataset.codeTheme==="dracula"&&!window.theme.dirty');await capture('01-dracula');await wait('window.snapshot().diffColors.some(item=>item.text.includes("const")&&item.color!=="rgb(255, 255, 255)")');const draculaDiff=await js('JSON.stringify(window.snapshot().diffColors)');checks.push('Actual searchable preset selection immediately saved to ThemeFile/SQLite and applied dark palette');
step='editor-preservation';await js('document.querySelector("diffs-container").shadowRoot.querySelector("[contenteditable=true]").focus()');await key('End',['meta']);await win.webContents.insertText('// retained edit');await wait('window.snapshot().text.includes("retained edit")');await choose('Dark code theme','Nord');await wait('window.snapshot().dataset.codeTheme==="nord"');await js('document.querySelector("diffs-container").shadowRoot.querySelector("[contenteditable=true]").focus()');await key('z',['meta']);await wait('!window.snapshot().text.includes("retained edit")');await wait('JSON.stringify(window.snapshot().diffColors)!=='+JSON.stringify(draculaDiff));checks.push('Real source editor edit and undo survive code-preset switch; actual ReviewDiff worker pool re-highlights the same patch');await capture('02-nord-editor');
step='real-font-face';await wait('document.querySelectorAll("#theme-local-fonts option").length>10');await choose('Dark code font','Menlo');await choose('Dark code font style','Bold');await wait('window.theme.current.document.appearance.dark.fonts.code.face?.postscriptName==="Menlo-Bold"&&!window.theme.dirty');await js('document.fonts.ready');await wait('Array.from(document.fonts).some(face=>face.family.includes("Agent Desktop selected Menlo-Bold")&&face.status==="loaded")');checks.push('Actual macOS font catalog and specific Menlo Bold face saved and loaded');
step='hex-and-picker';await click('input[aria-label="Dark accent"]');win.webContents.selectAll();await pause(80);await js('if(document.activeElement.selectionStart!==0||document.activeElement.selectionEnd!==document.activeElement.value.length)throw new Error("Electron editing command did not select the input")');await win.webContents.insertText('#abc');if(await js('window.theme.current.document.appearance.dark.accent')==='#abc')throw new Error('Partial hex saved');await key('Tab');await wait('Array.from(document.querySelectorAll("input")).find(input=>input.ariaLabel==="Dark accent").value.length===7');await click('input[aria-label="Dark accent"]');win.webContents.selectAll();await pause(80);await js('if(document.activeElement.selectionStart!==0||document.activeElement.selectionEnd!==document.activeElement.value.length)throw new Error("Electron editing command did not select the input")');await win.webContents.insertText('#336699');await wait('window.theme.current.document.appearance.dark.accent==="#336699"&&!window.theme.dirty');await click('button[aria-label="Pick dark accent"]');await click('[role="slider"][aria-label="Dark accent saturation and brightness"]');await key('ArrowRight');await key('Escape');await wait('!document.querySelector(".appearance-color-popover")&&!window.theme.dirty');if(await js('window.theme.current.document.appearance.dark.accent')==='#336699')throw new Error('Color picker did not change saved accent');checks.push('Native hex input preserves incomplete text until blur and saves valid hex; saturation pointer/keyboard interaction saves and Escape restores the trigger');
step='copy-import';await click('button[aria-label="Copy dark theme"]');await pause(200);const shared=await clipboard.readText();if(!shared.startsWith('codex-theme-v1:'))throw new Error('Theme copy missing pinned share format');await click('button[aria-label="Import dark theme"]');await win.webContents.insertText(shared);await js('Array.from(document.querySelectorAll(".appearance-import button")).find(button=>button.textContent==="Import theme").click()');await wait('!document.querySelector(".appearance-import")&&!window.theme.saving');checks.push('Real clipboard copy and native-dialog import round-trip the palette/font face');
step='write-failure';await js('window.request("/fault",{failWrite:true})');await click('[role="switch"][aria-label="Use pointer cursors"]');await wait('window.theme.error&&window.theme.dirty&&!window.theme.saving');await capture('03-write-error');await js('window.request("/fault",{failWrite:false})');await js('Array.from(document.querySelectorAll("button")).find(button=>button.textContent==="Retry theme changes").click()');await wait('!window.theme.error&&!window.theme.dirty');checks.push('Failed immediate write retains preview/error and deliberate retry commits through real storage');
step='reopen';const saved=await js('JSON.stringify(window.theme.current.document)');await win.reload();await wait('window.theme?.current&&!window.theme.loading');if(await js('JSON.stringify(window.theme.current.document)')!==saved)throw new Error('Reload lost theme');checks.push('Renderer reload recovers exactly persisted palette, local font face, and preferences');await capture('04-reopened');
step='capability';await js('window.capability(false)');await wait('Array.from(document.querySelectorAll("button")).find(item=>item.ariaLabel==="Dark translucent sidebar").disabled');if(await js('window.theme.dirty'))throw new Error('Capability loss edited saved theme');checks.push('Unavailable translucency disables action without rewriting saved per-variant request');
step='light';await js('document.querySelector("#appearance-mode").value="light";document.querySelector("#appearance-mode").dispatchEvent(new Event("change",{bubbles:true}))');await wait('window.snapshot().dataset.resolvedTheme==="light"&&!window.theme.dirty');await capture('05-light');checks.push('Light mode uses separate saved palette and code-theme selection');
step='system';nativeTheme.themeSource='dark';await js('document.querySelector("#appearance-mode").value="system";document.querySelector("#appearance-mode").dispatchEvent(new Event("change",{bubbles:true}))');await wait('window.snapshot().dataset.resolvedTheme==="dark"&&!window.theme.dirty');nativeTheme.themeSource='light';await wait('window.snapshot().dataset.resolvedTheme==="light"');checks.push('Actual Electron system appearance changes switch the existing palette and code consumers');
step='legacy-overrides';await js('window.theme.edit({...window.theme.draft,tokens:{...window.theme.draft.tokens,"--app-surface":"rgba(12, 34, 56, .5)","--radius":"20px"}})');await wait('Array.from(document.querySelectorAll("button")).find(button=>button.ariaLabel==="Dark code theme").disabled');await js('Array.from(document.querySelectorAll("button")).find(button=>button.textContent==="Save advanced preview").click()');await wait('!window.theme.dirty');await choose('Dark code theme','Dracula');if(await js('window.theme.current.document.tokens["--app-surface"]')!=='rgba(12, 34, 56, .5)')throw new Error('Preset erased advanced color');await js('Array.from(document.querySelectorAll("button")).find(button=>button.textContent==="Clear palette and font overrides for both themes").click()');await wait('!window.theme.dirty');if(await js('window.theme.current.document.tokens["--app-surface"]!==undefined||window.theme.current.document.tokens["--radius"]!=="20px"'))throw new Error('Explicit override clearing changed unrelated advanced values');checks.push('Advanced previews require explicit save; preset changes preserve legacy alpha colors until explicit override clearing, preserving unrelated radius');
const state=await js('window.snapshot()');if(state.errors.length)throw new Error(JSON.stringify(state.errors));fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({passed:true,checks,captures,state,contentBounds:win.getContentBounds(),scope:'Actual mounted ThemeSettings/Pierre editor, native Electron input and clipboard, macOS font catalog, real temporary ThemeFile/SQLite through fixture HTTP. No full App IPC or native translucency claim.'},null,2));app.exit(0);
}catch(error){await capture('failure').catch(()=>{});fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({passed:false,step,error:String(error),checks,captures,state:await js('window.snapshot()').catch(()=>null)},null,2));app.exit(1)}});`;
  await writeFile(join(output, "main.cjs"), main);
  const child = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs")], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) });
  const timeout = setTimeout(() => child.kill("SIGTERM"), 120_000); code = await child.exited; clearTimeout(timeout);
} finally {
  server.stop(true); await theme.dispose(); preferences.dispose(); store.close();
  await writeFile(join(output, "writes.json"), JSON.stringify(writes, null, 2));
  const after = await hashes(); await writeFile(join(output, "source-after.json"), JSON.stringify(after, null, 2));
  if (JSON.stringify(before) !== JSON.stringify(after)) throw new Error("Source changed during fixture");
}
if (code !== 0) throw new Error(`Appearance fixture failed: ${output}`);
console.log(JSON.stringify({ passed: true, output }));
