import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { build } from "vite";

const repo = resolve(import.meta.dir, "../..");
const output = resolve(process.argv[2] ?? `.data/configuration-layout-${Date.now()}`);
if (existsSync(output) && (await readdir(output)).length) throw new Error(`Output must be empty: ${output}`);
await mkdir(output, { recursive: true, mode: 0o700 });
const sources = [
  "apps/desktop/src/renderer/App.tsx", "apps/desktop/src/renderer/NativeSettings.tsx", "apps/desktop/src/renderer/native-settings.css",
  "apps/desktop/src/renderer/NativeSwitch.tsx", "apps/desktop/src/renderer/native-switch.css",
  "apps/desktop/src/renderer/SettingsSidebar.tsx", "apps/desktop/src/renderer/settings-sidebar.css", "apps/desktop/src/renderer/SshToolSettings.tsx",
  "apps/desktop/src/renderer/ssh-tool-settings.css", "apps/desktop/src/renderer/styles.css", "apps/desktop/src/renderer/theme.css",
  "packages/shared/src/settings.ts", "packages/shared/src/protocol.ts", "scripts/acceptance/configuration-layout.ts", "scripts/acceptance/configuration-layout-browser.tsx",
];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(repo, path))).digest("hex")])));
const before = await hashes();
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "configuration-layout-browser.tsx"))}"></script>`);
await writeFile(join(output, "tsconfig.fixture.json"), JSON.stringify({ extends: join(repo, "tsconfig.json"), compilerOptions: { paths: { "@agent-desktop/shared": [join(repo, "packages/shared/src/protocol.ts")] } }, include: [join(repo, "scripts/acceptance/configuration-layout-browser.tsx")] }, null, 2));
const check = Bun.spawn([process.execPath, join(repo, "node_modules/typescript/bin/tsc"), "-p", join(output, "tsconfig.fixture.json"), "--pretty", "false"], { cwd: output, stdout: Bun.file(join(output, "strict.log")), stderr: Bun.file(join(output, "strict-errors.log")), env: { HOME: output, PATH: "/usr/bin:/bin" } });
if (await check.exited !== 0) throw new Error(`Strict fixture compilation failed; inspect ${join(output, "strict-errors.log")}`);
await build({ configFile: join(repo, "apps/desktop/vite.config.ts"), root: output, logLevel: "warn", worker: { format: "es" }, build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });

const profile = await mkdtemp(join(tmpdir(), "agent-desktop-configuration-layout-"));
let exitCode = -1;
try {
  await writeFile(join(output, "main.cjs"), String.raw`
const {app,BrowserWindow}=require("electron"),fs=require("node:fs"),path=require("node:path");
const output=process.argv[2],profile=process.argv[3],sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));app.setPath("userData",profile);
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1440,height:820,webPreferences:{sandbox:true,contextIsolation:false,nodeIntegration:false,backgroundThrottling:false}});const js=source=>win.webContents.executeJavaScript(source,true),state=()=>js("configurationLayoutState()"),steps=[];const assert=(v,m)=>{if(!v)throw Error(m)},wait=async source=>{for(let i=0;i<320;i++){if(await js(source))return;await sleep(25)}throw Error("Timed out: "+source)},observe=async name=>steps.push({name,state:await state()});const select=async(label,value)=>{await js("(()=>{const e=document.querySelector('[aria-label=\""+label+"\"]');e.value='"+value+"';e.dispatchEvent(new Event('change',{bubbles:true}));})()");await sleep(50)};const set=async(label,value)=>{await js("(()=>{const e=document.querySelector('[aria-label=\""+label+"\"]');const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;s.call(e,"+JSON.stringify(value)+");e.dispatchEvent(new Event('input',{bubbles:true}));})()");await sleep(50)};const click=async selector=>{const p=await js("(()=>{const e=document.querySelector("+JSON.stringify(selector)+");if(!e)throw Error('Missing '+"+JSON.stringify(selector)+");const b=e.getBoundingClientRect();return{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}})()");for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...p,...(type==="mouseMove"?{}:{button:"left",clickCount:1})});await sleep(50)};
try{await win.loadFile(path.join(output,"web/index.html"));await wait("configurationLayoutState().categoryOptions.length>=6");let s=await state();assert(s.outerSidebars===1&&s.nestedSidebars===0&&s.legacyLayouts===0,"Configuration retained a second navigation rail or legacy layout");assert(s.backButtons===1&&s.headings.includes("Configuration"),"Configuration heading or sole outer Back control missing");assert(s.structure,"Single-column Configuration structure missing");assert(s.categoryOptions.slice(0,3).map(o=>o.value).join(',')==='ssh,models,all',"Native category built-ins or order changed");assert(s.categoryOptions.some(o=>o.value==='appearance'&&o.text.includes('2'))&&s.categoryOptions.some(o=>o.value==='advanced'&&o.text.includes('1'))&&s.categoryOptions.some(o=>o.value==='future'&&o.text.includes('1')),"Schema categories/counts, including a schema-only future category, are missing");assert(s.text.includes("4 core settings"),"All-category inventory count did not include every schema descriptor");assert(s.column.width<=768&&s.column.left>=s.page.left&&s.column.right<=s.page.right+1,"Wide Configuration layout exceeds its column");const scalarWide=s.rows.scalar,compoundWide=s.rows.compound;assert(scalarWide.summary.right<=scalarWide.controls.left&&scalarWide.card.left<=scalarWide.main.left&&scalarWide.main.right<=scalarWide.card.right,"Wide scalar row did not place its editor to the right inside the card");assert(compoundWide.compound&&compoundWide.controls.top>=compoundWide.summary.bottom&&compoundWide.card.left<=compoundWide.controls.left&&compoundWide.controls.right<=compoundWide.card.right,"Compound editor did not use the full-width row below its summary");assert(!scalarWide.detailsOpen&&!scalarWide.pathVisible,"Clean row exposed technical metadata outside its collapsed details");await observe("single-column-inventory-wide");win.setSize(720,820);await wait("configurationLayoutState().viewport.width===720");s=await state();const initialColumnLeft=s.column.left;assert(s.viewport.scrollWidth<=s.viewport.width&&s.scroll.scrollWidth<=s.scroll.clientWidth&&s.column.width<=768&&s.column.left>=s.page.left&&s.column.right<=s.page.right+1,"Narrow Configuration layout overflows or exceeds its column");assert(s.rows.scalar.controls.top>=s.rows.scalar.summary.bottom&&s.rows.compound.controls.top>=s.rows.compound.summary.bottom,"Narrow compact rows did not stack controls below summaries");await observe("single-column-narrow-bounds");
await select("Native settings category","appearance");await wait("configurationLayoutState().category==='appearance'");await click("[data-setting-path='appearance.fixtureEnabled'] [role='switch'][aria-label='Fixture enabled']");await wait("configurationLayoutState().checked===true");s=await state();assert(s.text.includes("1 unsaved")&&s.settingWrites.length===0,"Local edit was not retained without a host write");assert(s.rows.scalar.save&&!s.rows.scalar.save.disabled&&s.rows.scalar.discard,"Changed compact row did not expose enabled Save and Discard");await click("[data-setting-path='appearance.fixtureEnabled'] .native-setting-details > summary");await wait("configurationLayoutState().rows.scalar.detailsOpen");s=await state();assert(s.rows.scalar.reset?.visible&&!s.rows.scalar.reset.disabled&&s.rows.scalar.pathVisible,"Native details did not expose Reset and technical path metadata");await select("Native settings scope","project");await wait("configurationLayoutState().scope==='project'");await select("Native settings scope","global");await wait("configurationLayoutState().checked===true");s=await state();assert(s.text.includes("1 unsaved")&&s.settingWrites.length===0,"Scope switch discarded or persisted the unsaved host edit");await observe("scope-switch-retains-unsaved-edit");
await js("configurationLayoutControl('advance-settings-revision')");await wait("configurationLayoutState().rows.scalar.rebase===true");s=await state();assert(s.checked&&s.rows.scalar.detailsOpen&&s.rows.scalar.save?.disabled&&s.rows.scalar.discard&&s.rows.scalar.alert?.includes('saved revision changed')&&s.settingWrites.length===0,"Newer saved revision did not preserve and fence the compact-row edit");await observe("stale-edit-fenced-before-rebase");await click("[data-setting-path='appearance.fixtureEnabled'] .native-edit-error button");await wait("configurationLayoutState().rows.scalar.save?.disabled===false&&!configurationLayoutState().rows.scalar.rebase");s=await state();assert(s.checked&&s.rows.scalar.discard&&s.settingWrites.length===0,"Explicit rebase lost the edit or wrote it to the host");await observe("stale-edit-requires-explicit-rebase");
await select("Native settings category","ssh");await wait("configurationLayoutState().category==='ssh'&&configurationLayoutState().text.includes('SSH tool targets')");await set("Search all native settings","advanced.hiddenContract");await wait("configurationLayoutState().advancedVisible&&configurationLayoutState().advancedOpen&&configurationLayoutState().rows.advanced.detailsOpen");s=await state();assert(s.scopeVisible&&s.text.includes("Results for “advanced.hiddenContract”")&&s.rows.advanced.pathVisible,"All-schema path search did not open advanced technical details or restore scope");assert(s.column.left===initialColumnLeft,"Filtering shifted the stable Configuration column horizontally");await observe("all-schema-search-includes-advanced-from-ssh");
await set("Search all native settings","");await wait("configurationLayoutState().text.includes('SSH tool targets')");await select("Native settings category","models");await wait("configurationLayoutState().category==='models'&&configurationLayoutState().text.includes('Session & models')");await observe("ssh-and-models-reachable");
fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:true,hidden:true,electron:process.versions.electron,input:"Actual full production App and NativeSettings under a controlled bridge; switch/details/rebase pointer through Electron sendInputEvent and controlled select/search DOM change events; no fixture-owned focus.",steps},null,2));}catch(error){fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:false,error:String(error.stack||error),state:await state().catch(()=>null),steps},null,2));}finally{win.close();app.quit();}});
`);
  const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs"), output, profile], { cwd: profile, stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")), env: { HOME: profile, TMPDIR: profile, PATH: "/usr/bin:/bin" } });
  const timer = setTimeout(() => electron.kill("SIGTERM"), 60_000); try { exitCode = await electron.exited; } finally { clearTimeout(timer); }
} finally { await rm(profile, { recursive: true, force: true }); }
let result: Record<string, unknown>; try { result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); } catch (cause) { result = { passed: false, resultReadError: cause instanceof Error ? cause.message : String(cause) }; }
result.exitCode = exitCode; result.sourceBeforeBuild = before; result.sourceAfterRun = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceBeforeBuild) === JSON.stringify(result.sourceAfterRun); result.scope = "Full production App and NativeSettings in hidden isolated Electron with controlled bridge data. This proves DOM structure, controlled state transitions, switch/details/rebase pointer input, and responsive overflow behavior; it is not native reference or pixel proof."; result.passed = result.passed === true && exitCode === 0 && result.sourceHashesStable; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`Configuration layout acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
