import {createHash} from "node:crypto";
import {mkdir,mkdtemp,readFile,readdir,realpath,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,relative,resolve} from "node:path";
import {build} from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import type {CommandEnvelope} from "../../packages/shared/src/protocol";
import {startHost} from "../../apps/host/src/server";

const repo=resolve(import.meta.dir,"../.."),output=resolve(process.argv[2]??`.data/files-explorer-${Date.now()}`),fixture=await realpath(await mkdtemp(join(tmpdir(),"agent-files-explorer-"))),workspace=join(fixture,"workspace"),dataDirectory=join(fixture,"data"),agentDirectory=join(fixture,"agent");
const sources=["packages/shared/src/workspace.ts","packages/shared/src/workspace-protocol.ts","apps/host/src/workspace/service.ts","apps/host/src/workspace-http.ts","apps/host/src/server.ts","apps/desktop/src/renderer/workspace-state.ts","apps/desktop/src/renderer/WorkspaceFileTree.tsx","apps/desktop/src/renderer/WorkspaceTreeMenu.tsx","apps/desktop/src/renderer/WorkspacePathDialog.tsx","apps/desktop/src/renderer/workspace-file-tree.css","apps/desktop/src/renderer/workspace-path-dialog.css","scripts/acceptance/files-explorer.ts","scripts/acceptance/files-explorer-browser.tsx","scripts/acceptance/files-explorer-electron.cjs"];
const hashes=async()=>Object.fromEntries(await Promise.all(sources.map(async file=>[file,createHash("sha256").update(await readFile(join(repo,file))).digest("hex")])));
await mkdir(output,{recursive:true,mode:0o700});if((await readdir(output)).length)throw new Error("Output must be empty");await Promise.all([workspace,agentDirectory].map(path=>mkdir(path)));await writeFile(join(workspace,"seed.txt"),"seed\n");
const host=await startHost({dataDirectory,agentDirectory,discoveryDirectory:workspace,port:0,tailscale:false});let proxy:ReturnType<typeof Bun.serve>|undefined;
try{
 const native=async(path:string,body:unknown)=>{const response=await fetch(host.connection.origin+path,{method:"POST",headers:{authorization:`Bearer ${host.connection.token}`,"content-type":"application/json"},body:JSON.stringify(body)});return new Response(await response.arrayBuffer(),{status:response.status,headers:{"content-type":"application/json","access-control-allow-origin":"*"}})};
 const add=await (await native("/v1/commands",{id:"files-project",command:{type:"project.add",path:workspace}})).json() as any;if(!add.ok)throw new Error("Project add failed");const target={projectId:add.value.id},calls:{route:string;type?:string}[]=[];
 proxy=Bun.serve({hostname:"127.0.0.1",port:0,async fetch(request){const input=await request.json() as any,path=new URL(request.url).pathname;if(input.hostId&&input.hostId!==host.connection.hostId)return Response.json({error:{message:"Wrong host"}},{status:403});if(path==="/workspace"){calls.push({route:path,type:input.query?.type});return native("/v1/workspace/query",{target:input.owner,query:input.query})}if(path==="/command"){const envelope=input.envelope as CommandEnvelope;calls.push({route:path,type:envelope.command.type==="workspace.mutate"?envelope.command.action.type:envelope.command.type});return native("/v1/commands",envelope)}if(path==="/external"){await writeFile(join(workspace,input.path),input.text);return Response.json({ok:true},{headers:{"access-control-allow-origin":"*"}})}if(path==="/external-folder"){await mkdir(join(workspace,"folder"),{recursive:true});await writeFile(join(workspace,"folder","child.txt"),"child\n");return Response.json({ok:true},{headers:{"access-control-allow-origin":"*"}})}if(path==="/files")return Response.json({files:await readdir(workspace)},{headers:{"access-control-allow-origin":"*"}});if(path==="/calls")return Response.json({count:calls.length,calls},{headers:{"access-control-allow-origin":"*"}});return Response.json({error:{message:"Unknown fixture route"}},{status:404,headers:{"access-control-allow-origin":"*"}})}});
 const sourceAtBuild=await hashes();await writeFile(join(output,"index.html"),`<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="${relative(output,join(import.meta.dir,"files-explorer-browser.tsx"))}"></script>`);await build({configFile:false,root:output,plugins:[react(),tailwindcss()],base:"./",build:{outDir:join(output,"web"),rollupOptions:{input:join(output,"index.html")}}});await writeFile(join(output,"launch.json"),JSON.stringify({endpoint:`http://127.0.0.1:${proxy.port}`,target,hostId:host.connection.hostId,cwd:workspace,profile:join(fixture,"profile")}));
 const electron=Bun.spawn([process.execPath,join(repo,"node_modules/electron/cli.js"),join(import.meta.dir,"files-explorer-electron.cjs"),output],{stdout:Bun.file(join(output,"electron.log")),stderr:Bun.file(join(output,"electron-errors.log"))}),timer=setTimeout(()=>electron.kill("SIGTERM"),90000),code=await electron.exited;clearTimeout(timer);
 const result=JSON.parse(await readFile(join(output,"result.json"),"utf8"));result.sourceAtBuild=sourceAtBuild;result.sourceAfterRun=await hashes();result.sourceHashesStable=JSON.stringify(result.sourceAtBuild)===JSON.stringify(result.sourceAfterRun);result.passed&&=code===0&&result.sourceHashesStable;await writeFile(join(output,"result.json"),JSON.stringify(result,null,2));if(!result.passed)throw new Error(`Files explorer acceptance failed: ${join(output,"result.json")}`);console.log(JSON.stringify({passed:true,output}));
}finally{proxy?.stop(true);await host.stop();await rm(fixture,{recursive:true,force:true});await rm(join(output,"launch.json"),{force:true})}
