import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { build } from "vite";
const repo = resolve(import.meta.dir,"../.."), output = resolve(process.argv[2] ?? `.data/general-dock-${Date.now()}`);
await mkdir(output,{recursive:true,mode:0o700});if((await readdir(output)).length)throw Error("Use a new empty evidence directory");
const sources = ["packages/shared/src/preferences.ts","apps/desktop/src/renderer/App.tsx","apps/desktop/src/renderer/GeneralSettings.tsx","apps/desktop/src/renderer/general-settings.css","apps/desktop/src/renderer/preferences-state.ts","apps/desktop/src/renderer/use-workbench-dock.tsx","apps/desktop/src/renderer/dock-state.ts","apps/desktop/src/renderer/app-shortcuts.ts","apps/desktop/src/renderer/EnvironmentActions.tsx","apps/desktop/src/renderer/NativeSwitch.tsx","apps/desktop/src/renderer/styles.css","apps/desktop/src/renderer/theme.css","scripts/acceptance/app-dock-browser.tsx","scripts/acceptance/general-dock.ts","scripts/acceptance/general-dock-browser.tsx"];
const hashes=async()=>Object.fromEntries(await Promise.all(sources.map(async path=>[path,createHash("sha256").update(await readFile(join(repo,path))).digest("hex")])));
const before=await hashes();await writeFile(join(output,"source-before.json"),JSON.stringify(before,null,2));
await writeFile(join(output,"index.html"),`<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="${relative(output,join(import.meta.dir,"general-dock-browser.tsx"))}"></script>`);
await writeFile(join(output,"tsconfig.fixture.json"),JSON.stringify({extends:join(repo,"tsconfig.json"),compilerOptions:{paths:{"@agent-desktop/shared":[join(repo,"packages/shared/src/protocol.ts")]}},include:[join(repo,"scripts/acceptance/general-dock-browser.tsx")]},null,2));
const check=Bun.spawn([process.execPath,join(repo,"node_modules/typescript/bin/tsc"),"-p",join(output,"tsconfig.fixture.json"),"--pretty","false"],{stdout:Bun.file(join(output,"strict.log")),stderr:Bun.file(join(output,"strict-error.log"))});
const strictExit=await check.exited;if(strictExit)throw Error(`Strict fixture compile failed (${strictExit})`);
await build({configFile:join(repo,"apps/desktop/vite.config.ts"),root:output,logLevel:"warn",worker:{format:"es"},build:{outDir:join(output,"web"),rollupOptions:{input:join(output,"index.html")}}});
const profile=await mkdtemp(join(tmpdir(),"general-dock-control-"));let exitCode=-1;
try {
 await writeFile(join(output,"main.cjs"),String.raw`
const{app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path');const output=process.argv[2];app.setPath('userData',process.argv[3]);
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),steps=[];const js=s=>win.webContents.executeJavaScript(s,true),state=()=>js('generalDockState()'),sleep=ms=>new Promise(r=>setTimeout(r,ms));const assert=(v,m)=>{if(!v)throw Error(m)},wait=async s=>{for(let i=0;i<300;i++){if(await js(s))return;await sleep(25)}throw Error('Timed out: '+s)};
const click=async(selector,text)=>{const p=await js('(()=>{const e=[...document.querySelectorAll('+JSON.stringify(selector)+')].find(e=>e.getClientRects().length&&!e.disabled&&'+(text===undefined?'true':'e.textContent.trim().startsWith('+JSON.stringify(text)+')')+');if(!e)throw Error("Missing pointer target");const b=e.getBoundingClientRect();return{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}})()');for(const type of ['mouseMove','mouseDown','mouseUp'])win.webContents.sendInputEvent({type,...p,...(type==='mouseMove'?{}:{button:'left',clickCount:1})});await sleep(60)};
const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await sleep(100)};
const capture=async name=>{steps.push({name,state:await state(),preferences:await js('generalDockPreferences()')});fs.writeFileSync(path.join(output,name+'.png'),(await win.webContents.capturePage()).toPNG())};
const settings=async()=>{await click('.profile-trigger');await click('[role=menuitem]','Settings');await wait('Boolean(document.querySelector(".general-settings"))')};const back=async()=>{await click('.settings-sidebar-back');await wait('!document.querySelector(".general-settings")')};
try{
 win.webContents.on('console-message',(_e,_level,message)=>fs.appendFileSync(path.join(output,'renderer.log'),message+'\n'));await win.loadFile(path.join(output,'web/index.html'));await wait('Boolean(document.querySelector(".profile-trigger")&&document.querySelector("#prompt"))');win.webContents.focus();
 await settings();await wait('generalDockState().bottomPreference==="true"&&generalDockState().selectedLocation==="Bottom"');await capture('01-default-controls');
 await click('.general-segmented button','Right');await wait('generalDockState().selectedLocation==="Right"');await back();
 await click('#prompt');await key(String.fromCharCode(96),['control']);await wait('generalDockState().tabs.some(t=>t.id.includes("terminal")&&t.destination==="right")');assert((await state()).tabs.filter(t=>t.id.includes('terminal')).length===1,'Shortcut duplicated the terminal tab');await capture('02-shortcut-right');
 await settings();await click('.general-segmented button','Bottom');await wait('generalDockState().selectedLocation==="Bottom"');await back();await click('.dock-slot-right [aria-label="Close project tab"]');await wait('!generalDockState().tabs.some(t=>t.id.includes("terminal"))');await click('#prompt');await key(String.fromCharCode(96),['control']);await wait('generalDockState().tabs.some(t=>t.id.includes("terminal")&&t.destination==="bottom")');const beforeOff=(await state()).tabs;await capture('03-shortcut-bottom');
 await settings();await click('[role=switch][aria-label="Bottom panel"]');await wait('generalDockState().bottomPreference==="false"&&!generalDockState().location');await back();let s=await state();assert(!s.bottomLauncher,'Disabled bottom launcher remained visible');assert(JSON.stringify(s.tabs)===JSON.stringify(beforeOff),'Preference change migrated/closed existing tabs');await capture('04-hidden-preserves-tabs');
 const prefs=await js('generalDockPreferences()');assert(prefs.records.some(r=>r.key==='general.defaultTerminalLocation'&&r.value==='bottom'),'Hiding bottom panel erased stored preference');
 await click('.dock-slot-bottom [aria-label="Close project tab"]');await wait('!generalDockState().tabs.some(t=>t.id.includes("terminal"))');await click('#prompt');await key(String.fromCharCode(96),['control']);await wait('generalDockState().tabs.some(t=>t.id.includes("terminal")&&t.destination==="right")');await capture('05-disabled-forces-right');
 await settings();await click('[role=switch][aria-label="Bottom panel"]');await wait('generalDockState().selectedLocation==="Bottom"');await back();assert((await state()).bottomLauncher,'Re-enabled bottom launcher missing');await capture('06-restores-choice');
 const end=await state();assert(end.commands.every(c=>c.command.type==='preferences.put'),'Fixture dispatched a non-preference command');assert(end.terminalActions.every(a=>!['create','write'].includes(a[0].type)),'Fixture created or wrote a terminal');
 fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:true,steps,scope:'Full actual App under existing controlled bridge; pointer/shortcut input through Electron. No real terminal, provider or native OS capture.'},null,2));
}catch(e){fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:false,error:String(e.stack||e),steps,state:await state().catch(()=>null)},null,2));}finally{win.close();app.quit();}});
`);
 const child=Bun.spawn([process.execPath,join(repo,"node_modules/electron/cli.js"),join(output,"main.cjs"),output,profile],{cwd:profile,env:{HOME:profile,PATH:"/usr/bin:/bin",TMPDIR:profile},stdout:Bun.file(join(output,"electron.log")),stderr:Bun.file(join(output,"electron-error.log"))});const timer=setTimeout(()=>child.kill("SIGTERM"),60000);try{exitCode=await child.exited}finally{clearTimeout(timer)};
} finally {await rm(profile,{recursive:true,force:true})}
let result:Record<string,unknown>;try{result=JSON.parse(await readFile(join(output,"result.json"),"utf8"))}catch(error){result={passed:false,error:String(error)}}
const after=await hashes();Object.assign(result,{exitCode,strictExit,sourceBefore:before,sourceAfter:after,sourceHashesStable:JSON.stringify(before)===JSON.stringify(after)});result.passed=result.passed===true&&exitCode===0&&result.sourceHashesStable;await writeFile(join(output,"result.json"),JSON.stringify(result,null,2));if(!result.passed)throw Error(`App General dock acceptance failed: ${output}`);console.log(JSON.stringify({passed:true,output}));
