import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import react from "@vitejs/plugin-react";
import { build } from "vite";

const repo = resolve(import.meta.dir, "../..");
const output = resolve(process.argv[2] ?? `.data/git-submission-dialog-${Date.now()}`);
if (existsSync(output) && (await readdir(output)).length) throw new Error(`Output must be empty: ${output}`);
await mkdir(output, { recursive: true, mode: 0o700 });
const sources = [
  "apps/desktop/src/renderer/GitSubmissionDialog.tsx", "apps/desktop/src/renderer/git-submission-dialog.css", "apps/desktop/src/renderer/git-submission-view.ts",
  "apps/desktop/src/renderer/BranchSelector.tsx", "apps/desktop/src/renderer/branch-selector.css", "apps/desktop/src/renderer/Icons.tsx",
  "apps/desktop/src/renderer/workspace-state.ts", "packages/shared/src/git-submissions.ts", "packages/shared/src/workspace.ts", "packages/shared/src/workspace-protocol.ts",
  "scripts/acceptance/git-submission-dialog.ts", "scripts/acceptance/git-submission-dialog-browser.tsx",
];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(repo, path))).digest("hex")])));
const sourceAtBuild = await hashes();
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;height:100%;font:14px system-ui;background:#222;color:#eee}main{padding:16px}</style><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "git-submission-dialog-browser.tsx"))}"></script>`);
await writeFile(join(output, "tsconfig.fixture.json"), JSON.stringify({ extends: join(repo, "tsconfig.json"), include: [join(repo, "scripts/acceptance/git-submission-dialog-browser.tsx"), join(repo, "apps/desktop/src/renderer/GitSubmissionDialog.tsx")] }, null, 2));
const check = Bun.spawn([process.execPath, "x", "tsc", "-p", join(output, "tsconfig.fixture.json"), "--pretty", "false"], { cwd: output, stdout: Bun.file(join(output, "strict.log")), stderr: Bun.file(join(output, "strict-errors.log")), env: { HOME: output, PATH: "/usr/bin:/bin" } });
if (await check.exited !== 0) throw new Error(`Strict fixture compilation failed; inspect ${join(output, "strict-errors.log")}`);
await build({ configFile: false, root: output, plugins: [react()], base: "./", build: { target: "esnext", outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });

const profile = await mkdtemp(join(tmpdir(), "agent-desktop-git-submission-dialog-"));
let exitCode = -1;
try {
  await writeFile(join(output, "main.cjs"), String.raw`
const {app,BrowserWindow}=require("electron"),fs=require("node:fs"),path=require("node:path");
const output=process.argv[2],profile=process.argv[3],sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));app.setPath("userData",profile);
app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,width:900,height:640,webPreferences:{sandbox:true,contextIsolation:false,nodeIntegration:false,backgroundThrottling:false}});
 const js=source=>win.webContents.executeJavaScript(source,true),state=()=>js("gitSubmissionState()"),steps=[];
 const assert=(value,message)=>{if(!value)throw Error(message)},wait=async predicate=>{for(let i=0;i<240;i++){if(await js(predicate))return;await sleep(25)}throw Error("Timed out: "+predicate)};
 const observe=async name=>steps.push({name,state:await state()});
 const click=async(selector,text)=>{const point=await js("gitSubmissionTarget("+JSON.stringify(selector)+","+JSON.stringify(text)+")");for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...point,...(type==="mouseMove"?{}:{button:"left",clickCount:1})});await sleep(80)};
 const key=async(keyCode,modifiers=[])=>{win.webContents.focus();for(const type of ["keyDown",...(keyCode==="Enter"&&!modifiers.length?["char"]:[]),"keyUp"])win.webContents.sendInputEvent({type,keyCode:type==="char"?"\r":keyCode,modifiers});await sleep(80)};
 const open=async(expectedBranch="main")=>{await click("#submission-trigger");await wait("gitSubmissionState().open&&gitSubmissionState().activeLabel==='Commit to'");await wait("gitSubmissionState().branchText==="+JSON.stringify(expectedBranch)+"&&!document.querySelector('.git-submission-totals .spinner')")};
 const close=()=>wait("!gitSubmissionState().open");
 try{
  await win.loadFile(path.join(output,"web/index.html"));await wait("Boolean(document.querySelector('#submission-trigger'))");
  await open();let current=await state();assert(Math.abs(current.dialog.width-420)<0.75,"Dialog width is not 420px");assert(current.dialog.width<=current.viewport.width*.92+0.75,"Dialog exceeded 92vw cap");assert(current.activeLabel==="Commit to"&&current.activeText==="main","Resolved branch target was not first focus");await observe("branch-first-focus-420-width");
  win.setContentSize(360,640);await wait("gitSubmissionState().viewport.width===360");current=await state();assert(current.dialog.width<=current.viewport.width*.92+0.75,"Dialog exceeded 92vw at a narrow viewport");assert(current.dialog.left>=-0.75&&current.dialog.right<=current.viewport.width+0.75,"Capped dialog overflowed the viewport");await observe("narrow-viewport-92vw-cap");win.setContentSize(900,640);await wait("gitSubmissionState().viewport.width===900");
  await key("Escape");await close();current=await state();assert(current.activeId==="submission-trigger","Production dialog did not restore invoking focus");assert(current.commands===0&&current.submissions.length===0,"Opening or Escape dispatched a mutation");await observe("escape-no-mutation-production-focus");
  await open();await click('[aria-label="Commit to"]');await wait("Boolean(document.querySelector('.branch-selector-menu'))");await click('[role="menuitemradio"]',"main");assert((await state()).commands===0,"Selecting current destination dispatched a workspace command");
  await click('[aria-label="Commit to"]');await wait("Boolean(document.querySelector('.branch-selector-menu'))");await click('[role="menuitemradio"]',"New branch");await wait("gitSubmissionState().newBranch!==null&&gitSubmissionState().activeLabel==='Branch name'");current=await state();assert(current.commands===0&&current.submissions.length===0,"Selecting New branch dispatched before submission");await observe("deferred-current-new-branch-input-focus");
  await key("Escape");await close();await open();await js("document.querySelector('.git-submission-message').focus()");await win.webContents.insertText("first line");await key("Enter");await win.webContents.insertText("second line");current=await state();assert(current.message==="first line\nsecond line","Plain Enter did not remain a textarea newline");assert(current.submissions.length===0,"Plain Enter submitted Git action");await observe("textarea-enter-newline");
  await js("document.querySelector('[cmdk-item][aria-selected=true]').focus()");await key("Up");current=await state();assert(current.selected.at(-1).selected==="true","ArrowUp did not loop from Commit to Push");await key("Down");assert((await state()).selected[0].selected==="true","ArrowDown did not loop from Push to Commit");await observe("command-arrow-loop");
  await js("gitSubmissionControl('compositionstart');gitSubmissionControl('redraw')");await key("Enter",["meta"]);assert((await state()).submissions.length===0,"IME composition submitted after redraw");await js("gitSubmissionControl('compositionend')");await key("Down");await key("Enter",["meta"]);current=await state();assert(current.submissions.length===1&&current.submissions[0].operation==="commit-and-push","Meta+Enter did not submit the selected action exactly once");await key("Enter",["meta"]);assert((await state()).submissions.length===1,"Submission guard allowed a duplicate action");await observe("ime-fence-and-selected-meta-enter-once");
  await key("Escape");await close();await open();await click(".git-submission-selection input");await js("document.querySelector('.git-submission-message').focus();document.querySelector('.git-submission-message').select()");await win.webContents.insertText("Persisted draft");await key("Escape");await close();await open();current=await state();assert(current.include===false&&current.message==="Persisted draft","Workspace draft or Include unstaged choice did not survive reopen");await observe("owner-draft-preserved-across-reopen");
  await js("gitSubmissionControl('mismatch')");await wait("gitSubmissionState().statusRevision==='status-r1'&&gitSubmissionState().contextRevision==='context-r2'&&!document.querySelector('.git-submission-totals .spinner')");current=await state();const mismatchCommit=current.selected.find(item=>item.text.startsWith("Commit⌘")||item.text==="Commit⌘⏎");assert(current.branchText==="main","Delayed status query changed the displayed branch before release");assert(mismatchCommit?.disabled==="true","Action remained enabled while displayed status main lagged action context feature/context");await js("document.querySelector('.git-submission-message').focus()");await key("Enter",["meta"]);assert((await state()).submissions.length===1,"Mismatched displayed status and action context dispatched a Git submission");await observe("mismatched-display-context-blocks-action");
  await js("gitSubmissionControl('match')");await wait("gitSubmissionState().statusRevision==='status-r2'&&gitSubmissionState().branchText==='feature/context'");current=await state();const matchingCommit=current.selected.find(item=>item.text.startsWith("Commit⌘")||item.text==="Commit⌘⏎");assert(matchingCommit?.disabled!=="true","Action remained disabled after displayed status caught up to action context");await click("[cmdk-item]","Commit⌘");current=await state();assert(current.submissions.length===2&&current.submissions[1].contextRevision==="context-r2","Matching displayed status did not submit context B revision exactly once");await click("[cmdk-item]","Commit⌘");assert((await state()).submissions.length===2,"Matching status/context submission dispatched more than once");await observe("matching-status-context-submits-b-revision-once");
  await key("Escape");await close();await js("gitSubmissionControl('delay-staged-summary')");await click("#submission-trigger");await wait("gitSubmissionState().open&&gitSubmissionState().branchText==='feature/context'&&Boolean(document.querySelector('.git-submission-totals .spinner'))");await click(".git-submission-selection input");await wait("gitSubmissionState().include===true&&gitSubmissionState().totalsLabel==='2 additions, 1 deletions'");await js("gitSubmissionControl('release-summary')");await sleep(150);current=await state();assert(current.totalsLabel==="2 additions, 1 deletions"&&!current.text.includes("+99")&&!current.text.includes("−98"),"Late staged summary replaced the current Include unstaged summary");await observe("late-old-mode-summary-ignored-after-toggle");
  await key("Escape");await close();await js("gitSubmissionControl('zero-summary')");await open("feature/context");current=await state();let commit=current.selected.find(item=>item.text.startsWith("Commit⌘")||item.text==="Commit⌘⏎");assert(current.totalsLabel==="0 additions, 0 deletions"&&commit?.disabled==="true"&&commit.reason==="No changes to commit.","An exact zero-file prepared summary did not disable Commit as No changes");await js("document.querySelector('.git-submission-message').focus()");await key("Enter",["meta"]);assert((await state()).submissions.length===2,"Zero-file prepared selection dispatched a Git submission");await observe("zero-selected-files-disables-commit");
  await key("Escape");await close();await js("gitSubmissionControl('fail-summary')");await open("feature/context");current=await state();commit=current.selected.find(item=>item.text.startsWith("Commit⌘")||item.text==="Commit⌘⏎");assert(current.totalsLabel==="Change totals unavailable"&&current.text.includes("Controlled selection summary unavailable")&&commit?.disabled==="true","Selection summary failure was shown as a usable or zero-total selection");await js("document.querySelector('.git-submission-message').focus()");await key("Enter",["meta"]);assert((await state()).submissions.length===2,"Failed selection summary dispatched a Git submission");await observe("summary-failure-visible-and-blocking");
  await js("gitSubmissionControl('partial')");await wait("gitSubmissionState().partialSurface");current=await state();assert(current.text.includes("222222222222")&&current.text.includes("origin/main: push confirmed · upstream failed"),"Partial receipt surface omitted the completed commit SHA or confirmed remote/upstream-failed state");await observe("push-partial-receipt-visible");
  fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:true,hidden:true,electron:process.versions.electron,input:"Electron sendInputEvent pointer/keyboard and insertText; synthetic CompositionEvent only for explicit IME state",steps},null,2));
 }catch(error){fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:false,error:String(error.stack||error),state:await state().catch(()=>null),steps},null,2));process.exitCode=1}finally{await win.close();app.quit()}
});`);
  const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs"), output, profile], { cwd: profile, stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")), env: { HOME: profile, TMPDIR: profile, PATH: "/usr/bin:/bin" } });
  const timer = setTimeout(() => electron.kill("SIGTERM"), 60_000);
  try { exitCode = await electron.exited; } finally { clearTimeout(timer); }
} finally { await rm(profile, { recursive:true, force:true }); }
let result: Record<string, unknown>;
try { result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); }
catch (cause) { result = { passed:false, resultReadError:cause instanceof Error ? cause.message : String(cause) }; }
result.exitCode=exitCode;result.sourceAtBuild=sourceAtBuild;result.sourceAfterRun=await hashes();result.sourceHashesStable=JSON.stringify(result.sourceAtBuild)===JSON.stringify(result.sourceAfterRun);
result.scope="Actual production GitSubmissionDialog, BranchSelector, Icons, CSS and WorkspaceState in hidden isolated Electron with controlled read-only bridge/cache. It verifies renderer behavior and Chromium geometry, not Git/provider execution, full App routing, visible/native-window pixels or reference parity.";
result.passed=result.passed===true&&exitCode===0&&result.sourceHashesStable;
await writeFile(join(output,"result.json"),JSON.stringify(result,null,2));
if(!result.passed)throw new Error(`Git submission dialog acceptance failed; inspect ${join(output,"result.json")}`);
console.log(JSON.stringify({passed:true,output}));
