import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { build } from "vite";

const repo = resolve(import.meta.dir, "../..");
const output = resolve(process.argv[2] ?? `.data/header-panel-context-menu-${Date.now()}`);
if (existsSync(output) && (await readdir(output)).length) throw new Error(`Output must be empty: ${output}`);
await mkdir(output, { recursive: true, mode: 0o700 });
const sources = [
  "apps/desktop/src/renderer/App.tsx", "apps/desktop/src/renderer/use-header-context-menu.ts", "apps/desktop/src/renderer/GeneralSettings.tsx", "apps/desktop/src/renderer/preferences-state.ts",
  "apps/desktop/src/renderer/use-workbench-dock.tsx", "apps/desktop/src/renderer/dock-state.ts", "apps/desktop/src/renderer/styles.css",
  "apps/desktop/src/main/native-context-menu.ts", "apps/desktop/src/main/preload.ts", "packages/shared/src/context-menu.ts",
  "packages/shared/src/preferences.ts", "packages/shared/src/protocol.ts", "scripts/acceptance/app-dock-browser.tsx",
  "scripts/acceptance/header-panel-menu.ts", "scripts/acceptance/header-panel-menu-browser.tsx",
];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(repo, path))).digest("hex")])));
const before = await hashes();
await writeFile(join(output, "source-before.json"), JSON.stringify(before, null, 2));
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "header-panel-menu-browser.tsx"))}"></script>`);
await writeFile(join(output, "tsconfig.fixture.json"), JSON.stringify({ extends: join(repo, "tsconfig.json"), compilerOptions: { paths: { "@agent-desktop/shared": [join(repo, "packages/shared/src/protocol.ts")] } }, include: [join(repo, "scripts/acceptance/header-panel-menu-browser.tsx")] }, null, 2));
const check = Bun.spawn([process.execPath, join(repo, "node_modules/typescript/bin/tsc"), "-p", join(output, "tsconfig.fixture.json"), "--pretty", "false"], { stdout: Bun.file(join(output, "strict.log")), stderr: Bun.file(join(output, "strict-errors.log")) });
const strictExit = await check.exited;
if (strictExit) throw new Error(`Strict fixture compile failed (${strictExit}); inspect ${join(output, "strict-errors.log")}`);
await build({ configFile: join(repo, "apps/desktop/vite.config.ts"), root: output, logLevel: "warn", worker: { format: "es" }, build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });

const profile = await mkdtemp(join(tmpdir(), "agent-desktop-header-panel-menu-"));
let exitCode = -1;
try {
  await writeFile(join(output, "main.cjs"), String.raw`
const{app,BrowserWindow}=require("electron"),fs=require("node:fs"),path=require("node:path");const output=process.argv[2];app.setPath("userData",process.argv[3]);
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),steps=[];const js=s=>win.webContents.executeJavaScript(s,true),state=()=>js("headerPanelMenuState()"),sleep=ms=>new Promise(r=>setTimeout(r,ms));const assert=(v,m)=>{if(!v)throw Error(m)},wait=async s=>{for(let i=0;i<720;i++){if(await js(s))return;await sleep(25)}throw Error("Timed out: "+s)};const point=async(selector,text)=>js("(()=>{const e=[...document.querySelectorAll("+JSON.stringify(selector)+")].find(e=>e.getClientRects().length&&!e.disabled&&"+(text===undefined?"true":"e.textContent.trim().startsWith("+JSON.stringify(text)+")")+");if(!e)throw Error('Missing target '+"+JSON.stringify(selector)+");const b=e.getBoundingClientRect();return{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}})()");const mouse=async(selector,button="left",text)=>{const p=await point(selector,text);for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...p,...(type==="mouseMove"?{}:{button,clickCount:1})});await sleep(60)};const observe=async name=>steps.push({name,state:await state()});const settings=async()=>{await mouse(".profile-trigger");await mouse("[role=menuitem]","left","Settings");await wait("Boolean(document.querySelector('.general-settings'))")};const back=async()=>{await mouse(".settings-sidebar-back");await wait("!document.querySelector('.settings-sidebar')")};
try{win.webContents.on("console-message",(_e,_level,message)=>fs.appendFileSync(path.join(output,"renderer.log"),message+"\n"));await win.loadFile(path.join(output,"web/index.html"));await wait("Boolean(document.querySelector('.main-header')&&document.querySelector('.profile-trigger'))");win.webContents.focus();
await settings();await mouse(".general-segmented button","left","Right");await wait("headerPanelMenuState().then(s=>s.terminalLocation==='Right')");await back();let baseline=await state(),baselineCommands=baseline.preferenceCommands.length,beforeDock=JSON.stringify(baseline.dock);assert(baseline.bottomLauncher,"Bottom launcher was not enabled by default");
await mouse(".main-header","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===1)");let s=await state(),item=s.menuCalls[0].items[0];assert(s.menuCalls[0].items.length===1&&item.id==='toggle-bottom-panel-launcher'&&item.label==='Bottom panel'&&item.type==='checkbox'&&item.checked===true&&item.enabled===true,"Default header descriptor is not the enabled checked Bottom panel item");await js("headerPanelMenuControl('resolve-menu',null)");await sleep(80);assert((await state()).preferenceCommands.length===baselineCommands,"Dismissing header menu dispatched a preference command");await observe("dismiss-does-not-dispatch");
await js("headerPanelMenuControl('hold-next-preference')");await mouse(".main-header","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===2)");await js("headerPanelMenuControl('resolve-menu','toggle-bottom-panel-launcher')");await wait("headerPanelMenuState().then(s=>s.pendingPreference)");await mouse(".main-header","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===3)");s=await state();item=s.menuCalls[2].items[0];assert(item.checked===true&&item.enabled===false,"Pending preference did not disable the current checked menu item");await js("headerPanelMenuControl('resolve-menu','toggle-bottom-panel-launcher')");await sleep(80);assert((await state()).preferenceCommands.length===baselineCommands+1,"Disabled pending menu result dispatched a second command");await js("headerPanelMenuControl('release-preference')");await wait("headerPanelMenuState().then(s=>!s.pendingPreference&&!s.bottomLauncher)");s=await state();assert(JSON.stringify(s.dock)===beforeDock,"Hiding launcher changed existing dock tabs or open state");const records=s.preferences.records;assert(records.some(r=>r.key==='general.bottomPanel'&&r.value===false)&&records.some(r=>r.key==='general.defaultTerminalLocation'&&r.value==='right'),"Off receipt or stored terminal location was not preserved");await observe("pending-disabled-and-off-preserves-dock-choice");
await settings();await wait("headerPanelMenuState().then(s=>s.bottomSetting==='false')");s=await state();assert(s.preferences.records.some(r=>r.key==='general.defaultTerminalLocation'&&r.value==='right'),"Settings did not retain the hidden stored terminal location");await observe("settings-agrees-with-menu-off");await back();
await mouse(".header-panel-actions","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===4)");await settings();await wait("headerPanelMenuState().then(s=>s.settingsOpen)");await back();await js("headerPanelMenuControl('resolve-menu','toggle-bottom-panel-launcher')");await sleep(100);s=await state();assert(!s.bottomLauncher&&s.preferenceCommands.length===baselineCommands+1,"A menu choice resolved after Settings navigation changed the preference");await observe("stale-held-choice-after-navigation-ignored");
await mouse(".header-panel-actions","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===5)");s=await state();item=s.menuCalls[4].items[0];assert(item.checked===false&&item.enabled===true&&s.sideLauncher,"Hidden bottom launcher left no enabled side-trigger menu");await js("headerPanelMenuControl('resolve-menu','toggle-bottom-panel-launcher')");await wait("headerPanelMenuState().then(s=>s.bottomLauncher)");await settings();await wait("headerPanelMenuState().then(s=>s.bottomSetting==='true'&&s.terminalLocation==='Right')");await observe("side-trigger-restores-and-settings-agree");await back();
await js("headerPanelMenuControl('set-state-unavailable',true)");await wait("headerPanelMenuState().then(s=>s.text.includes('Offline · cached view'))");const beforeOffline=(await state()).preferenceCommands.length;await mouse(".main-header","right");await wait("headerPanelMenuState().then(s=>s.menuCalls.length===6)");s=await state();item=s.menuCalls[5].items[0];assert(item.checked===true&&item.enabled===false,"Offline header descriptor was not disabled");await js("headerPanelMenuControl('resolve-menu','toggle-bottom-panel-launcher')");await sleep(100);assert((await state()).preferenceCommands.length===beforeOffline,"Offline controlled menu result dispatched a preference write");await observe("offline-disabled-no-dispatch");
fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:true,hidden:true,electron:process.versions.electron,input:"Actual Electron right-button events on the production App header; menu choices are controlled DesktopBridge results, not native OS menu interaction.",steps},null,2));}catch(error){fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:false,error:String(error.stack||error),state:await state().catch(()=>null),steps},null,2));}finally{win.close();app.quit();}});
`);
  const child = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs"), output, profile], { cwd: profile, env: { HOME: profile, PATH: "/usr/bin:/bin", TMPDIR: profile }, stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) });
  const timer = setTimeout(() => child.kill("SIGTERM"), 60_000); try { exitCode = await child.exited; } finally { clearTimeout(timer); }
} finally { await rm(profile, { recursive: true, force: true }); }
let result: Record<string, unknown>; try { result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); } catch (cause) { result = { passed: false, resultReadError: cause instanceof Error ? cause.message : String(cause) }; }
const after = await hashes(); Object.assign(result, { exitCode, strictExit, sourceBefore: before, sourceAfter: after, sourceHashesStable: JSON.stringify(before) === JSON.stringify(after), scope: "Full production App in hidden isolated Electron. Actual header right-button events and production preference state are exercised against a controlled context-menu result; this is not native OS-menu or pixel proof." }); result.passed = result.passed === true && exitCode === 0 && result.sourceHashesStable; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`Header panel context-menu acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
