import {Database} from 'bun:sqlite';
import {PluginAcquisitionRecords} from '../../apps/host/src/integrations/acquisition-records';
import {mkdir,mkdtemp,writeFile,readFile,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import {WorkerRuntime} from '../../apps/host/src/omp-workers/runtime';
import {IntegrationsHttp} from '../../apps/host/src/integrations-http';
import {getMCPConfigPath} from '@oh-my-pi/pi-utils';
const pluginDetailOnly=process.argv.includes('--plugin-detail-only');
const repo=resolve(import.meta.dir,'../..'),output=resolve(process.argv[2]??`.data/integrations-ui-${Date.now()}`);
await mkdir(output,{recursive:true});if((await readdir(output)).length)throw new Error('Acceptance output must be empty.');
const root=await mkdtemp(join(tmpdir(),'agent-desktop-integrations-ui-')),agentDir=join(root,'agent'),cwd=join(root,'project'),plugins=join(root,'.omp/plugins');
await Promise.all([agentDir,join(cwd,'.omp'),join(plugins,'node_modules','fixture-plugin')].map(p=>mkdir(p,{recursive:true})));
await writeFile(join(agentDir,'config.yml'),'extensions: []\n');
const json=(x:unknown)=>JSON.stringify(x,null,2)+'\n';
await writeFile(join(plugins,'package.json'),json({name:'omp-plugins',private:true,dependencies:{'fixture-plugin':'1.0.0'}}));
await writeFile(join(plugins,'omp-plugins.lock.json'),json({plugins:{'fixture-plugin':{version:'1.0.0',enabled:true,enabledFeatures:null}},settings:{'fixture-plugin':{token:'initial-private-value'}}}));
await writeFile(join(plugins,'node_modules','fixture-plugin','package.json'),json({name:'fixture-plugin',version:'1.0.0',omp:{name:'Fixture plugin',description:'Native registry configuration fixture',features:{tools:{default:true}},settings:{token:{type:'string',secret:true},mode:{type:'enum',values:['compact','expanded'],default:'compact'}}}}));
await writeFile(join(agentDir,'mcp.json'),json({mcpServers:{'disabled-fixture':{command:'/bin/false',enabled:false,args:['original'],env:{OPAQUE:'${TOKEN:-fallback}'},auth:{token:'synthetic-private-auth'},oauth:{clientId:'synthetic-client'},timeout:4321}}}));
const sources=['apps/desktop/src/renderer/NativePluginSummary.tsx','apps/desktop/src/renderer/native-plugin-summary.css','apps/desktop/src/main/main.ts','apps/desktop/src/main/preload.ts','apps/host/src/omp-workers/protocol.ts','packages/shared/src/protocol.ts','apps/desktop/src/renderer/NativeIntegrations.tsx','apps/desktop/src/renderer/McpServerForm.tsx','apps/desktop/src/renderer/mcp-server-form.ts','apps/desktop/src/renderer/native-integrations.css','apps/host/src/integrations/mcp.ts','apps/host/src/integrations/plugins.ts','apps/host/src/integrations-http.ts','apps/host/src/omp-workers/entry.ts','apps/host/src/omp-workers/runtime.ts','packages/shared/src/integrations.ts','scripts/acceptance/integrations.ts','scripts/acceptance/integrations-browser.tsx','scripts/acceptance/integrations-electron.cjs','apps/desktop/src/renderer/SettingsSidebar.tsx','apps/desktop/src/renderer/settings-sidebar.css','apps/desktop/src/renderer/styles.css','apps/desktop/src/renderer/theme.css','apps/desktop/src/renderer/Icons.tsx'];
const hashes=async()=>Object.fromEntries(await Promise.all(sources.map(async file=>[file,createHash('sha256').update(await readFile(join(repo,file))).digest('hex')])));
const runtime=new WorkerRuntime({agentDir,workerPath:join(repo,'apps/host/src/omp-workers/fixtures/no-provider-worker.ts'),environment:{HOME:root,PATH:process.env.PATH,TMPDIR:tmpdir(),PI_CODING_AGENT_DIR:agentDir,TERM:'dumb'}});
const receiptsDb=new Database(join(root,'receipts.sqlite'));receiptsDb.exec('CREATE TABLE metadata(key TEXT PRIMARY KEY,data TEXT NOT NULL)');const receipts=new PluginAcquisitionRecords(receiptsDb);
const service=new IntegrationsHttp({runtime,resolveCwd:target=>{if(target&&'projectId'in target&&target.projectId==='fixture')return cwd;throw new Error('Unknown fixture target');},changed:()=>{}});
const capability=crypto.randomUUID(),observed:string[]=[],delayed=Promise.withResolvers<void>();let delayedHeld=false;
const cors={'Access-Control-Allow-Origin':'null','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'content-type'};
const proxy=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){const url=new URL(request.url);if(!url.pathname.startsWith('/'+capability+'/'))return new Response(null,{status:404});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const route=url.pathname.slice(capability.length+1);if(route==='/test/delay-state')return Response.json({held:delayedHeld},{headers:cors});if(route==='/test/release'){delayed.resolve();return Response.json({released:true},{headers:cors});}if(route==='/test/external-edit'){const file=join(agentDir,'mcp.json'),value=JSON.parse(await readFile(file,'utf8'));value.externalWriter='preserve-me';await writeFile(file,json(value));return Response.json({changed:true},{headers:cors});}if(route==='/acquisition/operations'){observed.push(route);return Response.json(receipts.list(),{headers:cors});}if(route==='/acquisition/catalog'){const input=await request.json();if(input?.target?.projectId!=='fixture')return new Response(null,{status:400});observed.push(route);return Response.json(await runtime.getMarketplaceCatalog(cwd),{headers:cors});}if(!/^\/(plugins|mcp)\/(read|detail|mutate)$/.test(route))return new Response(null,{status:403});observed.push(route);const input=route==='/mcp/mutate'?await request.clone().json().catch(()=>null):null;const target=new URL('http://fixture/v1/integrations'+route);const result=await service.route(new Request(target,request),target);if(input?.mutation?.operation==='add'&&input.mutation.name==='ui-sse'){delayedHeld=true;await delayed.promise;}return new Response(await result!.arrayBuffer(),{status:result!.status,headers:{...cors,'Content-Type':'application/json'}});}});
try{
 const before=await hashes();const catalog=await runtime.getPlugins(cwd);if(catalog.plugins.length!==1)throw new Error('Isolated native plugin was not discovered');
 const entry=join(output,'index.html');await writeFile(entry,`<!doctype html><html><head><meta charset="utf-8"></head><body><div id="root"></div><script type="module" src="${join(repo,'scripts/acceptance/integrations-browser.tsx')}"></script></body></html>`);
 await build({configFile:false,plugins:[react(),tailwindcss()],root:output,base:'./',build:{outDir:join(output,'web'),emptyOutDir:true,rollupOptions:{input:entry}}});
 await writeFile(join(output,'launch.json'),json({endpoint:`http://127.0.0.1:${proxy.port}/${capability}`,profile:join(root,'electron-profile'),pluginDetailOnly}));
 const child=Bun.spawn([process.execPath,join(repo,'node_modules/electron/cli.js'),join(repo,'scripts/acceptance/integrations-electron.cjs'),output],{stdout:Bun.file(join(output,'electron.log')),stderr:Bun.file(join(output,'electron-errors.log'))});
 const code=await child.exited,result=await Bun.file(join(output,'result.json')).json();
 const readJson=async(file:string)=>JSON.parse(await readFile(file,'utf8').catch(error=>{if((error as NodeJS.ErrnoException).code==='ENOENT')return 'null';throw error;}));
 const stored=JSON.parse(await readFile(join(plugins,'omp-plugins.lock.json'),'utf8')),mcp=await readJson(join(agentDir,'mcp.json')),projectMcp=await readJson(getMCPConfigPath('project',cwd));
 const after=await hashes();Object.assign(result,{sourceAtBuild:before,sourceAfterBuild:after,sourceHashesStable:JSON.stringify(before)===JSON.stringify(after),hostEvidence:{secretSaved:stored.settings['fixture-plugin'].token==='UI_REPLACEMENT',mode:stored.settings['fixture-plugin'].mode,pluginEnabled:stored.plugins['fixture-plugin'].enabled,userMcp:mcp?.mcpServers??null,projectMcp:projectMcp?.mcpServers??null,mutations:observed.filter(x=>x.endsWith('/mutate')).length},scope:'Production settings components in hidden sandboxed Electron with real profile-isolated OMP discovery workers and exact raw native user/project MCP configuration readback. Scoped HTTP bridge bypasses desktop main IPC. Docs is a recorded no-op. No sessions, prompts, MCP connections, providers, packaged/native-window, or pixel-parity claim.'});
 const user=mcp?.mcpServers??{},project=projectMcp?.mcpServers??{};
 const stdio=user['ui-stdio'],http=user['ui-http'],sse=project['ui-sse'];
 result.passed&&=code===0&&result.sourceHashesStable&&result.hostEvidence.secretSaved&&result.hostEvidence.mode==='expanded'&&result.hostEvidence.pluginEnabled===true&&result.hostEvidence.mutations===(pluginDetailOnly?4:9)
  &&(pluginDetailOnly || (stdio?.type==='stdio'&&stdio.command==='/bin/false'&&JSON.stringify(stdio.args)===JSON.stringify(['  spaced argument  ','','two words'])&&stdio.env?.LITERAL_SECRET==='  literal value  '&&stdio.env?.PASSTHROUGH==='${PASSTHROUGH}'&&stdio.cwd===' /fixture cwd '
  &&http?.type==='http'&&http.url==='https://example.test/mcp'&&http.headers?.['X-Literal']==='  literal header  '&&http.headers?.['X-From-Env']==='${HEADER_VALUE}'&&http.headers?.Authorization==='Bearer ${BEARER_TOKEN}'
  &&user['disabled-fixture']?.args?.[0]==='edited argument'&&user['disabled-fixture']?.type===undefined&&user['disabled-fixture']?.env?.OPAQUE==='${TOKEN:-fallback}'&&user['disabled-fixture']?.auth?.token==='synthetic-private-auth'&&user['disabled-fixture']?.oauth?.clientId==='synthetic-client'&&user['disabled-fixture']?.timeout===4321&&mcp.externalWriter==='preserve-me'
  &&sse?.type==='sse'&&sse.url==='https://example.test/events'));
 if(pluginDetailOnly)result.scope='Production plugin detail in hidden sandboxed Electron with actual isolated native OMP worker. Four configuration mutations: disable, enable, secret and enum. No main/preload, native OS-window or matched pixel acceptance; no sessions/prompts/provider/MCP connections.';
 await writeFile(join(output,'result.json'),json(result));console.log(JSON.stringify({passed:result.passed,result:join(output,'result.json')}));if(!result.passed)throw new Error('Integration UI acceptance failed');
}finally{proxy.stop();await service.dispose();await runtime.dispose();receiptsDb.close();await rm(root,{recursive:true,force:true});await rm(join(output,'launch.json'),{force:true});}
