import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, relative } from "node:path";
import { build } from "vite";

const root = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? `.data/review-ui-acceptance/${Date.now()}`), profile = await mkdtemp(join(tmpdir(), "agent-review-ui-"));
const sources = ["apps/desktop/src/renderer/ReviewPanel.tsx", "apps/desktop/src/renderer/ReviewDiff.tsx", "apps/desktop/src/renderer/review-model.ts", "apps/desktop/src/renderer/review-theme.ts", "apps/desktop/src/renderer/review-worker.ts", "apps/desktop/src/renderer/review-panel.css", "scripts/acceptance/review-ui-browser.tsx"];
const hashes = () => Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(root, path))).digest("hex")])).then(Object.fromEntries);
await mkdir(output, { recursive: true, mode: 0o700 }); const before = await hashes();
try {
  await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'none'"><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "review-ui-browser.tsx"))}"></script>`);
  await build({ configFile: join(root, "apps/desktop/vite.config.ts"), root: output, logLevel: "warn", build: { outDir: join(output, "web"), emptyOutDir: true, rollupOptions: { input: join(output, "index.html") } } });
  await writeFile(join(output, "main.cjs"), `const {app,BrowserWindow}=require('electron');const fs=require('node:fs');const path=require('node:path');app.setPath('userData',${JSON.stringify(profile)});app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1200,height:900,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});try{await win.loadFile(path.join(__dirname,'web/index.html'));const result=await win.webContents.executeJavaScript('runReviewUIAcceptance()');result.captures=[];for(const scene of [{name:'wide',width:1200,height:900,zoom:1},{name:'narrow',width:720,height:900,zoom:1},{name:'zoom150',width:1200,height:900,zoom:1.5}]){win.setContentSize(scene.width,scene.height);win.webContents.setZoomFactor(scene.zoom);const geometry=await win.webContents.executeJavaScript('reviewUIGeometry()');fs.writeFileSync(path.join(__dirname,scene.name+'.png'),(await win.webContents.capturePage()).toPNG());result.captures.push({...scene,...geometry});}result.hidden=true;result.electron=process.versions.electron;result.passed&&=result.captures.every(scene=>scene.fitting);fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify(result,null,2));win.destroy();app.exit(result.passed?0:1)}catch(error){const progress=await win.webContents.executeJavaScript('reviewUIProgress()').catch(()=>null);fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({passed:false,error:String(error),progress},null,2));app.exit(1)}});`);
  const child = Bun.spawn([process.execPath, join(root, "node_modules/electron/cli.js"), join(output, "main.cjs")], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) }); const timer = setTimeout(() => child.kill("SIGTERM"), 60_000); const code = await child.exited; clearTimeout(timer);
  const result = await Bun.file(join(output, "result.json")).json(); result.sourceAtBuild = before; result.sourceAfter = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceAtBuild) === JSON.stringify(result.sourceAfter); result.passed &&= result.sourceHashesStable; result.scope = "Actual ReviewPanel and Pierre renderer in hidden sandboxed Electron with controlled WorkspaceState only; no provider, native host, installed app, or credential operation."; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); console.log(JSON.stringify({ passed: result.passed, checks: result.checks?.length, result: join(output, "result.json") })); if (code || !result.passed) throw new Error(`Review UI acceptance failed; inspect ${output}/result.json`);
} finally { await rm(profile, { recursive: true, force: true }); }
