import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { build } from "vite";

const repo = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? ".data/sidebar-capability-correction-2026-09-08/controlled");
const sources = [
  "apps/desktop/src/renderer/ThemeSettings.tsx", "apps/desktop/src/renderer/theme-state.ts", "apps/desktop/src/renderer/preferences-state.ts", "apps/desktop/src/renderer/theme-image-state.ts", "apps/desktop/src/renderer/NativeSwitch.tsx", "apps/desktop/src/renderer/native-switch.css", "apps/desktop/src/renderer/styles.css", "apps/desktop/src/renderer/theme.css", "apps/desktop/src/renderer/App.tsx", "apps/desktop/src/main/preload.ts", "packages/shared/src/theme.ts", "packages/shared/src/preferences.ts", "packages/shared/src/protocol.ts", "scripts/acceptance/sidebar-capability.ts", "scripts/acceptance/sidebar-capability-browser.tsx",
];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async file => [file, createHash("sha256").update(await readFile(join(repo, file))).digest("hex")])));
await mkdir(output, { recursive: true, mode: 0o700 }); if ((await readdir(output)).length) throw new Error("Output must be empty");
const sourceAtBuild = await hashes();
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;min-height:100%}.controlled-sidebar-capability{width:100%;height:100vh}.controlled-sidebar-capability .theme-settings{width:100%;height:100%}</style><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "sidebar-capability-browser.tsx"))}"></script>`);
await build({ configFile: false, logLevel: "warn", root: output, plugins: [react(), tailwindcss()], base: "./", build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });
const profile = join(output, "profile");
const main = String.raw`const {app,BrowserWindow}=require("electron"),fs=require("node:fs"),path=require("node:path");
const output=__dirname;app.setPath("userData",${JSON.stringify(profile)});app.commandLine.appendSwitch("disable-renderer-backgrounding");
app.whenReady().then(async()=>{const win=new BrowserWindow({width:1440,height:1000,show:false,useContentSize:true,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),checks=[],captures=[],consoleMessages=[],rendererGone=[];
win.webContents.on("console-message",(...args)=>consoleMessages.push(args.slice(1).map(String).join(" | ")));win.webContents.on("render-process-gone",(_event,details)=>rendererGone.push(details));
const js=source=>win.webContents.executeJavaScript(source),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));const wait=async source=>{for(let i=0;i<600;i++){if(await js(source))return;await sleep(25)}throw new Error("Condition failed: "+source)};
const click=async(selector,label,index=0)=>{const point=await js("window.target("+JSON.stringify(selector)+","+JSON.stringify(label)+","+index+")");for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...point,...(type==="mouseMove"?{}:{button:"left",clickCount:1})});await sleep(120)};
const key=async keyCode=>{win.webContents.sendInputEvent({type:"keyDown",keyCode});win.webContents.sendInputEvent({type:"keyUp",keyCode});await sleep(120)};const character=async value=>{win.webContents.sendInputEvent({type:"keyDown",keyCode:value.toUpperCase()});win.webContents.sendInputEvent({type:"char",keyCode:value});win.webContents.sendInputEvent({type:"keyUp",keyCode:value.toUpperCase()});await sleep(120)};
const capture=async name=>{await sleep(100);const image=await win.webContents.capturePage();fs.writeFileSync(path.join(output,name+".png"),image.toPNG());fs.writeFileSync(path.join(output,name+".ax.json"),JSON.stringify(await win.webContents.debugger.sendCommand("Accessibility.getFullAXTree"),null,2));captures.push({name,raster:image.getSize(),contentBounds:win.getContentBounds(),windowBounds:win.getBounds(),zoomFactor:win.webContents.getZoomFactor(),state:await js("window.state()")})};
let step="load";try{win.webContents.debugger.attach("1.3");await win.loadFile(path.join(output,"web/index.html"));win.webContents.focus();await wait("window.state?.().current&&!window.state().loading");let state=await js("window.state()");
if(state.switch.checked!=="true"||!state.switch.disabled||!state.material.disabled||state.material.value!=="sidebar"||!state.notice||state.dirty||state.saves.length||state.calls.includes("theme.set"))throw new Error("Unsupported capability state differs: "+JSON.stringify(state));await capture("01-unsupported-saved-request");checks.push("With backdrop support absent, production ThemeSettings shows the saved translucency request as checked while disabling both its switch and material selector; mounting and pointer observation do not edit or save it");
step="supported-fallback";await js("window.capability(true)");await wait("window.state().supported&&window.state().fallback&&!window.state().material.disabled");state=await js("window.state()");if(state.switch.checked!=="true"||state.switch.disabled||state.material.value!=="sidebar"||state.dirty||state.saves.length)throw new Error("Supported fallback state differs: "+JSON.stringify(state));await capture("02-supported-effective-fallback");checks.push("When support is present, the saved translucency request remains actionable even while the controlled effective-window fallback message is visible");
step="preview-only";await click('[role="switch"][aria-label="Translucent sidebar"]',"Translucent sidebar");await wait("window.state().switch.checked==='false'&&window.state().material.disabled&&window.state().dirty");state=await js("window.state()");if(state.draft.opaqueWindows!==true||state.preview.opaqueWindows!==true||state.current.document.opaqueWindows!==false||state.draft.material!=="sidebar"||state.preview.material!=="sidebar"||state.current.document.material!=="sidebar"||state.saves.length)throw new Error("Opaque preview changed saved theme: "+JSON.stringify(state));await capture("03-unsaved-preview");checks.push("Real pointer changes the supported translucency request; ThemeEditor draft and preview become opaque while the current saved theme and controlled save log remain untouched, and the material selector disables for that opaque preview");
step="explicit-save";await click("button","Save theme");await wait("window.state().saves.length===1&&!window.state().dirty&&!window.state().saving");state=await js("window.state()");if(state.saves[0].expectedRevision!=="theme-1"||state.saves[0].document.material!=="sidebar"||state.saves[0].document.opaqueWindows!==true||state.current.revision!=="theme-2"||state.calls.filter(item=>item==="theme.set").length!==1||state.calls.includes("preferences.command")||state.calls.includes("import")||state.calls.includes("open-file")||state.runtimeErrors.length||rendererGone.length)throw new Error("Explicit save result differs: "+JSON.stringify({state,rendererGone}));await capture("04-explicit-save");checks.push("Only real pointer activation of Save theme writes the controlled storage once with the original revision and exact previewed native fields; no preference, provider, file, host or personal storage action occurs");
const geometry={viewport:state.viewport,contentBounds:win.getContentBounds(),windowBounds:win.getBounds(),zoomFactor:win.webContents.getZoomFactor(),captureRasters:captures.map(item=>({name:item.name,...item.raster}))};fs.writeFileSync(path.join(output,"geometry.json"),JSON.stringify(geometry,null,2));fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:true,checks,captures,geometry,finalState:state,consoleMessages,rendererGone,hidden:true,controlledBridges:true,expectedOldBehavior:"The old always-enabled native controls are expected to fail the unsupported disabled-state assertion; no identical old-source run was performed.",oldRunNotPerformed:true,agentModelSelfReported:"GPT-6",scope:"Actual ThemeSettings, ThemeEditor, PreferencesState and ThemeImageState in hidden Electron. Capability, effective-window fallback and persistence are controlled at the fixture boundary; no full App, installed/native-window pixel parity, host, provider, personal storage, Work, native UI or OS integration claim."},null,2));app.exit(0)}catch(error){await capture("failure").catch(()=>{});fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:false,step,error:String(error),checks,captures,state:await js("window.state()").catch(()=>null),consoleMessages,rendererGone},null,2));app.exit(1)}});`;
await writeFile(join(output, "main.cjs"), main);
const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs")], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) });
const timer = setTimeout(() => electron.kill("SIGTERM"), 90_000), code = await electron.exited; clearTimeout(timer);
const result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); result.sourceAtBuild = sourceAtBuild; result.sourceAfterRun = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceAtBuild) === JSON.stringify(result.sourceAfterRun); result.passed &&= code === 0 && result.sourceHashesStable;
await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`Sidebar capability acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
