import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import react from "@vitejs/plugin-react";
import { build } from "vite";

const repo = resolve(import.meta.dir, "../..");
const selectedSource = process.argv[3] ? resolve(process.argv[3]) : undefined;
const selectedBytes = selectedSource ? await readFile(selectedSource,"utf8") : undefined;
const output = resolve(process.argv[2] ?? `.data/ssh-tool-settings-${Date.now()}`);
if (existsSync(output) && (await readdir(output)).length) throw new Error(`Output must be empty: ${output}`);
await mkdir(output, { recursive: true, mode: 0o700 });
const sources = [
  "apps/desktop/src/renderer/SshToolSettings.tsx", "apps/desktop/src/renderer/ssh-tool-settings.css", "apps/desktop/src/renderer/Icons.tsx",
  "apps/desktop/src/renderer/styles.css", "apps/desktop/src/renderer/native-settings.css", "packages/shared/src/ssh-settings.ts", "packages/shared/src/protocol.ts",
  "scripts/acceptance/ssh-tool-settings.ts", "scripts/acceptance/ssh-tool-settings-browser.tsx",
];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async path => [path, createHash("sha256").update(await readFile(join(repo, path))).digest("hex")]))) ;
const before = await hashes();
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;height:100%}main{width:680px;padding:40px}</style><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "ssh-tool-settings-browser.tsx"))}"></script>`);
await writeFile(join(output, "tsconfig.fixture.json"), JSON.stringify({ extends: join(repo, "tsconfig.json"), include: [join(repo, "scripts/acceptance/ssh-tool-settings-browser.tsx"), join(repo, "apps/desktop/src/renderer/SshToolSettings.tsx")] }, null, 2));
const check = Bun.spawn([process.execPath, join(repo, "node_modules/typescript/bin/tsc"), "-p", join(output, "tsconfig.fixture.json"), "--pretty", "false"], { cwd: output, stdout: Bun.file(join(output, "strict.log")), stderr: Bun.file(join(output, "strict-errors.log")), env: { HOME: output, PATH: "/usr/bin:/bin" } });
if (await check.exited !== 0) throw new Error(`Strict fixture compilation failed; inspect ${join(output, "strict-errors.log")}`);
await build({ configFile: false, logLevel: "warn", root: output, plugins: [...(selectedBytes === undefined ? [] : [{name:"selected-ssh-component",enforce:"pre" as const,transform(_code: string,id: string) { return id === join(repo,"apps/desktop/src/renderer/SshToolSettings.tsx") ? {code:selectedBytes,map:null} : null; }}]),react()], base: "./", build: { target: "esnext", outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } });

const profile = await mkdtemp(join(tmpdir(), "agent-desktop-ssh-tool-settings-"));
let exitCode = -1;
try {
  await writeFile(join(output, "main.cjs"), String.raw`
const {app,BrowserWindow}=require("electron"),fs=require("node:fs"),path=require("node:path");
const output=process.argv[2],profile=process.argv[3],sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));app.setPath("userData",profile);
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:900,height:720,webPreferences:{sandbox:true,contextIsolation:false,nodeIntegration:false,backgroundThrottling:false}});const js=source=>win.webContents.executeJavaScript(source,true),state=()=>js("sshToolState()"),steps=[];const assert=(v,m)=>{if(!v)throw Error(m)},wait=async source=>{for(let i=0;i<320;i++){if(await js(source))return;await sleep(25)}throw Error("Timed out: "+source)},observe=async name=>steps.push({name,state:await state()});
const point=async(selector,text)=>js("(()=>{const e=[...document.querySelectorAll("+JSON.stringify(selector)+")].find(e=>e.getClientRects().length&&!e.disabled&&"+(text===undefined?"true":"e.textContent.includes("+JSON.stringify(text)+")")+");if(!e)throw Error('Unavailable target '+"+JSON.stringify(selector)+");const b=e.getBoundingClientRect();return{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}})()");const click=async(selector,text)=>{const p=await point(selector,text);for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...p,...(type==="mouseMove"?{}:{button:"left",clickCount:1})});await sleep(40)};const key=async keyCode=>{win.webContents.sendInputEvent({type:"keyDown",keyCode});win.webContents.sendInputEvent({type:"keyUp",keyCode});await sleep(40)};const set=async(selector,value)=>js("(()=>{const e=document.querySelector("+JSON.stringify(selector)+");const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;s.call(e,"+JSON.stringify(value)+");e.dispatchEvent(new Event('input',{bubbles:true}));})()");
try{await win.loadFile(path.join(output,"web/index.html"));await wait("sshToolState().reads.length===1");let s=await state();assert(s.text.includes("Loading SSH tool targets"),"Late initial read did not remain loading");await js("sshToolControl('release-initial')");await wait("sshToolState().rows.length===2");s=await state();assert(s.text.includes("Read only")&&s.text.includes("Shadowed"),"Scope/source/legacy inventory missing");await observe("catalog-and-readonly-inventory");
await js("sshToolControl('emit-settings','local')");await sleep(80);s=await state();assert(s.reads.length===1,"Foreign local event refreshed the remote owner");await js("sshToolControl('emit-settings','remote')");await wait("sshToolState().reads.length===2");await observe("settings-events-owner-fenced");
await click(".ssh-tool-add");await wait("sshToolState().dialogTitle==='Add SSH target'");s=await state();assert(s.active==="name","Add dialog did not focus the name field");await key("ESC");await wait("!sshToolState().dialog");s=await state();assert(s.active?.includes("Add"),"Escape did not restore the opener focus");await observe("escape-restores-opener");
await click(".ssh-tool-add");await wait("sshToolState().dialog");await js("(()=>{const d=document.querySelector('.ssh-tool-dialog'),b=d.getBoundingClientRect(),x=Math.floor(b.right-3),y=Math.floor(b.bottom-3);window.__inside={x,y};})()");const p=await js("window.__inside");for(const type of ["mouseMove","mouseDown","mouseUp"])win.webContents.sendInputEvent({type,...p,...(type==="mouseMove"?{}:{button:"left",clickCount:1})});await sleep(60);assert((await state()).dialog,"A click on interior dialog padding closed it");await key("ESC");await observe("interior-padding-is-not-backdrop");
await js("sshToolControl('set-connected',false)");await wait("sshToolState().rows.every(row=>row.disabled)");s=await state();assert(s.text.includes("disconnected"),"Offline state not visible");await observe("offline-disables-native-reads");await js("sshToolControl('set-connected',true)");await wait("sshToolState().reads.length===3");
await js("sshToolControl('hold-next-read')");await click("button[aria-label='Reload SSH tool targets']");await wait("sshToolState().reads.length===4&&sshToolState().reads[3].held");await click(".ssh-tool-add");await set("input[name=name]","beta");await set("input[name=host]","beta.invalid");await click(".ssh-tool-dialog .primary-button");await wait("Boolean(sshToolState().pendingMutation)");s=await state();assert(s.mutations.length===1&&s.disabledFields.every(field=>field.disabled),"Pending mutation did not lock every form control");await click(".ssh-tool-dialog .primary-button").catch(()=>{});assert((await state()).mutations.length===1,"Pending mutation replayed");await js("sshToolControl('emit-settings','remote')");await sleep(60);assert((await state()).reads.length===4,"Settings event read was not queued behind mutation");const next={revision:'r2',hosts:[{id:'user:alpha',name:'alpha',scope:'user',source:'/fixture/user.json',shadowed:false,editable:true},{id:'legacy:old',name:'legacy',scope:'user',source:'~/.ssh/config',shadowed:true,editable:false},{id:'project:beta',name:'beta',scope:'project',source:'/fixture/project.json',shadowed:false,editable:true}],warnings:[]};await js("sshToolControl('resolve-mutation',"+JSON.stringify(next)+")");await wait("!sshToolState().dialog&&sshToolState().rows.some(row=>row.text.includes('beta'))&&sshToolState().reads.length===5");const old={revision:'old',hosts:[{id:'user:obsolete',name:'obsolete',scope:'user',source:'/old',shadowed:false,editable:true}],warnings:[]};await js("sshToolControl('release-held-read',"+JSON.stringify(old)+")");await sleep(100);s=await state();assert(s.rows.some(row=>row.text.includes('beta'))&&!s.rows.some(row=>row.text.includes('obsolete')),"Late pre-mutation catalog overwrote the committed result");assert(s.mutations[0].expectedRevision==='r1'&&s.mutations[0].scope==='project',"Add did not carry reviewed revision and project scope");await observe("mutation-serialized-late-read-ignored");
await click(".ssh-tool-row-main","alpha");await wait("sshToolState().dialogTitle==='alpha'&&sshToolState().text.includes('Additional saved fields')");await click(".ssh-tool-dialog .secondary-button","Edit");await wait("sshToolState().dialogTitle==='Edit alpha'");await set("input[name=host]","changed.invalid");const changed={...next,revision:'r3'};await js("sshToolControl('set-catalog-and-emit',"+JSON.stringify(changed)+")");await wait("sshToolState().stale.length===1");s=await state();assert(s.disabledFields.some(field=>field.name==='Save changes'&&field.disabled),"Stale draft remained writable");assert(await js("document.querySelector('input[name=host]').value==='changed.invalid'"),"External update discarded the draft before review");await observe("stale-draft-preserved-requires-review");
await key("ESC");await wait("!sshToolState().dialog");await click(".ssh-tool-row-main","alpha");await wait("sshToolState().dialogTitle==='alpha'");await click(".ssh-tool-dialog .danger-link","Remove");await click(".ssh-tool-dialog .danger-button","Remove target");await wait("sshToolState().pendingMutation?.operation==='remove'");const remaining={...next,revision:'r4',hosts:next.hosts.filter(h=>h.id!=='user:alpha')};await js("sshToolControl('resolve-mutation',"+JSON.stringify(remaining)+")");await wait("!sshToolState().dialog&&sshToolState().rows.length===2");const focusFailures=[];try{await wait("sshToolState().activeConnected&&sshToolState().activeRow==='legacy'")}catch{focusFailures.push('Removed row focus did not move to the surviving row')};await observe("remove-restores-surviving-row");
const single={revision:'r5',hosts:[next.hosts[2]],warnings:[]};await js("sshToolControl('set-catalog-and-emit',"+JSON.stringify(single)+")");await wait("sshToolState().rows.length===1");await click(".ssh-tool-row-main","beta");await wait("sshToolState().dialogTitle==='beta'");await click(".ssh-tool-dialog .danger-link","Remove");await click(".ssh-tool-dialog .danger-button","Remove target");await wait("sshToolState().pendingMutation?.operation==='remove'");await js("sshToolControl('resolve-mutation',{revision:'r6',hosts:[],warnings:[]})");await wait("!sshToolState().dialog&&sshToolState().rows.length===0");try{await wait("sshToolState().activeConnected&&sshToolState().activeIsAdd")}catch{focusFailures.push('Last row removal did not focus Add')};await observe("remove-last-row-restores-add");if(focusFailures.length)throw Error(focusFailures.join('; '));
fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:true,hidden:true,electron:process.versions.electron,input:"Actual SshToolSettings under controlled deferred DesktopBridge; pointer and keyboard via Electron sendInputEvent",steps},null,2));}catch(error){fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({passed:false,error:String(error.stack||error),state:await state().catch(()=>null),steps},null,2));}finally{win.close();app.quit();}});
`);
  const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "main.cjs"), output, profile], { cwd: profile, stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")), env: { HOME: profile, TMPDIR: profile, PATH: "/usr/bin:/bin" } });
  const timer = setTimeout(() => electron.kill("SIGTERM"), 60_000); try { exitCode = await electron.exited; } finally { clearTimeout(timer); }
} finally { await rm(profile, { recursive: true, force: true }); }
let result: Record<string, unknown>; try { result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); } catch (cause) { result = { passed: false, resultReadError: cause instanceof Error ? cause.message : String(cause) }; }
result.selectedComponent = selectedSource ? {path:selectedSource,sha256:createHash("sha256").update(selectedBytes!).digest("hex")} : {path:join(repo,"apps/desktop/src/renderer/SshToolSettings.tsx"),sha256:before["apps/desktop/src/renderer/SshToolSettings.tsx"]}; result.exitCode = exitCode; result.sourceBeforeBuild = before; result.sourceAfterRun = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceBeforeBuild) === JSON.stringify(result.sourceAfterRun); result.scope = "Actual SshToolSettings and production CSS in hidden isolated Electron. Controlled bridge only; no SSH, provider, personal configuration, app transport or native visual proof."; result.passed = result.passed === true && exitCode === 0 && result.sourceHashesStable; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`SSH tool settings acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
