import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createHash } from "node:crypto";
import { build } from "vite";
import { tmpdir } from "node:os";
const root = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? `.data/welcome-theme-${Date.now()}`), mode = process.argv[3] ?? "dark";
const profile = await mkdtemp(join(tmpdir(), "welcome-theme-"));
await mkdir(output, { recursive: true, mode: 0o700 });
await writeFile(join(output, "fixture.tsx"), `import { createRoot } from "react-dom/client"; import { Welcome } from ${JSON.stringify(join(root,"apps/desktop/src/renderer/Welcome.tsx"))}; import ${JSON.stringify(join(root,"apps/desktop/src/renderer/styles.css"))}; import ${JSON.stringify(join(root,"apps/desktop/src/renderer/theme.css"))}; createRoot(document.getElementById("root")!).render(<Welcome onSelectProject={()=>{}}/>);`);
await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><div id="root"></div><script type="module" src="/fixture.tsx"></script>`);
await build({configFile:join(root,"apps/desktop/vite.config.ts"),root: output, logLevel:"warn", build:{outDir:join(output,"web"),emptyOutDir:true,rollupOptions:{input:join(output,"index.html")}}});
const main = `const{app,BrowserWindow,nativeTheme}=require('electron'),path=require('node:path'),fs=require('node:fs');app.setPath('userData',${JSON.stringify(profile)});nativeTheme.themeSource=${JSON.stringify(mode)};app.whenReady().then(async()=>{const w=new BrowserWindow({show:false,width:800,height:1000,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});try{await w.loadFile(path.join(__dirname,'web/index.html'));w.setContentSize(800,1000);for(let i=0;i<100;i++){if(await w.webContents.executeJavaScript('Boolean(document.querySelector(".welcome-mark"))'))break;await new Promise(r=>setTimeout(r,20))}const read=()=>w.webContents.executeJavaScript('(()=>{const e=document.querySelector(".welcome-mark"),r=e.getBoundingClientRect(),s=getComputedStyle(e),root=getComputedStyle(document.documentElement);return JSON.stringify({mode:${JSON.stringify(mode)},media:matchMedia("(prefers-color-scheme: dark)").matches,theme:document.documentElement.dataset.theme||null,foreground:s.color,opacity:s.opacity,rootText:root.getPropertyValue("--text").trim(),markColor:root.getPropertyValue("--welcome-mark-color").trim(),rect:{x:r.x,y:r.y,width:r.width,height:r.height}})})()',true);const scenes=[];for(const theme of ['system','light','dark','custom']){await w.webContents.executeJavaScript('document.documentElement.dataset.theme='+JSON.stringify(theme==='custom'?'system':theme)+';document.documentElement.style.removeProperty("--welcome-mark-color");'+(theme==='custom'?'document.documentElement.style.setProperty("--welcome-mark-color","rgb(200, 100, 50)");':''));w.webContents.sendInputEvent({type:'mouseMove',x:1,y:1});await new Promise(r=>setTimeout(r,100));const before=JSON.parse(await read());const expected=theme==='custom'?'rgb(200, 100, 50)':theme==='dark'||(theme==='system'&&${JSON.stringify(mode)}==='dark')?'rgb(255, 255, 255)':'rgb(13, 13, 13)';if(before.foreground!==expected||before.opacity!=='.3'&&before.opacity!=='0.3'||before.rect.width===0)throw Error('Invalid idle theme '+theme+': '+JSON.stringify(before));fs.writeFileSync(path.join(__dirname,theme+'-idle.png'),(await w.webContents.capturePage()).toPNG());const r=before.rect,z=w.webContents.getZoomFactor();w.webContents.sendInputEvent({type:'mouseMove',x:Math.round((r.x+r.width/2)*z),y:Math.round((r.y+r.height/2)*z)});await new Promise(r=>setTimeout(r,100));const after=JSON.parse(await read());if(after.foreground!==expected||after.opacity!=='0.4')throw Error('Invalid hover '+theme+': '+JSON.stringify(after));fs.writeFileSync(path.join(__dirname,theme+'-hover.png'),(await w.webContents.capturePage()).toPNG());scenes.push({theme,before,after})}fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({passed:true,scenes,nativePointerHover:true,hidden:true},null,2));app.exit(0)}catch(e){fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({passed:false,error:String(e)},null,2));app.exit(1)}});`;
await writeFile(join(output, "main.cjs"), main); const child = Bun.spawn([process.execPath, join(root, "node_modules/electron/cli.js"), join(output, "main.cjs")], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) }); const timer=setTimeout(()=>child.kill("SIGTERM"),30_000);try { await child.exited; } finally {clearTimeout(timer);await rm(profile,{recursive:true,force:true});}
const result = await Bun.file(join(output, "result.json")).json(); result.source = { path: "apps/desktop/src/renderer/theme.css", sha256: createHash("sha256").update(await readFile(join(root, "apps/desktop/src/renderer/theme.css"))).digest("hex") }; result.scope = "Isolated production CSS/Welcome mark in hidden Electron; system theme and native pointer hover exercised, not native reference parity."; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); console.log(JSON.stringify(result));
if (!result.passed) process.exitCode = 1;
