import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import type { CommandEnvelope, DesktopBridge, DesktopEvent, WorkspaceQuery, WorkspaceTarget } from "@agent-desktop/shared";
import { WorkspacePanel } from "../../apps/desktop/src/renderer/WorkspacePanel";
import { WorkspaceState } from "../../apps/desktop/src/renderer/workspace-state";
import { offlineCache } from "../../apps/desktop/src/renderer/offline-cache";
import "../../apps/desktop/src/renderer/styles.css"; import "../../apps/desktop/src/renderer/theme.css";

declare global { interface Window { workspaceSaveCopyAcceptance: { saveWorkspaceCopy(target: WorkspaceTarget, path: string, hostId: string): Promise<{path: string | null}> }; } }
const params = new URLSearchParams(location.search), endpoint = params.get("endpoint")!, target = JSON.parse(params.get("target")!) as WorkspaceTarget, hostId = params.get("hostId")!;
const request = async (route: string, body: unknown) => { const response = await fetch(endpoint + route, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json(), problem = (value as any).error; if (!response.ok) throw new Error(typeof problem === "string" ? problem : problem?.message ?? `Request failed (${response.status})`); return value as any; };
const listeners = new Set<(event: DesktopEvent) => void>(); setInterval(() => void request("/test/events", {}).then(events => { for (const event of events) for (const listener of listeners) listener(event); }).catch(() => {}), 100);
const runtimeErrors: string[] = []; addEventListener("error", event => runtimeErrors.push(`${event.message}\n${event.error?.stack ?? ""}`)); addEventListener("unhandledrejection", event => runtimeErrors.push(String(event.reason?.stack ?? event.reason)));
const bridge = { workspaceQuery: (owner: WorkspaceTarget, query: WorkspaceQuery, selectedHost?: string) => request("/v1/workspace/query", { target: owner, query, owner: selectedHost }), command: (envelope: CommandEnvelope, selectedHost?: string) => request("/v1/commands", { ...envelope, owner: selectedHost }), subscribe: (listener: (event: DesktopEvent) => void) => { listeners.add(listener); return () => listeners.delete(listener); }, saveWorkspaceCopy: window.workspaceSaveCopyAcceptance.saveWorkspaceCopy } satisfies Pick<DesktopBridge, "workspaceQuery" | "command" | "subscribe" | "saveWorkspaceCopy">;
let current: WorkspaceState, setConnection: (value: boolean) => void;
function Fixture() { const [connected, connectedChange] = useState(true); setConnection = connectedChange; const data = useMemo(() => new WorkspaceState(bridge, hostId, target, offlineCache, hostId), []); current = data; useEffect(() => () => data.stop(), [data]); return <main className="workspace-file-save-copy-fixture"><WorkspacePanel embedded data={data} connected={connected} active filePath="first.ts" name="Save copy fixture" path="/isolated/project" onOpenFile={() => {}} onClose={() => {}} onOpenProject={async () => {}}/></main>; }
document.documentElement.dataset.theme = "dark"; createRoot(document.getElementById("root")!).render(<Fixture/>);
Object.assign(window, { request, connection: (value: boolean) => setConnection(value), editor() { return [...document.querySelectorAll("diffs-container")].flatMap(node => [...(node.shadowRoot?.querySelectorAll<HTMLElement>('[contenteditable="true"]') ?? [])]).find(node => node.getClientRects().length); }, target(selector: string, label?: string) { const node = [...document.querySelectorAll<HTMLElement>(selector)].filter(item => item.getClientRects().length).find(item => label === undefined || item.textContent?.trim() === label || [...item.children].some(child => child.textContent?.trim() === label)); if (!node) throw new Error(`Missing ${selector} ${label ?? ""}`); const box = node.getBoundingClientRect(); return { x: box.x + box.width / 2, y: box.y + box.height / 2 }; }, state() { const doc = current.documents.get("first.ts"), menu = document.querySelector<HTMLElement>(".workspace-file-open-menu"), root = getComputedStyle(document.documentElement); return { restored: current.restored, connected: current.connected, workspaceOpened: current.opened, busy: current.busy, pending: current.pending, errors: current.errors, text: doc?.text, dirty: doc?.dirty, conflict: doc?.conflict, menu: menu && { text: menu.innerText, rect: menu.getBoundingClientRect().toJSON(), items: [...menu.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')].map(item => ({ text: item.innerText, disabled: item.disabled, title: item.title })) }, alerts: [...document.querySelectorAll<HTMLElement>('[role="alert"]')].filter(node => node.getClientRects().length).map(node => node.innerText), focused: document.activeElement instanceof HTMLElement ? { text: document.activeElement.innerText, label: document.activeElement.ariaLabel, role: document.activeElement.getAttribute("role") } : undefined, viewport: { width: innerWidth, height: innerHeight, dpr: devicePixelRatio, visualViewportScale: visualViewport?.scale }, rootFont: { family: root.fontFamily, size: root.fontSize, lineHeight: root.lineHeight }, runtimeErrors: [...runtimeErrors] }; } });
