import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, realpath, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import {saveWorkspaceCopy,workspaceCopySource} from "../../apps/desktop/src/main/workspace-save-copy";
import { build } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const repo = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? `.data/workspace-file-open-${Date.now()}`);
const inlineFiles=process.argv[3]==="inline-files";
const wholeFiles = inlineFiles || process.argv[3] === "whole-files";
const sources = ["apps/host/src/store.ts","apps/host/src/validation.ts","apps/host/src/whole-file-protocol.ts","apps/host/src/omp-workers/runtime.ts","apps/host/src/omp-workers/protocol.ts","apps/host/src/omp/whole-file.ts","apps/host/src/omp/whole-file-history.ts","apps/desktop/src/renderer/composer-clipboard.ts","apps/desktop/src/renderer/ComposerAutocomplete.tsx","apps/desktop/src/renderer/composer-autocomplete.ts","apps/host/src/omp/composer-actions.ts","packages/shared/src/composer-actions.ts","apps/desktop/src/renderer/composer-document.ts","apps/desktop/src/renderer/ComposerEditor.tsx","apps/desktop/src/renderer/composer-editor.css","scripts/acceptance/inline-file-electron.cjs","apps/desktop/src/renderer/ComposerWholeFiles.tsx","apps/desktop/src/renderer/composer-whole-files.css","apps/desktop/src/renderer/whole-file-composer.ts","apps/desktop/src/renderer/drafts.ts","packages/shared/src/whole-file.ts","scripts/acceptance/whole-file-electron.cjs","apps/desktop/src/main/native-context-menu.ts","apps/desktop/src/main/main.ts","apps/desktop/src/main/preload.ts","packages/shared/src/context-menu.ts","apps/desktop/src/renderer/WorkspaceTreeMenu.tsx","apps/desktop/src/renderer/WorkspaceFileTree.tsx","apps/desktop/src/renderer/WorkspaceFileTreePane.tsx","apps/desktop/src/renderer/TranscriptFileReference.tsx","apps/desktop/src/renderer/transcript-file-actions.ts","apps/desktop/src/main/workspace-save-copy.ts","apps/desktop/src/renderer/WorkspacePanel.tsx", "apps/desktop/src/renderer/WorkspaceFileOpen.tsx", "apps/desktop/src/renderer/workspace-file-open.css", "apps/desktop/src/renderer/workspace-state.ts", "apps/desktop/src/renderer/workspace-lease.ts", "apps/desktop/src/renderer/PierreSourceEditor.tsx", "apps/desktop/src/renderer/pierre-source-editor.css", "apps/desktop/src/renderer/styles.css", "apps/desktop/src/renderer/theme.css", "apps/host/src/server.ts", "apps/host/src/workspace-http.ts", "apps/host/src/workspace-open.ts", "apps/host/src/workspace/service.ts", "packages/shared/src/workspace-protocol.ts", "packages/shared/src/protocol.ts", "scripts/acceptance/workspace-file-open.ts", "scripts/acceptance/workspace-file-open-host.ts", "scripts/acceptance/workspace-file-open-browser.tsx", "scripts/acceptance/workspace-file-open-electron.cjs"];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async file => [file, createHash("sha256").update(await readFile(join(repo, file))).digest("hex")])));
await mkdir(output, { recursive: true, mode: 0o700 }); if ((await readdir(output)).length) throw new Error("Output must be empty");
const fixture = await realpath(await mkdtemp(join(tmpdir(), "agent-desktop-workspace-file-open-")));
const host = Bun.spawn([process.execPath, join(import.meta.dir, "workspace-file-open-host.ts"), fixture], { cwd: fixture, env: { HOME: fixture, PATH: process.env.PATH, TMPDIR: fixture, PI_CODING_AGENT_DIR: join(fixture, "agent"), TERM: "dumb", AGENT_DESKTOP_NATIVE_TERMINALS: "0", XDG_DATA_HOME: join(fixture, "xdg-data"), XDG_STATE_HOME: join(fixture, "xdg-state"), XDG_CONFIG_HOME: join(fixture, "xdg-config"), XDG_CACHE_HOME: join(fixture, "xdg-cache") }, ipc: () => {}, stdout: Bun.file(join(output, "host.log")), stderr: Bun.file(join(output, "host-errors.log")) });
let proxy: ReturnType<typeof Bun.serve> | undefined, eventsSocket: WebSocket | undefined;
try {
  for (let i = 0; !(await Bun.file(join(fixture, "ready.json")).exists()); i++) { if (i > 700 || host.exitCode !== null) throw new Error("Native host fixture did not become ready"); await Bun.sleep(50); }
  const ready = JSON.parse(await readFile(join(fixture, "ready.json"), "utf8")), sourceAtBuild = await hashes(); const calls: any[] = [], pendingEvents: unknown[] = [], copies: unknown[] = [];
  const readLaunches = async () => (await readFile(ready.launchesPath, "utf8")).split("\n").filter(Boolean).map((text: string) => JSON.parse(text));
  eventsSocket = new WebSocket(ready.connection.origin.replace("http:", "ws:") + "/v1/events", ["agent-desktop", ready.connection.token]); eventsSocket.addEventListener("message", event => pendingEvents.push({ ...JSON.parse(String(event.data)), hostId: ready.connection.hostId })); await new Promise<void>((done, reject) => { eventsSocket!.addEventListener("open", () => done(), { once: true }); eventsSocket!.addEventListener("error", () => reject(new Error("Native event stream unavailable")), { once: true }); });
  const capability = crypto.randomUUID(), cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "content-type" };
  proxy = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
    const pathname = new URL(request.url).pathname; if (!pathname.startsWith(`/${capability}/`)) return new Response(null, { status: 404 }); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors }); const route = pathname.slice(capability.length + 1), input = await request.json() as any;
    if (route === "/test/events") return Response.json(pendingEvents.splice(0), { headers: cors });
    if(route==="/test/copy") {
      if(input.hostId!==ready.connection.hostId||JSON.stringify(input.target)!==JSON.stringify(ready.target)||input.path!=="second.ts")return new Response(null,{status:403,headers:cors});
      const copy=await saveWorkspaceCopy(input,{choose:async()=>join(fixture,"saved-second.ts"),source:async()=>workspaceCopySource({origin:ready.connection.origin,hostId:ready.connection.hostId,token:ready.connection.token},ready.target,true)});
      copies.push({hostId:input.hostId,target:input.target,path:input.path,text:await readFile(copy.path!,"utf8")});return Response.json(copy,{headers:cors});
    }
    const fixturePath = (file: unknown) => { if (file !== "first.ts" && file !== "second.ts") throw new Error("Unknown fixture file"); return join(ready.project, file); };
    if (route === "/test/file") return Response.json({ text: await readFile(fixturePath(input.file), "utf8") }, { headers: cors });
    if (route === "/test/control") { await writeFile(ready.controlPath, JSON.stringify({ availability: input.availability ?? "normal", launch: input.launch ?? "success" }), { mode: 0o600 }); return Response.json({ updated: true }, { headers: cors }); }
    if (route === "/test/state") { const native = await (await fetch(ready.connection.origin + "/v1/state", { headers: { Authorization: `Bearer ${ready.connection.token}` } })).json() as any; return Response.json({ calls, copies, launches: await readLaunches(), sessions: native.sessions?.length, draft: native.drafts?.find((value: any) => value.id === "new-conversation") }, { headers: cors }); }
    if (wholeFiles && route === "/test/draft") {
      if (input.owner !== ready.connection.hostId || input.command?.type !== "draft.put" || input.command.draft?.id !== "whole-file-ui") return new Response(null,{status:403,headers:cors});
      delete input.owner;
      const response=await fetch(ready.connection.origin+(input.commandVersion===9?"/v9/commands":input.commandVersion===8?"/v8/commands":"/v7/commands"),{method:"POST",headers:{Authorization:`Bearer ${ready.connection.token}`,"Content-Type":"application/json"},body:JSON.stringify(input)});
      return new Response(await response.arrayBuffer(),{status:response.status,headers:{...cors,"Content-Type":"application/json"}});
    }
    if (wholeFiles && route === "/test/whole-state") {
      const state=await (await fetch(ready.connection.origin+"/v1/state",{headers:{Authorization:`Bearer ${ready.connection.token}`}})).json() as any;
      return Response.json({draft:state.drafts?.find((draft:any)=>draft.id==="whole-file-ui"),sessions:state.sessions?.length},{headers:cors});
    }
    if (route !== "/v1/workspace/query" && route !== "/v1/commands" && !(inlineFiles && ["/v1/composer/actions","/v1/composer/completions"].includes(route))) return new Response(null, { status: 403, headers: cors }); if (input.owner !== ready.connection.hostId) return new Response(null, { status: 403, headers: cors }); delete input.owner;
    if (route === "/v1/commands" && (input.command?.type !== "workspace.mutate" || !["file.open", "file.write"].includes(input.command?.action?.type))) return new Response(null, { status: 403, headers: cors });
    const call = { route, query: input.query?.type, id: input.id, command: input.command?.type, action: input.command?.action?.type, path: input.command?.action?.path, targetId: input.command?.action?.targetId, text: input.command?.action?.text, returnedAt: undefined as number | undefined, status: undefined as number | undefined }; calls.push(call);
    const response = await fetch(ready.connection.origin + route, { method: "POST", headers: { Authorization: `Bearer ${ready.connection.token}`, "Content-Type": "application/json", "X-Agent-Host-Id": ready.connection.hostId }, body: JSON.stringify(input) }); call.status = response.status; call.returnedAt = Date.now(); return new Response(await response.arrayBuffer(), { status: response.status, headers: { ...cors, "Content-Type": "application/json" } });
  }});
  await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;height:100%;overflow:hidden}.workspace-file-open-fixture{display:flex;height:100vh}.workspace-file-open-fixture>.workspace-panel{position:relative;flex:1;width:auto;min-width:0}</style><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "workspace-file-open-browser.tsx"))}"></script>`);
  await build({ configFile: false, root: output, plugins: [react(), tailwindcss()], base: "./", build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } }); await writeFile(join(output, "launch.json"), JSON.stringify({ endpoint: `http://127.0.0.1:${proxy.port}/${capability}`, target: ready.target, hostId: ready.connection.hostId, project: ready.project, files: ready.files, wholeFiles, inlineFiles, profile: join(fixture, "electron-profile") }), { mode: 0o600 });
  const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(import.meta.dir, inlineFiles ? "inline-file-electron.cjs" : wholeFiles ? "whole-file-electron.cjs" : "workspace-file-open-electron.cjs"), output], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) }); const timer = setTimeout(() => electron.kill("SIGTERM"), 120_000), code = await electron.exited; clearTimeout(timer);
  const result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); result.sourceAtBuild = sourceAtBuild; result.sourceAfterRun = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceAtBuild) === JSON.stringify(result.sourceAfterRun); result.passed &&= code === 0 && result.sourceHashesStable; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`Workspace file open acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
} finally { eventsSocket?.close(); proxy?.stop(true); if (host.exitCode === null) { try { host.send({ stop: true }); } catch {} } await host.exited; await rm(fixture, { recursive: true, force: true }); await rm(join(output, "launch.json"), { force: true }); }
