import { app, BrowserWindow, ipcMain } from "electron";
import { appendFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { saveWorkspaceCopy, workspaceCopyOutcome, workspaceCopySource } from "../../apps/desktop/src/main/workspace-save-copy";

async function main() {
const output = process.argv[2]!, launch = JSON.parse(await readFile(join(output, "launch.json"), "utf8")); app.setPath("userData", launch.profile); app.commandLine.appendSwitch("disable-renderer-backgrounding");
const control = async () => JSON.parse(await readFile(launch.controlPath, "utf8"));
ipcMain.handle("acceptance:workspace-save-copy", async (_event, target, path, hostId) => workspaceCopyOutcome(() => saveWorkspaceCopy({ target, path, hostId }, {
  choose: async defaultName => { const value = await control(); await appendFile(launch.mainCallsPath, JSON.stringify({ target, path, hostId, defaultName, dialog: "injected", choice: value.choice, selected: value.selected }) + "\n"); return value.selected; },
  source: async () => workspaceCopySource({ origin: launch.copyEndpoint, hostId: launch.hostId, token: "acceptance-capability" }, target, false),
})));
await app.whenReady();
const win = new BrowserWindow({ width: 1440, height: 1000, show: false, useContentSize: true, webPreferences: { preload: launch.preload, sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
const js = (source: string) => win.webContents.executeJavaScript(source), sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms)); const checks: string[] = [], captures: any[] = [], consoleMessages: string[] = [], rendererGone: any[] = [];
win.webContents.on("console-message", (...args) => consoleMessages.push(args.slice(1).map(String).join(" | "))); win.webContents.on("render-process-gone", (_event, details) => rendererGone.push(details));
const wait = async (source: string) => { for (let i = 0; i < 1000; i++) { if (await js(source)) return; await sleep(25); } throw new Error("Condition failed: " + source); };
const click = async (selector: string, label?: string) => { const point = await js(`window.target(${JSON.stringify(selector)},${JSON.stringify(label)})`); for (const type of ["mouseMove", "mouseDown", "mouseUp"] as const) win.webContents.sendInputEvent({ type, ...(type === "mouseMove" ? {} : { button: "left", clickCount: 1 }), ...point }); await sleep(100); };
const chord = async (keyCode: string, modifiers: Array<"meta" | "control" | "shift" | "alt"> = []) => { const normalized = ({ ArrowDown: "Down", ArrowUp: "Up", Enter: "Return" } as Record<string,string>)[keyCode] ?? keyCode; win.webContents.sendInputEvent({ type: "keyDown", keyCode: normalized, modifiers }); if (keyCode === "Enter") win.webContents.sendInputEvent({ type: "char", keyCode: "\r", modifiers }); win.webContents.sendInputEvent({ type: "keyUp", keyCode: normalized, modifiers }); await sleep(80); };
const replace = async (value: string) => { const focused = await js(`(()=>{const node=window.editor();if(!node)return false;node.focus();return node.getRootNode().activeElement===node})()`); if (!focused) throw new Error("Editor focus failed"); await chord("a", ["meta"]); await win.webContents.insertText(value); await sleep(100); };
const state = () => js("window.request('/test/state',{})"), controlDialog = (choice: string, sourceChange = false, changedText?: string) => js(`window.request('/test/control',{choice:${JSON.stringify(choice)},sourceChange:${sourceChange},changedText:${JSON.stringify(changedText)}})`);
const capture = async (name: string) => { const image = await win.webContents.capturePage(); const fs = await import("node:fs"); fs.writeFileSync(join(output, `${name}.png`), image.toPNG()); captures.push({ name, raster: image.getSize(), frame: win.getBounds(), rendererZoomFactor: win.webContents.getZoomFactor(), state: await js("window.state()"), host: await state() }); };
let step = "load";
try {
  await win.loadFile(join(output, "web/index.html"), { query: { endpoint: launch.endpoint, target: JSON.stringify(launch.target), hostId: launch.hostId } }); win.webContents.focus(); await wait(`window.state().restored&&window.editor()`); if (await js("window.state().workspaceOpened!==undefined")) throw new Error("Dedicated fixture selected the generic file path");
  step = "cancel"; await controlDialog("cancel"); await click(".workspace-file-open-options"); await wait(`window.state().menu?.items.some(item=>item.text==='Save as…')`); await chord("End"); await wait(`window.state().focused?.text==='Save as…'`); await js(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`); await capture("00-save-as-menu-keyboard"); const beforeCancel = await state(); await chord("Enter"); await wait(`!window.state().menu`); await sleep(150); let observed = await state(); if (observed.copyCalls.length !== beforeCancel.copyCalls.length || observed.destinations.success.exists || observed.mainCalls.length !== 1 || observed.mainCalls[0].choice !== "cancel" || observed.mainCalls[0].selected !== null) throw new Error("Canceled injected dialog read or wrote file data: " + JSON.stringify(observed)); checks.push("Native keyboard selection reaches Save as; the injected canceled dialog returns before source creation, with zero copy queries or destination writes");
  step = "dirty-success"; const initial = launch.files["first.ts"], dirty = initial + "export const unsavedInEditor = true;\n"; await replace(dirty); await wait(`window.state().dirty&&window.state().text===${JSON.stringify(dirty)}`); await controlDialog("success"); await click(".workspace-file-open-options"); await wait(`window.state().menu?.items.some(item=>item.text==='Save as…')`); await chord("End"); await chord("Enter"); await wait(`window.request('/test/state',{}).then(value=>value.destinations.success.exists&&value.destinations.success.text===${JSON.stringify(initial)}&&!window.state().busy)`); observed = await state(); if (observed.hostFile !== initial || !await js("window.state().dirty") || await js("window.state().text") !== dirty || await js("window.state().workspaceOpened!==undefined")) throw new Error("Save as forced the dirty editor into the host or changed file identity"); await capture("00-dirty-byte-exact-save-as"); checks.push("Save as exports byte-exact current host contents through production copy-info/chunk validation while retaining the different dirty editor buffer and dedicated file identity");
  await wait(`window.request('/test/state',{}).then(value=>value.hostFile===${JSON.stringify(dirty)}&&!window.state().dirty)`);
  step = "source-error"; const changed = dirty + "export const ownerChangedDuringCopy = true;\n", protectedText = "DESTINATION_MUST_STAY_UNTOUCHED\n"; await controlDialog("error", true, changed); await click(".workspace-file-open-options"); await wait(`window.state().menu?.items.some(item=>item.text==='Save as…')`); await chord("End"); await chord("Enter"); await wait(`window.state().alerts.some(text=>text.includes('Could not save a copy'))`); observed = await state(); const visibleError = await js(`window.state().alerts.find(text=>text.includes('Could not save a copy'))`); if (!visibleError.includes("The source file changed before this copy chunk. Choose Save as again.") || ["Error invoking", "HostRequestError", "acceptance:"].some(value => visibleError.includes(value)) || observed.destinations.error.text !== protectedText || observed.hostFile !== changed || !observed.copyCalls.some((call: any) => call.status !== 200)) throw new Error("Host source-change error was not cleanly serialized or preserved the destination: " + JSON.stringify({ visibleError, observed })); await capture("01-host-change-error-destination-preserved");
  step = "recovery"; await controlDialog("error"); await click(".workspace-file-open-options"); await wait(`window.state().menu?.items.some(item=>item.text==='Save as…')`); await chord("End"); await chord("Enter"); await wait(`window.request('/test/state',{}).then(value=>value.destinations.error.text===${JSON.stringify(changed)}&&!window.state().alerts.some(text=>text.includes('Could not save a copy')))`); checks.push("A host revision error leaves the existing destination untouched and visible error state; a later native Save as retry replaces it with the now-stable host bytes"); await capture("02-save-as-recovered");
  step = "offline"; await js("window.connection(false)"); await wait(`!window.state().connected`); const beforeOffline = await state(); await click(".workspace-file-open-options"); await wait(`window.state().menu?.items.some(item=>item.text==='Save as…'&&item.disabled&&item.title.includes('Reconnect'))`); await chord("End"); await capture("03-offline-save-as-disabled"); await chord("Escape"); await sleep(150); observed = await state(); if (observed.copyCalls.length !== beforeOffline.copyCalls.length || observed.mainCalls.length !== beforeOffline.mainCalls.length) throw new Error("Offline Save as reached IPC or the host"); checks.push("Offline mode leaves Save as visible but disabled with a reconnect explanation and issues no dialog IPC or host copy query");
  const renderer = await js("window.state()"), finalState = await state(), writes = finalState.calls.filter((call: any) => call.action === "file.write"); if (finalState.sessions !== 0 || finalState.draft?.text !== "EXISTING_UNSENT_SAVE_COPY_DRAFT" || finalState.draft?.projectId !== launch.target.projectId || finalState.draft?.model !== null || finalState.draft?.revision !== 1 || writes.length !== 1 || writes[0].text !== dirty || renderer.runtimeErrors.length || renderer.pending || renderer.busy || renderer.workspaceOpened !== undefined || rendererGone.length) throw new Error("Final scope/state proof failed: " + JSON.stringify({ renderer, finalState })); checks.push(`Four injected dialog invocations comprised one cancellation and three accepted choices, producing two successful exports and one guarded host failure; one autosave was the only workspace mutation, with zero sessions and an unchanged draft`);
  const fs = await import("node:fs"); fs.writeFileSync(join(output, "result.json"), JSON.stringify({ passed: true, checks, captures, finalState, hidden: true, productionMainCopyHelper: true, injectedNativeDialogBoundary: true, actualNativeDialogShown: false, actualOsApplicationLaunch: false, nativeWindowPhysicalPixelParity: false, consoleMessages, rendererGone, scope: "Production WorkspaceFileOpen, WorkspacePanel, WorkspaceState, saveWorkspaceCopy and workspaceCopySource run in hidden Electron against an authenticated isolated host. Electron keyboard/mouse input, IPC, owner-host snapshot queries and real disposable filesystem writes are exercised. Native dialog selection is injected; captures are renderer page rasters plus DOM measurements, and no OS application launches; visible/native-window, physical-input and matched screenshot/pixel parity are excluded." }, null, 2)); app.exit(0);
} catch (error) { await capture("failure").catch(() => {}); const fs = await import("node:fs"); fs.writeFileSync(join(output, "result.json"), JSON.stringify({ passed: false, step, error: String(error), checks, captures, renderer: await js("window.state()").catch(() => null), host: await state().catch(() => null), consoleMessages, rendererGone }, null, 2)); app.exit(1); }
}
void main();
