import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = process.argv[2]!, project = join(root, "project"), agent = join(root, "agent");
const first = ['# Image fixture', '', '![Wide diagram](../assets/wide.svg "Wide title")', '', `![Small diagram](file://${project}/assets/small.svg)`, '', '![Reference diagram][logo]', '', '![No extension](../assets/extensionless)', '', '![Missing diagram](../assets/missing.png)', '', '![Web image](https://example.invalid/never-request.png)', '', '![Data image](data:image/png;base64,AA==)', '', 'End of fixture.', '', '[logo]: ../assets/small.svg "Reference title"'].join('\n');
const files = { "docs/guide.md": first, "src/main.ts": "one\ntwo\nthree\nfour\n", "assets/wide.svg": '<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="240"><rect width="1600" height="240" fill="#496b91"/><!--' + 'x'.repeat(2 * 1024 * 1024) + '--></svg>', "assets/small.svg": '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="32"><rect width="64" height="32" fill="#be8d52"/></svg>' };
await Promise.all([mkdir(join(project,"assets"), { recursive: true, mode: 0o700 }), mkdir(join(project,"docs"), { recursive: true, mode: 0o700 }), mkdir(join(project,"src"), { recursive: true, mode: 0o700 }), mkdir(agent, { recursive: true, mode: 0o700 })]);
await writeFile(join(agent, "config.yml"), "extensions: []\n"); await Promise.all(Object.entries(files).map(([path, text]) => writeFile(join(project, path), text, { mode: 0o600 })));
await writeFile(join(project, "assets/extensionless"), Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64"));
Bun.spawnSync(["git", "init", "-q", project]); Bun.spawnSync(["git", "-C", project, "config", "user.name", "Workspace Images Acceptance"]); Bun.spawnSync(["git", "-C", project, "config", "user.email", "workspace-markdown-images@example.invalid"]); Bun.spawnSync(["git", "-C", project, "add", "."]); Bun.spawnSync(["git", "-C", project, "commit", "-qm", "Fixture baseline"]);
const { startHost } = await import("../../apps/host/src/server"); const host = await startHost({ dataDirectory: join(root, "data"), agentDirectory: agent, discoveryDirectory: project, workerPath: join(import.meta.dir, "../../apps/host/src/omp-workers/fixtures/no-provider-worker.ts"), tailscale: false, port: 0 });
const request = async (route: string, body: unknown) => { const response = await fetch(host.connection.origin + route, { method: "POST", headers: { Authorization: `Bearer ${host.connection.token}`, "Content-Type": "application/json", "X-Agent-Host-Id": host.connection.hostId }, body: JSON.stringify(body) }); const value = await response.json() as any; if (!response.ok) throw new Error(`Fixture setup failed (${response.status}): ${JSON.stringify(value)}`); return value; };
const projectResult = await request("/v1/commands", { id: "workspace-markdown-images-project", command: { type: "project.add", path: project } }); if (!projectResult.ok) throw new Error("Project creation failed"); const target = { projectId: projectResult.value.id };
const draft = await request("/v5/commands", { id: "workspace-markdown-images-draft", commandVersion: 5, command: { type: "draft.put", draft: { id: "new-conversation", text: "EXISTING_UNSENT_MARKDOWN_DRAFT", projectId: target.projectId, model: null }, expectedRevision: 0 } }); if (!draft.ok) throw new Error("Draft creation failed");
await writeFile(join(root, "ready.json"), JSON.stringify({ connection: host.connection, target, project, draft: draft.value }), { mode: 0o600 }); process.on("message", () => void host.stop().then(() => process.exit(0)));
