import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, realpath, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { build } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const repo = resolve(import.meta.dir, "../.."), output = resolve(process.argv[2] ?? `.data/workspace-file-save-copy-${Date.now()}`);
const sources = ["apps/desktop/src/main/workspace-save-copy.ts", "apps/desktop/src/main/host-transport.ts", "apps/desktop/src/main/preload.ts", "apps/desktop/src/renderer/WorkspacePanel.tsx", "apps/desktop/src/renderer/WorkspaceFileOpen.tsx", "apps/desktop/src/renderer/workspace-file-open.css", "apps/desktop/src/renderer/workspace-state.ts", "apps/desktop/src/renderer/workspace-lease.ts", "apps/desktop/src/renderer/PierreSourceEditor.tsx", "apps/desktop/src/renderer/pierre-source-editor.css", "apps/desktop/src/renderer/styles.css", "apps/desktop/src/renderer/theme.css", "apps/host/src/server.ts", "apps/host/src/workspace-http.ts", "apps/host/src/workspace/service.ts", "packages/shared/src/workspace-protocol.ts", "packages/shared/src/protocol.ts", "scripts/acceptance/workspace-file-save-copy.ts", "scripts/acceptance/workspace-file-save-copy-host.ts", "scripts/acceptance/workspace-file-save-copy-browser.tsx", "scripts/acceptance/workspace-file-save-copy-electron.ts", "scripts/acceptance/workspace-file-save-copy-preload.cjs"];
const hashes = async () => Object.fromEntries(await Promise.all(sources.map(async file => [file, createHash("sha256").update(await readFile(join(repo, file))).digest("hex")])));
await mkdir(output, { recursive: true, mode: 0o700 }); if ((await readdir(output)).length) throw new Error("Output must be empty");
const fixture = await realpath(await mkdtemp(join(tmpdir(), "agent-desktop-workspace-save-copy-"))), exportsDirectory = join(fixture, "exports"), controlPath = join(fixture, "dialog-control.json"), mainCallsPath = join(fixture, "main-calls.jsonl");
await mkdir(exportsDirectory, { mode: 0o700 }); const destinations = { success: join(exportsDirectory, "first-copy.ts"), error: join(exportsDirectory, "protected-copy.ts") }; await writeFile(destinations.error, "DESTINATION_MUST_STAY_UNTOUCHED\n", { mode: 0o600 }); await writeFile(controlPath, JSON.stringify({ choice: "cancel", selected: null }), { mode: 0o600 }); await writeFile(mainCallsPath, "", { mode: 0o600 });
const host = Bun.spawn([process.execPath, join(import.meta.dir, "workspace-file-save-copy-host.ts"), fixture], { cwd: fixture, env: { HOME: fixture, PATH: process.env.PATH, TMPDIR: fixture, PI_CODING_AGENT_DIR: join(fixture, "agent"), TERM: "dumb", AGENT_DESKTOP_NATIVE_TERMINALS: "0", XDG_DATA_HOME: join(fixture, "xdg-data"), XDG_STATE_HOME: join(fixture, "xdg-state"), XDG_CONFIG_HOME: join(fixture, "xdg-config"), XDG_CACHE_HOME: join(fixture, "xdg-cache") }, ipc: () => {}, stdout: Bun.file(join(output, "host.log")), stderr: Bun.file(join(output, "host-errors.log")) });
let proxy: ReturnType<typeof Bun.serve> | undefined, eventsSocket: WebSocket | undefined;
try {
  for (let i = 0; !(await Bun.file(join(fixture, "ready.json")).exists()); i++) { if (i > 700 || host.exitCode !== null) throw new Error("Native host fixture did not become ready"); await Bun.sleep(50); }
  const ready = JSON.parse(await readFile(join(fixture, "ready.json"), "utf8")), sourceAtBuild = await hashes(); const calls: any[] = [], copyCalls: any[] = [], pendingEvents: unknown[] = []; let changeApplied = false;
  eventsSocket = new WebSocket(ready.connection.origin.replace("http:", "ws:") + "/v1/events", ["agent-desktop", ready.connection.token]); eventsSocket.addEventListener("message", event => pendingEvents.push({ ...JSON.parse(String(event.data)), hostId: ready.connection.hostId })); await new Promise<void>((done, reject) => { eventsSocket!.addEventListener("open", () => done(), { once: true }); eventsSocket!.addEventListener("error", () => reject(new Error("Native event stream unavailable")), { once: true }); });
  const capability = crypto.randomUUID(), cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "content-type" }, readOptional = async (path: string) => { try { return { exists: true, text: await readFile(path, "utf8"), mode: (await stat(path)).mode & 0o777 }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { exists: false }; throw error; } };
  proxy = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
    const pathname = new URL(request.url).pathname; if (!pathname.startsWith(`/${capability}/`)) return new Response(null, { status: 404 }); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors }); const route = pathname.slice(capability.length + 1), input = await request.json() as any;
    if (route === "/test/events") return Response.json(pendingEvents.splice(0), { headers: cors });
    if (route === "/test/file") return Response.json({ text: await readFile(join(ready.project, "first.ts"), "utf8") }, { headers: cors });
    if (route === "/test/control") { const selected = input.choice === "cancel" ? null : destinations[input.choice as "success" | "error"]; if (input.choice !== "cancel" && !selected) throw new Error("Unknown injected dialog choice"); changeApplied = false; await writeFile(controlPath, JSON.stringify({ choice: input.choice, selected, sourceChange: Boolean(input.sourceChange), changedText: input.changedText }), { mode: 0o600 }); return Response.json({ updated: true }, { headers: cors }); }
    if (route === "/test/state") { const native = await (await fetch(ready.connection.origin + "/v1/state", { headers: { Authorization: `Bearer ${ready.connection.token}` } })).json() as any; const mainCalls = (await readFile(mainCallsPath, "utf8")).split("\n").filter(Boolean).map((text: string) => JSON.parse(text)); return Response.json({ calls, copyCalls, mainCalls, destinations: { success: await readOptional(destinations.success), error: await readOptional(destinations.error) }, hostFile: await readFile(join(ready.project, "first.ts"), "utf8"), sessions: native.sessions?.length, draft: native.drafts?.find((value: any) => value.id === "new-conversation") }, { headers: cors }); }
    if (route === "/main/v1/workspace/query") { if (!input.query || !["file.copy-info", "file.copy-chunk"].includes(input.query.type)) return new Response(null, { status: 403 }); const entry = { query: input.query.type, path: input.query.path, offset: input.query.offset, revision: input.query.revision, status: 0 }; copyCalls.push(entry); const response = await fetch(ready.connection.origin + "/v1/workspace/query", { method: "POST", headers: { Authorization: `Bearer ${ready.connection.token}`, "Content-Type": "application/json", "X-Agent-Host-Id": ready.connection.hostId }, body: JSON.stringify(input) }); const bytes = await response.arrayBuffer(); entry.status = response.status; const control = JSON.parse(await readFile(controlPath, "utf8")); if (response.ok && input.query.type === "file.copy-info" && control.sourceChange && !changeApplied) { changeApplied = true; await writeFile(join(ready.project, "first.ts"), control.changedText, { mode: 0o600 }); } return new Response(bytes, { status: response.status, headers: { "Content-Type": "application/json", "X-Agent-Host-Id": ready.connection.hostId } }); }
    if (route !== "/v1/workspace/query" && route !== "/v1/commands") return new Response(null, { status: 403, headers: cors }); if (input.owner !== ready.connection.hostId) return new Response(null, { status: 403, headers: cors }); delete input.owner;
    if (route === "/v1/commands" && (input.command?.type !== "workspace.mutate" || input.command?.action?.type !== "file.write")) return new Response(null, { status: 403, headers: cors }); calls.push({ route, query: input.query?.type, id: input.id, command: input.command?.type, action: input.command?.action?.type, path: input.command?.action?.path, text: input.command?.action?.text }); const response = await fetch(ready.connection.origin + route, { method: "POST", headers: { Authorization: `Bearer ${ready.connection.token}`, "Content-Type": "application/json", "X-Agent-Host-Id": ready.connection.hostId }, body: JSON.stringify(input) }); return new Response(await response.arrayBuffer(), { status: response.status, headers: { ...cors, "Content-Type": "application/json" } });
  }});
  await writeFile(join(output, "index.html"), `<!doctype html><meta charset="utf-8"><style>html,body,#root{margin:0;width:100%;height:100%;overflow:hidden}.workspace-file-save-copy-fixture{display:flex;height:100vh}.workspace-file-save-copy-fixture>.workspace-panel{position:relative;flex:1;width:auto;min-width:0}</style><div id="root"></div><script type="module" src="${relative(output, join(import.meta.dir, "workspace-file-save-copy-browser.tsx"))}"></script>`);
  await build({ configFile: false, root: output, plugins: [react(), tailwindcss()], base: "./", build: { outDir: join(output, "web"), rollupOptions: { input: join(output, "index.html") } } }); const mainBuild = await Bun.build({ entrypoints: [join(import.meta.dir, "workspace-file-save-copy-electron.ts")], outdir: output, target: "node", format: "cjs", external: ["electron"], naming: "electron.cjs" }); if (!mainBuild.success) throw new Error(mainBuild.logs.join("\n"));
  await writeFile(join(output, "launch.json"), JSON.stringify({ endpoint: `http://127.0.0.1:${proxy.port}/${capability}`, copyEndpoint: `http://127.0.0.1:${proxy.port}/${capability}/main`, target: ready.target, hostId: ready.connection.hostId, project: ready.project, files: ready.files, controlPath, mainCallsPath, profile: join(fixture, "electron-profile"), preload: join(import.meta.dir, "workspace-file-save-copy-preload.cjs") }), { mode: 0o600 });
  const electron = Bun.spawn([process.execPath, join(repo, "node_modules/electron/cli.js"), join(output, "electron.cjs"), output], { stdout: Bun.file(join(output, "electron.log")), stderr: Bun.file(join(output, "electron-errors.log")) }); const timer = setTimeout(() => electron.kill("SIGTERM"), 120_000), code = await electron.exited; clearTimeout(timer);
  const result = JSON.parse(await readFile(join(output, "result.json"), "utf8")); result.sourceAtBuild = sourceAtBuild; result.sourceAfterRun = await hashes(); result.sourceHashesStable = JSON.stringify(result.sourceAtBuild) === JSON.stringify(result.sourceAfterRun); result.passed &&= code === 0 && result.sourceHashesStable; await writeFile(join(output, "result.json"), JSON.stringify(result, null, 2)); if (!result.passed) throw new Error(`Workspace Save as acceptance failed; inspect ${join(output, "result.json")}`); console.log(JSON.stringify({ passed: true, output }));
} finally { eventsSocket?.close(); proxy?.stop(true); if (host.exitCode === null) { try { host.send({ stop: true }); } catch {} } await host.exited; await rm(fixture, { recursive: true, force: true }); await rm(join(output, "launch.json"), { force: true }); }
