import { afterEach, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { HostStore } from "./store";
import { AutomationService, type AutomationSessionState } from "./automations";
import type { AutomationMutation } from "../../../packages/shared/src/automations";
import type { CommandEnvelope, CommandResult, SessionSummary } from "../../../packages/shared/src/protocol";

const roots: string[] = [], stores: HostStore[] = [], services: AutomationService[] = [];
afterEach(async () => { await Promise.all(services.splice(0).map(service => service.dispose())); for (const store of stores.splice(0)) store.close(); for (const root of roots.splice(0)) rmSync(root, {recursive:true,force:true}); });
const session = (id="session"): SessionSummary => ({ id, hostId:"host", projectId:null, cwd:"/tmp", title:"Original", status:"idle", sessionFile:`/tmp/${id}.jsonl`, model:null, createdAt:1, updatedAt:1, archived:false });
function setup(input: { state?: Partial<AutomationSessionState>; dispatch?: (envelope:CommandEnvelope)=>Promise<CommandResult>; outcome?: "completed"|"failed"|"stopped"|"unknown"; completion?: Promise<"completed"|"failed"|"stopped"|"unknown">; now?:()=>number; tickMs?:number; validateDestination?:(destination:any)=>void|Promise<void> } = {}) {
  const root=mkdtempSync(join(tmpdir(),"automation-service-"));roots.push(root);const store=new HostStore(root);stores.push(store); const saved=session(); store.upsertSession({...saved,hostId:store.host.id});
  const calls:CommandEnvelope[]=[]; const service=new AutomationService({records:store.automations,
    dispatch:async envelope => { calls.push(envelope); return input.dispatch ? input.dispatch(envelope)
      : {ok:true,commandId:envelope.id,value:envelope.command.type==="session.create"?{...saved,id:"created",hostId:store.host.id}:undefined}; },
    waitForPrompt:async()=>await (input.completion ?? Promise.resolve(input.outcome ?? "completed")),sessionState:async id=>({session:store.getSession(id),busy:false,hasDraft:false,hasInteraction:false,...input.state}),changed:()=>{},now:input.now,tickMs:input.tickMs,validateDestination:input.validateDestination});services.push(service);return{store,service,calls};
}
const heartbeat=(destination: {kind:"heartbeat";sessionId:string}|{kind:"heartbeat-new";projectId:null;execution:{type:"local"};environment:null;model:null;thinkingLevel:null;approvalMode:null}={kind:"heartbeat",sessionId:"session"}) =>
  ({type:"save",requestId:"save",id:"task",expectedRevision:0,input:{name:"Check",prompt:"Inspect",rrule:"RRULE:FREQ=MINUTELY;INTERVAL=15",destination,notificationPolicy:"all",status:"active"}} as const satisfies AutomationMutation);
const wait = async (condition:()=>boolean) => { for(let i=0;i<100&&!condition();i++)await Bun.sleep(5); expect(condition()).toBe(true); };

test("heartbeat-new creates the original once with a deterministic command and saves its resolved owner",async()=>{const f=setup();const result=await f.service.mutate(heartbeat({kind:"heartbeat-new",projectId:null,execution:{type:"local"},environment:null,model:null,thinkingLevel:null,approvalMode:null}));expect(f.calls.map(call=>call.id)).toEqual(["automation:save:heartbeat:create"]);expect(result.task?.destination).toEqual({kind:"heartbeat",sessionId:"created"});});

test("manual heartbeat settles only after its exact prompt completion",async()=>{let release!:()=>void;const completion=new Promise<"completed">(resolve=>{release=()=>resolve("completed")});const f=setup({completion});const saved=await f.service.mutate(heartbeat());const result=await f.service.mutate({type:"run",requestId:"run",id:"task",expectedRevision:saved.task!.revision});expect(result.run?.status).toBe("reserved");await wait(()=>f.store.automations.getRun(result.run!.id)?.status==="running");release();await wait(()=>f.store.automations.getRun(result.run!.id)?.status==="completed");expect(f.calls.at(-1)?.command).toMatchObject({type:"session.prompt",sessionId:"session",text:"Inspect"});});

test("manual busy heartbeat is visibly failed without dispatch",async()=>{const f=setup({state:{busy:true}});const saved=await f.service.mutate(heartbeat());const manual=await f.service.mutate({type:"run",requestId:"run",id:"task",expectedRevision:saved.task!.revision});await wait(()=>f.store.automations.getRun(manual.run!.id)?.status==="failed");expect(f.calls).toHaveLength(0);});

test("scheduled busy heartbeat is skipped and its cursor advances without a catch-up burst",async()=>{let now=Date.UTC(2026,8,12,12);const f=setup({state:{busy:true},now:()=>now,tickMs:5});const saved=await f.service.mutate(heartbeat());now=saved.task!.nextRunAt!+60_000;f.service.start();await wait(()=>f.store.automations.snapshot().runs[0]?.status==="skipped");expect(f.store.automations.snapshot().runs).toHaveLength(1);expect(f.store.automations.get("task")!.nextRunAt).toBeGreaterThan(now);expect(f.calls).toHaveLength(0);});

test("an exact manual retry reports the run's authoritative terminal state",async()=>{const f=setup({outcome:"unknown"});const saved=await f.service.mutate(heartbeat());const mutation={type:"run",requestId:"run",id:"task",expectedRevision:saved.task!.revision}as const;const admitted=await f.service.mutate(mutation);await wait(()=>f.store.automations.getRun(admitted.run!.id)?.status==="unknown");expect((await f.service.mutate(mutation)).run?.status).toBe("unknown");});

test("editing without changing recurrence preserves the admitted due cursor",async()=>{let now=Date.UTC(2026,8,12,12);const f=setup({now:()=>now});const first=await f.service.mutate(heartbeat());const due=first.task!.nextRunAt;now+=5*60_000;const edit={...heartbeat(),requestId:"edit",expectedRevision:first.task!.revision,input:{...heartbeat().input,prompt:"Updated prompt"}}as const;const updated=await f.service.mutate(edit);expect(updated.task?.nextRunAt).toBe(due);expect(updated.task?.rrule).toBe(first.task?.rrule);});

test("cron destination is revalidated immediately before native run admission",async()=>{let validations=0;const f=setup({validateDestination:destination=>{if(destination.kind==="cron"&&++validations>1)throw new Error("model removed");}});const save={...heartbeat(),input:{...heartbeat().input,destination:{kind:"cron" as const,projectId:null,execution:{type:"local" as const},environment:null,model:{provider:"fixture",id:"model"},thinkingLevel:null,approvalMode:null}}};const saved=await f.service.mutate(save);const run=await f.service.mutate({type:"run",requestId:"run",id:"task",expectedRevision:saved.task!.revision});await wait(()=>f.store.automations.getRun(run.run!.id)?.status==="failed");expect(f.calls).toHaveLength(0);expect(f.store.automations.getRun(run.run!.id)?.error).toContain("model removed");});

test("mutations are refused after scheduler shutdown begins",async()=>{const f=setup();await f.service.dispose();await expect(f.service.mutate(heartbeat())).rejects.toThrow("stopping");});

test("shutdown drains an already-admitted automation mutation",async()=>{let release!:()=>void,entered=false;const gate=new Promise<void>(resolve=>{release=resolve});const f=setup({validateDestination:async()=>{entered=true;await gate;}});const mutation=f.service.mutate(heartbeat());await wait(()=>entered);let stopped=false;const stopping=f.service.dispose().then(()=>{stopped=true});await Bun.sleep(5);expect(stopped).toBe(false);release();await mutation;await stopping;expect(f.store.automations.get("task")).toBeDefined();});

test("manual runs share the scheduler's three-run concurrency cap",async()=>{let release!:()=>void;const completion=new Promise<"completed">(resolve=>{release=()=>resolve("completed")});const f=setup({completion});for(let index=1;index<=4;index++){const id=`session-${index}`;f.store.upsertSession({...session(id),hostId:f.store.host.id});const save={...heartbeat({kind:"heartbeat",sessionId:id}),requestId:`save-${index}`,id:`task-${index}`}as const;const saved=await f.service.mutate(save);await f.service.mutate({type:"run",requestId:`run-${index}`,id:saved.task!.id,expectedRevision:saved.task!.revision});}await wait(()=>f.store.automations.snapshot().runs.some(run=>run.automationId==="task-4"&&run.status==="failed"));expect(f.calls.filter(call=>call.command.type==="session.prompt")).toHaveLength(3);release();await wait(()=>f.store.automations.snapshot().runs.filter(run=>run.status==="completed").length===3);});

test("a scheduler fault is retained and reported during shutdown",async()=>{const f=setup({tickMs:5});const records=f.store.automations as any;const original=records.reserveDue;records.reserveDue=()=>{throw new Error("schedule storage failed")};f.service.start();await Bun.sleep(15);const index=services.indexOf(f.service);if(index>=0)services.splice(index,1);await expect(f.service.dispose()).rejects.toThrow("did not finish cleanly");records.reserveDue=original;});
